### ISSUE TITLE
Support Java 8 Dates in Job and Step Execution [BATCH-2590]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1014]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[BATCH-2590](https://jira.spring.io/browse/BATCH-2590?redirect=false)** and commented

Currently all timestamps on `JobExecution` and `StepExecution` are of type `java.util.Date`. It would be cool if instead they could be directly a Java 8 Date Time API type, `OffsetDateTime` and `ZonedDateTime` are obvious candidates.
Ideally the data type of the corresponding database would be changed from `TIMESTAMP` to `TIMESTAMP WITH TIME ZONE` as well.

---
No further details from [BATCH-2590](https://jira.spring.io/browse/BATCH-2590?redirect=false)

**Comment by ptahchiev** [comment]
Yep +1 here. And also consider changing the job parameter types to be java8 Date Time API.

**Comment by javaHelper** [comment]
@benas - When Spring Batch 5.0.0 will be ready?

**Comment by fmbenhassine** [comment]
While evaluating the change of timestamp fields to `OffsetDateTime`, several issues popped up, see #4209.

For this reason, we have decided to change the type from `java.util.Date` to `java.time.LocalDateTime` for now, and defer the feature of making those fields timezone aware to a future release.

**Comment by uyw4687** [comment]
@fmbenhassine Hello, it seem the datatype is still Date, not LocalDateTime on the API(JobParametersBuilder.addDate).
Is this issue still ongoing or removed?

**Comment by uyw4687** [comment]
It's a bit off-topic, but is there any rationale to exclude addBoolean on the JobParametersBuilder?

**Comment by uyw4687** [comment]
@davidkarlsen sorry I was using spring boot 2. I checked it from code.
How about `addBoolean`? Should I make a new issue?
