### ISSUE TITLE
A CrudRepository implementation is required when we use RepositoryItemWriter [BATCH-2570]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1034]
**[yeswanthreddy](https://jira.spring.io/secure/ViewProfile.jspa?name=yeswanth)** opened **[BATCH-2570](https://jira.spring.io/browse/BATCH-2570?redirect=false)** and commented

A CrudRepository implementation is required when we use RepositoryItemWriter

```java
@Component
public class InventryJpaItemWriter extends RepositoryItemWriter<InventryEntityBatch> {

	@Autowired
	private InventryBatchRepo batchRepo;
		
	@Override
	public void write(List<? extends InventryEntityBatch> items) throws Exception {
		setRepository(batchRepo);
		setMethodName("save");
		batchRepo.save(items);
		afterPropertiesSet();
		super.write(items);
	}
	
	 
	
}
```

---

**Attachments:**
- [e1.PNG](https://jira.spring.io/secure/attachment/23690/e1.PNG) (_19.79 kB_)
- [e2.PNG](https://jira.spring.io/secure/attachment/23689/e2.PNG) (_18.14 kB_)

**Comment by benas** [comment]
Based on the last two comments, I'm closing this issue.
