### ISSUE TITLE
Support Java 8 Dates for Job Parameters [BATCH-2569]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1035]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[BATCH-2569](https://jira.spring.io/browse/BATCH-2569?redirect=false)** and commented

It would be cool if `JobParameter` would support the Java 8 Date and Time API. Since the value on the table is of SQL type `TIMESTAMP` the corresponding type would be `LocalDateTime`.
Unfortunately due the design of the `JobParameter` class with a single `#getValue()` method doing this would break backward compatibility.
One way to avoid this would be a. new `getLocalDate()` method.

---
No further details from [BATCH-2569](https://jira.spring.io/browse/BATCH-2569?redirect=false)

**Comment by parikshitdutta** [comment]
Hi @benas, Please assign me the task, I am starting work on this one.

**Comment by benas** [comment]
Hi @parikshitdutta ,

Thank you for your offer to help.

```
Since the value on the table is of SQL type TIMESTAMP the corresponding type would be LocalDateTime
```

We have a feature request to use timezone aware datatypes (see #871), so I'm not sure `LocalDateTime` would be the right datatype to use if we decide to implement #871. I did not evaluate the impact of such a change yet, so I would like to take some time to think about the best design choices for this feature.

Please note that we did not start working on v5 yet, we just assigned a few issues we think should be addressed in a major version to the v5.0.0 milestone.

**Comment by parikshitdutta** [comment]
Thanks @benas for sharing the information. 
This one can wait, meanwhile I better look into some other issues.

**Comment by fmbenhassine** [comment]
> We have a feature request to use timezone aware datatypes (see https://github.com/spring-projects/spring-batch/issues/871), so I'm not sure LocalDateTime would be the right datatype to use if we decide to implement https://github.com/spring-projects/spring-batch/issues/871. I did not evaluate the impact of such a change yet, so I would like to take some time to think about the best design choices for this feature.

> I will look forward to your finding before taking this task.

@parikshitdutta The impact of #871 was evaluated and the feature was deferred to a future version, see the rationale behind this decision in https://github.com/spring-projects/spring-batch/issues/871#issuecomment-1275230018 and https://github.com/spring-projects/spring-batch/issues/1014#issuecomment-1275272556. Hence, the type of timestamp fields was changed to `java.time.LocalDateTime` for now.
