### ISSUE TITLE
Incorrect behaviour of RepositoryItemReader#jumpToItem() on restart

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1074]
**[Oleh Rohov](https://jira.spring.io/secure/ViewProfile.jspa?name=olehrohov)** opened **[BATCH-2526](https://jira.spring.io/browse/BATCH-2526?redirect=false)** and commented

After restart of batch step RepositoryItemReader reads last already processed item

https://github.com/olehrgf/spring-batch-repository-item-reader-bug

---

**Affects:** 3.0.7

**Reference URL:** https://github.com/olehrgf/spring-batch-repository-item-reader-bug

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/443

1 votes, 3 watchers

**Comment by benas** [comment]
Resolved with #443 .
