### ISSUE TITLE
Allow configure TransactionManager for jobOperator.stop  [BATCH-2524]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1078]
**[Nico](https://jira.spring.io/secure/ViewProfile.jspa?name=niconavarrete)** opened **[BATCH-2524](https://jira.spring.io/browse/BATCH-2524?redirect=false)** and commented

SimpleJobOperator stop() is decorated with `@Transactional`, therefore
we cannot configure the transactionManager name as the other components ,  forcing the implementation of org.springframework.transaction.annotation.TransactionManagementConfigurer to set the transactionManager to use.

---

**Affects:** 3.0.7

**Comment by Matheus-Rangel** [comment]
Any update about this issue?

**Comment by minimalistinnovator** [comment]
I am running into the same problem in one of listeners where I am explicitly calling the SimpleJobOperator to stop the execution.

**Comment by nkuflk** [comment]
Any update about this issue?

**Comment by benas** [comment]
No, we are working on the [upcoming v4.3](https://github.com/spring-projects/spring-batch/milestone/107) and this issue is not planned for it. We will let you know in which version this issue will be addressed. Contributions are welcome.

**Comment by fmbenhassine** [comment]
Along with https://github.com/spring-projects/spring-batch/issues/4195, both the transaction manager and the transaction attributes are now configurable in the proxy created around the `JobOperator`. This is indeed more flexible than the usage of a statically defined `@Transactional` on methods.

cc @nkuflk @Matheus-Rangel @minimalistinnovator
