### ISSUE TITLE
Using Spring Batch JdbcCursorItemReader with NamedParameters [BATCH-2521]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1081]
**[Wellington Baltazar de Souza](https://jira.spring.io/secure/ViewProfile.jspa?name=wbsouza@gmail.com)** opened **[BATCH-2521](https://jira.spring.io/browse/BATCH-2521?redirect=false)** and commented

Find attached the source files adding this feature.

---

**Affects:** 3.0.7

**Reference URL:** http://stackoverflow.com/questions/23222353/using-spring-batch-jdbccursoritemreader-with-namedparameters/38644424#38644424

1 votes, 1 watchers

**Comment by benas** [comment]
The solution suggested in the [linked SO thread](http://stackoverflow.com/questions/23222353/using-spring-batch-jdbccursoritemreader-with-namedparameters/38644424#38644424) suggests to 1) introduce a new concept (`SqlParameterSourceProvider`), 2) implement it with named parameters and 3) extend the `JdbcCursorItemReader` to use the the custom implementation. This is a bit heavy compared to the following two lines used to transform named parameters to jdbc placeholders:

```java
String preparedSql = NamedParameterUtils.substituteNamedParameters(sql, new MapSqlParameterSource(namedParameters));
PreparedStatementSetter preparedStatementSetter = new ArgumentPreparedStatementSetter(NamedParameterUtils.buildValueArray(sql, namedParameters));
```

So as mentioned in my previous comment, I see no need to introduce a new concept to support this feature (trying to avoid [API bloat](https://github.com/spring-projects/spring-batch/issues/3242)) thanks to the `NamedParameterUtils` class from `spring-jdbc`.

A complete example can be found in [this repo](https://github.com/benas/sandbox/blob/master/batch2521) (which also contains an example of [how to use a list as a named parameter](https://stackoverflow.com/questions/54782690)).

**Comment by logie2882** [comment]
@Bean
public JdbcCursorItemReader<Person> itemReader() {
	String sql = "select * from person where id IN(:id) and name IN (:name)";
	Map<String, List<String>> map= new HashMap<>() {{
		map.put("id", Array.asList("22522"));
		map.put("name", "21,22");
	}};
List<String> parameters = map.values().parallelStream.flatMap(c-->c.stream()).collect(Collectors.toList());
ArgumentPreparedStatementSetter argumentPreparedStatementSetter = new ArgumentPreparedStatementSetter(map.toArray());

	return new JdbcCursorItemReaderBuilder<Person>()
	  .name("personItemReader")
	  .dataSource(dataSource())
	  .rowMapper(rowMapper())
	  .sql(sql )
	  .preparedStatementSetter(argumentPreparedStatementSetter)
	  .build();
}

Problem is that its not taking map values of "21 , 20" its failing. Can you please help me on this.

**Comment by benas** [comment]
@logie2882 you are putting multiple values as a String here: `map.put("name", "21,22");`. You need to split those values and pass them as a list (as you did for `id`), something like:

```diff
- map.put("name", "21,22");
+ map.put("name", Arrays.asList("21,22".split(",")));
```

> Can you please help me on this.

Sure, splitting values as shown above should help (I tested this on the same example). If you need further support, please use SO (https://github.com/spring-projects/spring-batch#getting-help). Thank you.

**Comment by logie2882** [comment]
@bean
public JdbcCursorItemReader itemReader() {
String sql = "select * from person where id IN(:id) and name IN (:name)";
Map<String, List> map= new HashMap<>() {{
map.put("id", Arrays.asList("22522"));
map.put("name", Arrays.asList("21,22".split(","));
}};
List parameters = map.values().parallelStream.flatMap(c-->c.stream()).collect(Collectors.toList());
ArgumentPreparedStatementSetter argumentPreparedStatementSetter = new ArgumentPreparedStatementSetter(map.toArray());

return new JdbcCursorItemReaderBuilder<Person>()
  .name("personItemReader")
  .dataSource(dataSource())
  .rowMapper(rowMapper())
  .sql(sql )
  .preparedStatementSetter(argumentPreparedStatementSetter)
  .build();
}

Tried the above said solution , When i pass a single string its working. When i pass multiple string value i am getting exception java.sql.SqlException:Invalid column index.

**Comment by benas** [comment]
As mentioned [previously](https://github.com/spring-projects/spring-batch/issues/1081#issuecomment-613301857), if you need further support, please use SO.

> Tried the above said solution , When i pass a single string its working fine. When passing multiple string value i am getting exception java.sql.SqlException:Invalid column index. The reason for failing is only two IN params but the argumentPreparedStatementSetter is creating 3 param values

`ArgumentPreparedStatementSetter` is a class from Spring Framework, not Spring Batch. So there is nothing we can do on Spring Batch side. You need to flatten the arguments yourself. I already answered this question on SO with a complete code example, see https://stackoverflow.com/questions/54782690.

**Comment by javaHelper** [comment]
@fmbenhassine - Hey, could you please guide here: https://stackoverflow.com/questions/78770590/caused-by-java-sql-sqlexception-parameter-index-out-of-range-2-number-of-pa?
