### ISSUE TITLE
Parsing thousand of XMLs files - MultiResourcePartitioner / SimpleStepExecutionSplitter / commit-interval [BATCH-2520]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1083]
**[Alex Donovan](https://jira.spring.io/secure/ViewProfile.jspa?name=alexdonovann)** opened **[BATCH-2520](https://jira.spring.io/browse/BATCH-2520?redirect=false)** and commented

In test, i have a directory with at least 100 xml files (each file > 500 kb) which i parse with StaxEventItemReader and write to the database. In production i will have more than 100 000 files in one directory.
I have a processor who returns 1 beans for 1 file, and with the commit-interval at 10, at every 10 read, the itemWriter receives the 10 beans.
While using MultiResourceItemReader with no multithreading, everything works fine.

But with MultiResourcePartitioner and 10 threads, if i have more than 100 files in the directory, it is very slow doing the method split in the class SimpleStepExecutionSplitter.

for (Entry<String, ExecutionContext> context : contexts.entrySet()) {

    		// Make the step execution name unique and repeatable
    		String stepName = this.stepName + STEP_NAME_SEPARATOR + context.getKey();
    
    		StepExecution currentStepExecution = jobExecution.createStepExecution(stepName);
    
    		boolean startable = getStartable(currentStepExecution, context.getValue());
    
    		if (startable) {
    			set.add(currentStepExecution);
    		}
    	}

And something i don't understand is that the ItemWriter does not receive 10 beans at a time, but 1 by 1, it's like it does not care about the commit-interval. The processor will return 10 beans (1 bean by thread), and the writer will get 1 by 1.
It's like spring batch count 10 hits in the processor (1 by thread) but does not regroup the 10 hits for the writer.

So i have two problems :
- Why jobRepository.addAll(set) is very slow ?
- If i want the itemWriter to receive 10 beans by 10 beans, i have to custom the processor so that i add into a list of beans, and when the size of the list is 10 return to the itemWriter the list, and i have to synchronized the process.

The processor :
public int returnInterval;

    private static List<RequestBean> multiThreadList = new ArrayList<RequestBean>();
    
    @Override
    public List<RequestBean> process(Object item) throws Exception {		
    	
    	synchronized (this) {
    		multiThreadList.add(new RequestBuilder().build(item, jobControlService));
    		
    		if(multiThreadList.size() == returnInterval) {
    			List<RequestBean> rb = new ArrayList<RequestBean>(multiThreadList);
    			multiThreadList.clear();
    			return rb;
    		}
    		
    		return null;
    	}
    	
    }

The Writer :
public void write(List<? extends NodeValue> items) throws Exception {
if(items != null && items.size() > 0) {
synchronized (this) {
List\<NodeValue> lNodeValue = new ArrayList\<NodeValue>();
for(Object obj : (List\<RequestBean>) items.get(0)) {
RequestBean rb = (RequestBean) obj;
lNodeValue.addAll(rb.getlNodeValue());
}

    			//super.write(lNodeValue);
    			lNodeValue.clear();
    		}
    	}
    }

And the xml conf file :

\<bean id="partitioner" class="org.springframework.batch.core.partition.support.MultiResourcePartitioner" scope="step">
		\<property name="resources" value="#{jobParameters['inboundDir']}" />
	\</bean>

    <batch:job id="appJob">
    	<batch:step id="stepMultiThread">
    		<batch:partition step="appStep" partitioner="partitioner">
    			<batch:handler grid-size="1" task-executor="asyncTaskExecutor" />
    		</batch:partition>
    	</batch:step> 
    </batch:job>
    
    <batch:step id="appStep">
    	<batch:tasklet>
    		<batch:chunk reader="xmlItemReader" writer="dbWriter"
    			processor="processorApp" commit-interval="10" skip-policy="alwaysSkipParsingError">
    		</batch:chunk>
    	</batch:tasklet>
    </batch:step>
    
    <bean id="asyncTaskExecutor" class="org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor">
        <property name="corePoolSize" value="10" />
        <property name="maxPoolSize" value="1000" />
        <property name="allowCoreThreadTimeOut" value="true" />
    </bean>

\<bean id="xmlItemReader" class="org.springframework.batch.item.xml.StaxEventItemReader" scope="step">
		\
		\<property name="fragmentRootElementName" value="#{jobParameters['fragmentRootElementName']}" />
		\<property name="unmarshaller" ref="reportUnmarshaller" />
		\<property name="resource" value="#{stepExecutionContext['fileName']}" />
	\</bean>

    <bean id="processorApp" class="....processor.FilterProcessorApp">
    	
    	<property name="returnInterval" value="10" />
    </bean>

\<bean id="reportUnmarshaller" class="org.springframework.oxm.jaxb.Jaxb2Marshaller">
		\<property name="classesToBeBound">
			\<list>
				\<value>com...bean1\</value>
				\<value>com...bean2\</value>
				\<value>com...bean3\</value>
				\<value>com...bean4\</value>
			\</list>
		\</property>
	\</bean>
\<bean id="dbWriter" class="....writers.JdbcBatchItemDbWriter">
		\<property name="dataSource" ref="dataSource" />
		\<property name="sql">
			\<value>
	           	\<![CDATA[
	           		INSERT INTO NODE_VALUE_BATCH (id, elm_id,elm_lib,elm_value,dest_table,dest_colonne,obligatoire,ordre,position_pk,unique_uid_file) 
	           		VALUES (SEQ_ID_REQ.nextval, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	           	]]>
			\</value>
		\</property>
	    \<property name="itemPreparedStatementSetter">
			\<bean class="....statementsetter.PreparedStatementSetter" />
		\</property>
\</beans>

If i don't synchronize using that :

The processor :

public class FilterProcessorApp implements ItemProcessor<Object, RequestBean> {

    @Autowired
    public JobControlService jobControlService;
    
    @Override
    public RequestBean process(Object item) throws Exception {
    	return new RequestBuilder().build(item, jobControlService);
    }

}

The Writer :

public void write(List<? extends NodeValue> items) throws Exception {
for(Object obj : items) {
RequestBean rb = (RequestBean) obj;
lNodeValue.addAll(rb.getlNodeValue());
}
super.write(lNodeValue);
lNodeValue.clear();
}

The Writer will always get just 1 RequestBean in MultiThreading.

Thank you for the reading =) Hope i was clear.

---

**Affects:** 3.0.7

**Comment by benas** [comment]
There is a lot of code and multiple questions in this issue. Please narrow the scope and provide a minimal project instead.

> with MultiResourcePartitioner and 10 threads, if i have more than 100 files in the directory, it is very slow doing the method split in the class SimpleStepExecutionSplitter.

Step partitioning was optimized in #891 which has been released in v4.2. I'm closing this issue for now as I believe it is outdated. But if you still have the problem, please provide a minimal project to reproduce it and we can analyse further.
