### ISSUE TITLE
Integrate SAP Hana as supported Spring Batch database [BATCH-2515]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1087]
**[Christian Laboranowitsch](https://jira.spring.io/secure/ViewProfile.jspa?name=claboran)** opened **[BATCH-2515](https://jira.spring.io/browse/BATCH-2515?redirect=false)** and commented

As SAP Hana gains more and more attraction for building Datawarehouse infrastructures, it could make sense to add it to the supported database platforms. I did an integration for one of my customers and had already created before a showcase on github: https://github.com/claboran/priceimporter.

---

**Affects:** 3.0.7

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/595

2 votes, 5 watchers

**Comment by sergioag** [comment]
Hi, is there any news about this issue? The PR needs a bit of updating too...

**Comment by breglerj** [comment]
I have updated the PR. Let me know if you need anything else.

**Comment by luka223** [comment]
Hi,

Is there any ETA when PR will be merged?

**Comment by benas** [comment]
This feature will be included in Spring Batch v5, which will be based on Spring Framework v6. The release date has not been set yet as it depends on Spring Framework, but it should be sometime in Q4 2022 after [Spring Framework v6 GA](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6).

**Comment by benas** [comment]
Resolved with #595 .
