### ISSUE TITLE
ChunkMessageChannelItemWriter Reply Channel Issues [BATCH-2507]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1096]
**[Gary Russell](https://jira.spring.io/secure/ViewProfile.jspa?name=grussell)** opened **[BATCH-2507](https://jira.spring.io/browse/BATCH-2507?redirect=false)** and commented

The `ChunkMessageChannelItemWriter` won't work in a multi-threaded environment, even when using step scope - all requests are sharing the same reply channel.

The handler should be using a `replyChannel` header (one per step) instead of referencing a channel in the application context.

See similar code in the [MessageChannelPartitionHandler](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-integration/src/main/java/org/springframework/batch/integration/partition/MessageChannelPartitionHandler.java#L212) which was fixed to use a unique queue for each new request.

Even there, I'm not sure there's ever a valid case for explicitly injecting a shared channel.

---

**Affects:** 3.0.7

**Reference URL:** http://stackoverflow.com/questions/37332048/spring-batch-how-to-configure-remote-chunking-for-multiple-jobs-running-in-a-t

**Issue Links:**
- [BATCH-2228](https://jira.spring.io/browse/BATCH-2228) Remote-chunking implementation does not support parallel executions of the same job
 (_**"duplicates"**_)
- [BATCH-2508](https://jira.spring.io/browse/BATCH-2508) ChunkMessageChannelItemWriter Reply Channel Issues
 (_**"is duplicated by"**_)

3 votes, 5 watchers

**Comment by chpritam** [comment]
Any update on this ticket?

**Comment by akashsharma3030** [comment]
Any update on this ticket

**Comment by fmbenhassine** [comment]
Closing this as duplicate of #1372.
