### ISSUE TITLE
create Maven BOM for Spring Batch modules

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1097]
**[David J. M. Karlsen](https://jira.spring.io/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** opened **[BATCH-2502](https://jira.spring.io/browse/BATCH-2502?redirect=false)** and commented

It would be nice to have a BOM for spring-batch like for spring framework, spring security etc:

http://stackoverflow.com/questions/14874966/how-to-use-bom-file-with-maven
http://mvnrepository.com/artifact/org.springframework/spring-framework-bom

---

**Reference URL:** https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

1 votes, 5 watchers

**Comment by dbarciela** [comment]
I created a BOM for spring-batch https://github.com/spring-projects/spring-batch/pull/4078
