### ISSUE TITLE
StepBuilderFactory Only Supports Listener Annotations, Not Listener Interfaces [BATCH-2501]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1098]
**[Jeff](https://jira.spring.io/secure/ViewProfile.jspa?name=jefff)** opened **[BATCH-2501](https://jira.spring.io/browse/BATCH-2501?redirect=false)** and commented

When adding listeners to a step using the step builder, the step builder only broadcasts to listeners that use listener annotations, such as `@OnReadError`. Listeners that implement interfaces, such as "public class ExceptionListener implements ItemWriteListener", never receive broadcasted events.

> stepBuilderFactory.get("somethingFlatIdStep")
> .<TheObjectType, TheObjectType> chunk(25000)
> .reader(somethingFlatIdReader)
> .processor(new PassThroughItemProcessor\<TheObjectType>())
> .writer(somethingFlatIdWriter)
> .transactionAttribute(ConfigUtil.makeTransAttribute())
> .listener(new ExceptionListener())
> .listener(new AnnotationEventListener())
> .build();

Two files attached exemplifying a listener class that doesnt work (uses spring batch listener interfaces) and a listener clas that does work (uses listener annotations).

---

**Affects:** 3.0.6

**Attachments:**
- [AnnotationEventListener.java](https://jira.spring.io/secure/attachment/23377/AnnotationEventListener.java) (_1.95 kB_)
- [ExceptionListener.java](https://jira.spring.io/secure/attachment/23378/ExceptionListener.java) (_2.52 kB_)

**Comment by fmbenhassine** [comment]
Resolved with #3989 .
