### ISSUE TITLE
Fault tolerant step builder should handle chunks of one item more efficiently [BATCH-2494]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1108]
**[lbehnke](https://jira.spring.io/secure/ViewProfile.jspa?name=lbehnke)** opened **[BATCH-2494](https://jira.spring.io/browse/BATCH-2494?redirect=false)** and commented

My scenario:
I am building a database migration tool that pumps data from one system into another. The systems are accessed via their SOAP interfaces, respectively. Both, reading and writing is expensive, so a chunk size of 1 seems to be appropriate.
As I want to be able to skip a limited number of faulty records, I use the fault tolerant step builder.

As discussed in https://jira.spring.io/browse/BATCH-2334 spring batch must pinpoint the faulty record after a failed write and therefore iterates the chunk items again. I understand that this is a design decision.

However, it seems inefficient to do this iteration if we have a chunk size of 1. Spring batch should handle this special scenario and avoid unnecessary calls.

---

**Affects:** 3.0.6

**Comment by benas** [comment]
> spring batch must pinpoint the faulty record after a failed write [...] However, it seems inefficient to do this iteration if we have a chunk size of 1. Spring batch should handle this special scenario and avoid unnecessary calls.

Closing this as duplicate of #2064 .
