### ISSUE TITLE
JSR-352 Property Substitutions expression with default value doesn't work as expected [BATCH-2488]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1114]
**[Arindam Ray](https://jira.spring.io/secure/ViewProfile.jspa?name=arindam.ray)** opened **[BATCH-2488](https://jira.spring.io/browse/BATCH-2488?redirect=false)** and commented

As per JSR352 specification:

Substitutions expressions may include a default value using the "?:" operator. The default is applied if the substitution's principle value expression resolves to the empty string ""

For example:
\<property name="infile.name" value="#{jobParameters['infile.name']}?:in.txt;" />
Resolved property: infile.name = value of infile.name job parameter or "in.txt" if infile.name job parameter is unspecified.

But, for this case when #{jobParameters['infile.name']} getting resolved to some value, say input.txt, the infile.name value is coming as "input.txt?:in.txt" which is not correct. When we are not specifying #{jobParameters['infile.name']}, the infile.name value is coming as "in.txt" which is correct.

---

**Affects:** 3.0.4, 3.0.6

**Attachments:**
- [JsrExpressionParser.java](https://jira.spring.io/secure/attachment/23343/JsrExpressionParser.java) (_4.74 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/410

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
