### ISSUE TITLE
JSR-352 JsrJobContext does not provide any getter method for Job Parameters [BATCH-2487]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1116]
**[Arindam Ray](https://jira.spring.io/secure/ViewProfile.jspa?name=arindam.ray)** opened **[BATCH-2487](https://jira.spring.io/browse/BATCH-2487?redirect=false)** and commented

org.springframework.batch.core.jsr.JsrJobContext does not provide any getter method for Job Parameters. If we need current job parameters we have to go through job operator's getParameters method:

Properties properties = BatchRuntime.getJobOperator().getParameters(executionId);

---

**Affects:** 3.0.4

**Comment by hpoettker** [comment]
I think this issue can be closed. `JsrJobContext` has been removed in the course of https://github.com/spring-projects/spring-batch/issues/3894.

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
