### ISSUE TITLE
MapJobExplorerFactoryBean does not work with Java Config [BATCH-2483]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1120]
**[Tomoyuki Ikeya](https://jira.spring.io/secure/ViewProfile.jspa?name=ikeyat)** opened **[BATCH-2483](https://jira.spring.io/browse/BATCH-2483?redirect=false)** and commented

With XML config I was able to force in-memory `JobRepository` for prototyping by definition of `MapJobExplorerFactoryBean` as seen here.
http://docs.spring.io/spring-batch/trunk/reference/html/configureJob.html#inMemoryRepository

But with Java Config, it did not work and got `ClassCastException`. The reason may be that  `SimpleBatchConfiguration` creates bean that name is "jobRepository" and two same named but different typed bean conflicted. The first problem is this incompatibility between XML config and Java config.
https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.java#L66

Second problem is that there is no smart way to force  in-memory `JobRepository` with `DataSource` bean.
According to the code of `DefaultBatchConfigurer`, it constantly avoid to use in-memory `JobRepository` when there is `DataSource` bean. The extension of `DefaultBatchConfigurer` may solve it but it looks much less smart than that in XML config.
https://github.com/spring-projects/spring-batch/blob/dcc9da8273f2fe25fbc9aaa001b101f296f4ddcd/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/annotation/DefaultBatchConfigurer.java#L82

---

**Affects:** 3.0.6

**Comment by benas** [comment]
`MapJobExplorerFactoryBean` has been deprecated for removal, so I don't see an added value in putting effort on this.
