### ISSUE TITLE
DelimitedLineAggregator support string quote characters [BATCH-2463]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1139]
**[Doug Breaux](https://jira.spring.io/secure/ViewProfile.jspa?name=breaux)** opened **[BATCH-2463](https://jira.spring.io/browse/BATCH-2463?redirect=false)** and commented

I can't imagine why org.springframework.batch.item.file.transform.DelimitedLineAggregator doesn't already support a quote character like the delimited tokenizer does. I can see that the StringUtils class being used doesn't provide this capability either, so I'm guessing it just wasn't trivially easy to add, but it seems like a necessary capability for working with delimited files.

I know I need it and am going to have to implement it some other way instead. (As far as I can tell, I can't simply extend an existing Batch class to add a quote delimiter around an individual field value as needed.)

---

2 votes, 9 watchers

**Comment by desprez** [comment]
If it help i wrote this class based on BeanWrapperFieldExtractor

`	public class CSVQuotingBeanWrapperFieldExtractor<T> implements FieldExtractor<T>, InitializingBean {

		private String[] names;

		/**
		 * @param names field names to be extracted by the {@link #extract(Object)}
		 *              method.
		 */
		public void setNames(final String[] names) {
			Assert.notNull(names, "Names must be non-null");
			this.names = Arrays.asList(names).toArray(new String[names.length]);
		}

		/**
		 * @see org.springframework.batch.item.file.transform.FieldExtractor#extract(java.lang.Object)
		 */
		@Override
		public Object[] extract(final T item) {
			final List<Object> values = new ArrayList<>();

			final BeanWrapper bw = new BeanWrapperImpl(item);
			for (final String propertyName : this.names) {
				if (bw.getPropertyType(propertyName).isAssignableFrom(String.class)) {
					values.add(doublequoteIfString(bw.getPropertyValue(propertyName)));
				} else {
					values.add(bw.getPropertyValue(propertyName));
				}
			}
			return values.toArray();
		}

		@Override
		public void afterPropertiesSet() {
			Assert.notNull(names, "The 'names' property must be set.");
		}

		private String quote(final String str) {
			return str != null ? "\"" + str + "\"" : null;
		}

		private Object doublequoteIfString(final Object obj) {
			return obj instanceof String ? quote((String) obj) : obj;
		}
	}`
