### ISSUE TITLE
StaxEventItemReader with Jaxb2Marshaller doesn't work if schema is set [BATCH-2453]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1149]
**[Alain giller](https://jira.spring.io/secure/ViewProfile.jspa?name=gillera)** opened **[BATCH-2453](https://jira.spring.io/browse/BATCH-2453?redirect=false)** and commented

When the property schema is defined in jaxb, Spring batch throws an SAXParseException. Without the schema property, it works fine except it doesn't do any validation...
Here the spring batch config, the problem is the same with java config.

```xml
<bean id="personneItemReader" class="org.springframework.batch.item.xml.StaxEventItemReader">
    <property name="resource" value="classpath:personnes.xml" />
    <property name="fragmentRootElementName" value="personne" />
    <property name="unmarshaller" ref="jaxb2Marshaller" />
</bean>

<bean id="jaxb2Marshaller" class="org.springframework.oxm.jaxb.Jaxb2Marshaller">
    <property name="classesToBeBound">
        <list>
            <value>com.docapost.batch.xml.Personnes</value>
        </list>
    </property>
    <property name="schema" value="classpath:personnes.xsd" />
</bean>
```

---

**Affects:** 3.0.5

**Attachments:**
- [stacktrace.log](https://jira.spring.io/secure/attachment/23214/stacktrace.log) (_14.48 kB_)

**Comment by benas** [comment]
I agree with Michael, this is more like a marshaller config issue than a Spring Batch issue.

> Affects: 3.0.5
> the problem is the same with java config.

Spring Batch v3 is not maintained anymore. Using the latest version as of today (v4.2.1), I was not able to reproduce the issue, see [this repo](https://github.com/benas/spring-batch-sandbox/tree/master/gh1149). Even when the [schema is set](https://github.com/benas/spring-batch-sandbox/blob/master/gh1149/src/main/java/com/example/demo/MyJobConfig.java#L27), data is still unmarshalled as expected. I used the same xml and xsd files shown in the SO thread shared in the [previous comment](https://github.com/spring-projects/spring-batch/issues/1149#issuecomment-566274056).

I'm closing this issue as outdated. If you still face the problem, please provide a minimal complete example that reproduces it.
