### ISSUE TITLE
Skip limit and retry limit for jsr implementation should default to unlimited as per the jsr spec [BATCH-2443]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1159]
**[mark kouba](https://jira.spring.io/secure/ViewProfile.jspa?name=markrk505)** opened **[BATCH-2443](https://jira.spring.io/browse/BATCH-2443?redirect=false)** and commented

As per the jsr 352 spec (page 21 section 8.2.1) the skip limit attribute and the retry limit attribute should default to unlimited.  It does not describe when it should be defaulted but I think it would be safe to assume when the attribute does not exist.

The current class org.springframework.batch.core.jsr.configuration.xml.StepFactoryBean calls for validation that does not allow for a blank or negative value.

I have made a change that defaults the value to -1 when in the org.springframework.batch.core.jsr.configuration.xml.ChunkParser class and then made some updates to the step factory classes to allow for validations that should occur for the jsr only and exclude the other validations for jsr only.

I'm looking for confirmation that the interpretation of the spec is correct and if so I'll do a pull request against 3.0.x with the code I have already completed.

---

**Affects:** 4.0.0, 3.0.5

**Reference URL:** https://jcp.org/aboutJava/communityprocess/mrel/jsr352/index.html

2 votes, 1 watchers

**Comment by arindamray1982** [comment]
We can add getter for skipLimit in the following class:

https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/step/builder/FaultTolerantStepBuilder.java

public int getSkipLimit() {
		return skipLimit;
	}

And make the changes in following file:

https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/jsr/step/builder/JsrFaultTolerantStepBuilder.java

as follows:

the line following line in createChunkProcessor() method:
SkipPolicy skipPolicy = getFatalExceptionAwareProxy(createSkipPolicy());

Can be replaced by:

		SkipPolicy skipPolicy = null;
		if(getSkipLimit() == 0) {
			skipPolicy = getFatalExceptionAwareProxy(new NeverSkipItemSkipPolicy());
		} else if(getSkipLimit() < 0) {
			skipPolicy = getFatalExceptionAwareProxy(new AlwaysSkipItemSkipPolicy());
		} else {
			skipPolicy = getFatalExceptionAwareProxy(createSkipPolicy());
		}

**Comment by arindamray1982** [comment]
A quick fix could be as follows:

In org.springframework.batch.core.jsr.configuration.xml.ChunkParser class, we parse child elements for chunk using method private void parseChildElement(Element element, ParserContext parserContext, MutablePropertyValues propertyValues, Node nd, String stepName).

In that method we add skippableExceptionClasses when present:

else if(name.equals(SKIPPABLE_EXCEPTION_CLASSES_ELEMENT)) {
				ManagedMap<TypedStringValue, Boolean> exceptionClasses = new ExceptionElementParser().parse(element, parserContext, SKIPPABLE_EXCEPTION_CLASSES_ELEMENT);
				if(exceptionClasses != null) {
					propertyValues.addPropertyValue("skippableExceptionClasses", exceptionClasses);
				}
			}

This can be changed as follows:

else if(name.equals(SKIPPABLE_EXCEPTION_CLASSES_ELEMENT)) {
				ManagedMap<TypedStringValue, Boolean> exceptionClasses = new ExceptionElementParser().parse(element, parserContext, SKIPPABLE_EXCEPTION_CLASSES_ELEMENT);
				if(exceptionClasses != null) {
					propertyValues.addPropertyValue("skippableExceptionClasses", exceptionClasses);
					
					//Add skipLimit with value Integer.MAX_VALUE, if skipLimit is not there 
					if(propertyValues.getPropertyValue("skipLimit") == null) {
						propertyValues.addPropertyValue("skipLimit", Integer.MAX_VALUE);
					}
				}
			}

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
