### ISSUE TITLE
JSR 352 jobs don't support chunk/step listeners when using partitions [BATCH-2441]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1161]
**[Ryan Dunckel](https://jira.spring.io/secure/ViewProfile.jspa?name=sparty02)** opened **[BATCH-2441](https://jira.spring.io/browse/BATCH-2441?redirect=false)** and commented

Specifically, when leveraging a partition collector, if there are chunk/step listeners configured, the job fails to even initialize.  When using a partition collector without any chunk/step listeners, the collector looks like its initialized properly.  I did a bit of debugging and it looks like its failing due to a null check in the PartitionCollectorAdapter's constructor, checking for a Queue implementation.  For some reason, the flow instantiating this class run's slightly differently when using listeners.

See the referenced github branch to reproduce the issue.

---

**Affects:** 3.0.5

**Reference URL:** https://github.com/sparty02/spring-batch-named/tree/parition-with-listener-error

1 votes, 3 watchers

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
