### ISSUE TITLE
Improve TransactionAwareBufferedWriter efficiency [BATCH-2434]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1166]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[BATCH-2434](https://jira.spring.io/browse/BATCH-2434?redirect=false)** and commented

TransactionAwareBufferedWriter offers a number of optimization potentials. First it buffers at the char level. Buffering at the byte level instead saves about 50% memory usage in common cases. Second it does not overwrite any of the  #write(String) methods leading to unnecessary intermediate copies.

Together these two changes should help to reduce both live set size and allocation rate.

---

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/387

**Comment by benas** [comment]
Resolved with #387 .
