### ISSUE TITLE
JobFlowExecutor [BATCH-2432]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1170]
**[Adam George](https://jira.spring.io/secure/ViewProfile.jspa?name=awgtek)** opened **[BATCH-2432](https://jira.spring.io/browse/BATCH-2432?redirect=false)** and commented

The method org.springframework.batch.core.job.flow.JobFlowExecutor.updateJobExecutionStatus(FlowExecutionStatus) overwrites the exitDescription of the existing ExitStatus assigned to the JobExecution.
I am setting the JobExecution ExitStatus with a description in an ItemWriter. The description gets overwritten and thus the meta data I added to the JobExecution is lost and consequently I have no results from the JobExecution other than the status and side effects of batch processing.
I would recommend appending the existing job description via call to org.springframework.batch.core.ExitStatus.addExitDescription(String) along with setting the status.

---

**Affects:** 3.0.5

**Comment by fmbenhassine** [comment]
> I am setting the JobExecution ExitStatus with a description in an ItemWriter.

Based on the last comment by Michael, I am closing this issue.
