### ISSUE TITLE
JSR-352 @Inject not working with @Named Components [BATCH-2428]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1175]
**[Ryan Dunckel](https://jira.spring.io/secure/ViewProfile.jspa?name=sparty02)** opened **[BATCH-2428](https://jira.spring.io/browse/BATCH-2428?redirect=false)** and commented

As demonstrated in the repo in the reference URL, it appears that JSR 352 contextual `@Injects` aren't working when using `@Named` component classes.  In general, it almost seems as if the "JSR 352 DI context" (i.e. injecting `@BatchProperty` parameters, JobContext, etc) isn't available when Spring is managing the DI for the batch artifacts (i.e. ItemWriter).  In this example, I'm using `@Named` on the reader/writer, and using the named ref in the JSL.  The job is running through the chunk fine, but Spring isn't injecting the `@BatchProperty` into the writer.  Curiously, if I give a FQCN in the writer ref, the `@BatchProperty` is injected just fine (which is why I mentioned that the issue seems to be when Spring is handling DI for the artifact.

---

**Affects:** 3.0.4

**Reference URL:** https://github.com/sparty02/spring-batch-named

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
