### ISSUE TITLE
5.1 Chunk-Oriented Processing does not represent the actual implementation [BATCH-2423]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1179]
**[Iwasa Kazmi](https://jira.spring.io/secure/ViewProfile.jspa?name=iwasakazmi)** opened **[BATCH-2423](https://jira.spring.io/browse/BATCH-2423?redirect=false)** and commented

In reference documentation, diagram and code of concept in the section "5.1 Chunk-Oriented Processing" http://docs.spring.io/spring-batch/trunk/reference/html/configureStep.html#chunkOrientedProcessing
seems to be different from the actual implementation of the ChunkOrientedTasklet.

According to the description, ItemProcessor will be called immediately after the ItemReader was called once.

In actual implementation of ChunkOrientedTasklet, ItemReader will be called repeatedly for collecting item, then ItemProcessor will be called repeatedly for each collected items.

Current description may lead to the wrong step design and may lead to the performance issue.

---

**Affects:** 4.0.1, 4.1.0.RC1

**Reference URL:** https://stackoverflow.com/questions/26655281/spring-batch-documentation-about-chunk-oriented-step-versus-reality

**Issue Links:**
- [BATCH-2534](https://jira.spring.io/browse/BATCH-2534) Commit interval
 (_**"is duplicated by"**_)

1 votes, 3 watchers

**Comment by benas** [comment]
This is a duplicate of #1629.
