### ISSUE TITLE
Regexp pattern matching composite line mapper [BATCH-2421]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1182]
**[Mauro Scomparin](https://jira.spring.io/secure/ViewProfile.jspa?name=scompo)** opened **[BATCH-2421](https://jira.spring.io/browse/BATCH-2421?redirect=false)** and commented

I'd like to implement a regexp pattern matching composite line mapper to be used to read different record types in flat files.

---
No further details from [BATCH-2421](https://jira.spring.io/browse/BATCH-2421?redirect=false)

**Comment by benas** [comment]
> I'd like to use java String's matches(String pattern) method instead of the PatternMatcher implementation of the PatternMatchingCompositeLineMapper class to add more complex patterns when dealing with multiple records.

The goal is not to provide a `LineMapper` implementation with every possible pattern matching method. For custom/advanced mapping strategies, you can use a custom mapper for that.
