### ISSUE TITLE
NoSuchBeanDefinitionException with "modular = true" + generics + @Stepscope [BATCH-2413]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1190]
**[Roar Bjurstrøm](https://jira.spring.io/secure/ViewProfile.jspa?name=roarbjur)** opened **[BATCH-2413](https://jira.spring.io/browse/BATCH-2413?redirect=false)** and commented

While trying to upgrade from spring batch 2 -> 3 in my current project, i've encountered a strange problem. It seems like use of the following combination:
- `@EnableBatchProcessing`(modular = true)
- Have a step that uses generics
- And have a reader that is annotated with `@Stepscope` (but i am guessing the problem is not reader specific)
  ...will cause a NoSuchBeanDefinitionException.

I have recreated the problem in a test, see: https://gist.github.com/anonymous/0a8eec133affb0fddbc2

It seems like there are 3 ways to work around this issue:
1. Change `@EnableBatchProcessing`(modular = true) to `@EnableBatchProcessing`(modular = false) (line 51)

2. Remove generics. In this case i would have to change:

```
        @Bean
        public Step step(StaxEventItemReader<HibernateEntity> reader) {
            //Irrelevant method information
        }

        @Bean
        @StepScope
        public StaxEventItemReader<HibernateEntity> reader() throws JAXBException {
            //Irrelevant method information
        }
    
```

to

```
         @Bean
        public Step step(StaxEventItemReader reader) {
              //Irrelevant method information
        }

        @Bean
        @StepScope
        public StaxEventItemReader reader() throws JAXBException {
             //Irrelevant method information
        }
```

3. Remove the `@StepScope` annotation (line 163).

Since i am upgrading a large project, neither of these solutions are practical. Am I missing something here?

I have tried with version 3.0.4 and 3.1.0-SNAPSHOT (as of 05.08.2015).

---

**Affects:** 4.0.0, 3.0.4

**Attachments:**
- [stacktrace_batch_2413.txt](https://jira.spring.io/secure/attachment/22970/stacktrace_batch_2413.txt) (_17.95 kB_)
- [StepScopModularTest.java](https://jira.spring.io/secure/attachment/22969/StepScopModularTest.java) (_7.81 kB_)

3 votes, 5 watchers

**Comment by benas** [comment]
> While trying to upgrade from spring batch 2 -> 3 in my current project,
> I have tried with version 3.0.4 and 3.1.0-SNAPSHOT (as of 05.08.2015).

Spring Batch v2 and v3 are not maintained anymore. The same test provided in the [previous comment](https://github.com/spring-projects/spring-batch/issues/1190#issuecomment-566274553) passes with Spring Batch 4.2.1 (after adding a writer which is now mandatory, see #979, but the reported exception does not happen anymore)

I'm closing this issue as outdated.
