### ISSUE TITLE
OracleLobHandler is deprecated [BATCH-2409]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1194]
**[Philippe Marschall](https://jira.spring.io/secure/ViewProfile.jspa?name=marschall)** opened **[BATCH-2409](https://jira.spring.io/browse/BATCH-2409?redirect=false)** and commented

Spring has deprecated OracleLobHandler in favor of DefaultLobHandler for the Oracle 10g driver and higher and recommends using that driver even against 9i databases. Extended Support for Oracle 9.2 ended in [July 2010](http://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf).

To quote from [OracleLobHandler](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/support/lob/OracleLobHandler.html)

> Deprecated in favor of `DefaultLobHandler` for the Oracle 10g driver and higher. Consider using the 10g/11g driver even against an Oracle 9i database!

---

**Affects:** 3.0.4

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/380

**Comment by benas** [comment]
`OracleLobHandler` has been replaced by `DefaultLobHandler` in f4c05307301970cd04086f3d1aa59953ea53fea5.
