### ISSUE TITLE
Parallelize independent ItemWriters [BATCH-2379]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1225]
**[Matthew Ouyang](https://jira.spring.io/secure/ViewProfile.jspa?name=mouyang)** opened **[BATCH-2379](https://jira.spring.io/browse/BATCH-2379?redirect=false)** and commented

As a developer,
I would like to run a set of independent ItemWriters in parallel
so that a step may finish more quickly.

If I want to have multiple ItemWriters, the only current option is to wrap them in a CompositeItemWriter.  However, if the ItemWriters do not depend on each other then running them serially is not necessary.

I would like to take ownership of this, if approved.  Based on [this](http://incomplete-code.blogspot.ca/2013/04/spring-batch-parallel-item-writer.html), I did some preliminary work [here](https://github.com/mouyang/spring-batch/tree/parallel-item-writer).  However, it is lacking in some areas.

1. It is not fault-tolerant (i.e. no repeat/retry).  It would be nice to control this for each ItemWriter, but I think a good start would be to borrow things from the write method in FaultTolerantChunkProcessor and apply the settings from the chunk to all ItemWriters.
2. There is no way to get feedback at the ItemWriter level.  So, if one writer succeeds and another fails (example - two different databases), then there is no way to express this in the current domain model.
   * This raises the question of how to do this.  I don't what would be the best way of doing it (maybe a new entity, putting in execution context probably isn't a good idea).

---
No further details from [BATCH-2379](https://jira.spring.io/browse/BATCH-2379?redirect=false)

**Comment by fmbenhassine** [comment]
There is no plan to introduce this in Spring Batch. The main reason is the incompatibility of the feature with the current design of fault-tolerance and chunk scanning (how to deal with rollback, how to know which writer failed and at which item, etc).

The parallelization of writers can be implemented in a custom writer if the user can manage those aspects manually.
