### ISSUE TITLE
JSR-352 partitioning restarts incorrect partitions [BATCH-2364]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1239]
**[Michael Minella](https://jira.spring.io/secure/ViewProfile.jspa?name=mminella)** opened **[BATCH-2364](https://jira.spring.io/browse/BATCH-2364?redirect=false)** and commented

Partition properties are not being injected correctly to allow for the correct partition to be restarted.

---

**Affects:** 3.0.3

**Reference URL:** http://stackoverflow.com/questions/29098121/spring-batch-jsr-352-restarts-the-wrong-partitions

**Attachments:**
- [BatchJsrPartitioningTest.zip](https://jira.spring.io/secure/attachment/22701/BatchJsrPartitioningTest.zip) (_140.17 kB_)
- [JsrPartitionHandler.java](https://jira.spring.io/secure/attachment/23350/JsrPartitionHandler.java) (_15.82 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/408

**Comment by fmbenhassine** [comment]
The implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).

If anyone is still having this issue with v4.3.8+, then please provide a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md)  that we can run to reproduce the problem and we will re-open this issue for further investigation. Thank you upfront!
