### ISSUE TITLE
Job times out everytime after chunk failure [BATCH-2362]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1240]
**[Andrew Lane Carr](https://jira.spring.io/secure/ViewProfile.jspa?name=aliasdhacker)** opened **[BATCH-2362](https://jira.spring.io/browse/BATCH-2362?redirect=false)** and commented

After chunk failure and response sent to master, job fails.  Fix the problem and restart the job.  Job should work but fails, job times out everytime.

---

**Affects:** 3.0.3

**Comment by benas** [comment]
Closing this as no enough details are provided to reproduce the issue.
