### ISSUE TITLE
Restart job, count never marked successful [BATCH-2361]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1241]
**[Andrew Lane Carr](https://jira.spring.io/secure/ViewProfile.jspa?name=aliasdhacker)** opened **[BATCH-2361](https://jira.spring.io/browse/BATCH-2361?redirect=false)** and commented

After chunk failure, response sent to master.  Restart job, count not updated, chunk never marked successful.  Ends up with mismatch in count.

---

**Affects:** 3.0.3

**Comment by benas** [comment]
Closing this as no enough details are provided to reproduce the issue.
