### ISSUE TITLE
ShouldDeleteIfEmpty not working correctly when exception occurs after writing first chunk [BATCH-2349]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1252]
**[Jimmy Praet](https://jira.spring.io/secure/ViewProfile.jspa?name=jpraet)** opened **[BATCH-2349](https://jira.spring.io/browse/BATCH-2349?redirect=false)** and commented

Both `FlatFileItemWriter` and `StaxEventItemWriter` have a property `shouldDeleteIfEmpty`:

> Flag to indicate that the target file should be deleted if no items have
> been written (other than header and footer) on close. Defaults to false.

To determine if the file should be deleted, the `close()` method checks if the value of `state.linesWritter` or `currentRecordCount` == 0.

But it is possible that records have been written to the output file, and then an exception occurs afterwards causing the chunk to rollback (in my use case for example there is a `CompositeItemWriter` in use, and the second writer threw an exception). In that case the output file is currently not deleted.

If your writer is configured with `shouldDeleteIfExists` == false or `overwriteOutput` == false then the job will fail on resume.

> org.springframework.batch.item.ItemStreamException: File already exists: [D:\projects\MBBatch\MBBatchCoreTests\target\output\output.txt]
> at org.springframework.batch.item.util.FileUtils.setUpOutputFile(FileUtils.java:61) ~[spring-batch-infrastructure-2.2.7.RELEASE.jar:na]

I think this can be fixed by looking at the last persisted (updated) `record.count` execution context variable to determine whether or not to delete the output.

---

**Affects:** 2.2.7, 3.0.3

**Comment by cppwfs** [comment]
Thank you for opening the issue.   Closing the issue as the question has been answered.   If you feel that this issue has been closed in error please leave a comment.  Thank you.
