### ISSUE TITLE
Incorrect write and filter counts reported by asynchronous writer [BATCH-2325]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1279]
**[Sudharma Karekar](https://jira.spring.io/secure/ViewProfile.jspa?name=kaiser101)** opened **[BATCH-2325](https://jira.spring.io/browse/BATCH-2325?redirect=false)** and commented

This is linked to an earlier issue [BATCH-2297](https://jira.spring.io/browse/BATCH-2297). If the processor filters out objects then the list passed to the asynchronous writer contains Futures whose get method would return null. This item is also reported incorrectly in the write count. I assume this is because the writer which is registered with the step contribution is the asynchronous writer and not the delegate which does the actual writing.

---
No further details from [BATCH-2325](https://jira.spring.io/browse/BATCH-2325?redirect=false)

**Comment by benas** [comment]
> Incorrect write and filter counts

This limitation has been documented as part of the resolution of #1233 (See 2e8e7f67be1cc1b350228e5e861d0e8b5da93549).

Here is an excerpt from the javadoc of [AsyncItemProcessor](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/integration/async/AsyncItemProcessor.html):

```
Because the Future is typically unwrapped in the ItemWriter, there are lifecycle and stats limitations (since the framework doesn't know what the result of the processor is).
While not an exhaustive list, things like StepExecution.filterCount will not reflect the number of filtered items
```
