### ISSUE TITLE
Job restart after stop fails [BATCH-2315]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1287]
**[Chris Haas](https://jira.spring.io/secure/ViewProfile.jspa?name=chrishaas)** opened **[BATCH-2315](https://jira.spring.io/browse/BATCH-2315?redirect=false)** and commented

In our jobs we use the following construct to conditionally stop a job based on a property passed into the job:

```xml
<decision id="decisionId" decider="decider">
    <stop on="NEEDS_FINALIZATION" restart="placeAccounts"/>
    <next on="*" to="placeAccounts"/>
</decision>
```

In Spring Batch 2.1, "placeAccounts" is executed when the job is restarted.  In Spring Batch 3, the decision is re-executed, which of course means the job immediately stops again.

In 3.0.1, the job's flow has stateTransitions for the decision look like

```
StateTransition: [state=placementImport.placementFinalizationDecision, pattern=*, next=placementImport.placeAccounts],
StateTransition: [state=placementImport.placementFinalizationDecision, pattern=NEEDS_FINALIZATION, next=placementImport.stop60],
StateTransition: [state=placementImport.stop60, pattern=*, next=null],
```

but in 2.1, they look like:

```
StateTransition: [state=placementImport.placementFinalizationDecision, pattern=*, next=placementImport.placeAccounts],
StateTransition: [state=placementImport.placementFinalizationDecision, pattern=NEEDS_FINALIZATION, next=placementImport.stop60],
StateTransition: [state=placementImport.stop60, pattern=*, next=placementImport.placeAccounts],
```

Notice that the next element on stop60 is blank, which is probably the cause of the problem.

---

**Affects:** 3.0.1

2 votes, 3 watchers

**Comment by benas** [comment]
Minimal complete example to reproduce the issue here: https://github.com/benas/spring-batch-lab/tree/main/issues/gh1287
