### ISSUE TITLE
Overriding transaction management [BATCH-2294]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1289]
**[Abhay](https://jira.spring.io/secure/ViewProfile.jspa?name=abhayp)** opened **[BATCH-2294](https://jira.spring.io/browse/BATCH-2294?redirect=false)** and commented

SimpleBatchConfiguration which gets loaded by any of spring application, created transactionManager bean irrespective of whether that bean is already created or not. This results in overriding transaction manager

`@ConditionalOnMissingBean` could be used for resolution of this issues

---

**Affects:** 3.0.1

**Reference URL:** http://stackoverflow.com/q/25303163/3073323

**Issue Links:**
- [BATCH-2642](https://jira.spring.io/browse/BATCH-2642) Document how to make Spring Batch work with Spring Data JPA repositories
 (_**"is depended on by"**_)

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/609, and commits https://github.com/spring-projects/spring-batch/commit/a68d70043ae6c390a6a877cd435ccafec6cd9d62

**Backported to:** [4.1.0.M3](https://github.com/spring-projects/spring-batch/milestone/95?closed=1)

3 votes, 5 watchers

**Comment by borramTAS** [comment]
The solution proposed with Spring Boot 2.1.4 and Atomikos does not work:

```
@Configuration()
@EnableBatchProcessing
public class BatchConfigurerAutoConfiguration {

  @Bean
   public BatchConfigurer batchConfigurer() {
 	  return new DefaultBatchConfigurer() {
 		  @Override
 		  public PlatformTransactionManager getTransactionManager() {
 			  return new MyTransactionManager();
 		  }
 	  };
   }
}
```

`The bean 'transactionManager', defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/transaction/jta/AtomikosJtaConfiguration.class] and overriding is disabled.
`
