### ISSUE TITLE
Remove Spring Core/Etc Dependencies from Spring Batch Infrastructure [BATCH-2306]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1297]
**[Ryan Dunckel](https://jira.spring.io/secure/ViewProfile.jspa?name=sparty02)** opened **[BATCH-2306](https://jira.spring.io/browse/BATCH-2306?redirect=false)** and commented

There is a lot of useful functionality in Spring Batch Infrastructure that could be leveraged in other JSR 352 implementations.  It would be great if either the dependencies of Spring Batch Infrastructure could be restructured as to remove any other Spring Core/etc deps OR if the reusable components (readers, writers, etc) could be split out into their own module.

---
No further details from [BATCH-2306](https://jira.spring.io/browse/BATCH-2306?redirect=false)

**Comment by mminella** [comment]
Closing as will not fix.
