### ISSUE TITLE
@Qualifier-Annotation not working in combination with AutomaticJobRegistrar [BATCH-2303]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1300]
**[Dennis Schulte](https://jira.spring.io/secure/ViewProfile.jspa?name=denschu)** opened **[BATCH-2303](https://jira.spring.io/browse/BATCH-2303?redirect=false)** and commented

It seems there is a bug when I want to use the `@Qualifier-Annotation` in combination with the AutomaticJobRegistrar. Autowiring without Qualifiers is fully working. The problem is that Spring doesn't find the referenced bean "subExampleService" that is annotated with `@Qualifier` inside the "exampleService"-Bean.

XML-Snippet:

```xml
<bean id="exampleService" class="de.codecentric.batch.item.ExampleService"/>
<bean id="subExampleService" class="de.codecentric.batch.item.SubExampleService"/>
```

Java-Snippet:

```java
public class ExampleService {

    @Autowired
    @Qualifier("subExampleService")
    SubExampleService subExampleService;
    
    public String echo(String echo){
    	return subExampleService.echo(echo);
    }

}
```

I've added an example project with a test case "ApplicationTests" which produces the exception: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'subExampleService' is defined

---

**Affects:** 3.0.1

**Reference URL:** https://github.com/codecentric/spring-samples/tree/master/batch-simple

**Comment by benas** [comment]
@denschu Thank you for sharing a minimal example that reproduces the problem! However, this is not a Spring Batch issue. Without any code modification, the same test passes by upgrading Spring Framework from 4.0.6 to 4.0.8 here: https://github.com/codecentric/spring-samples/blob/master/batch-simple/pom.xml#L11

Looking at the [change log of Spring Framework v4.0.8](https://github.com/spring-projects/spring-framework/releases/tag/v4.0.8.RELEASE), I see in the "Bug Fixes" section that this was indeed resolved in https://github.com/spring-projects/spring-framework/issues/16805.
