### ISSUE TITLE
Add support to read/write from/to Couchbase [BATCH-2275]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1330]
**[Hasnain Javed](https://jira.spring.io/secure/ViewProfile.jspa?name=hkhan45)** opened **[BATCH-2275](https://jira.spring.io/browse/BATCH-2275?redirect=false)** and commented

---

**Affects:** 4.0.0

**Referenced from:** pull request https://github.com/spring-projects/spring-batch-extensions/pull/5

**Comment by benas** [comment]
Closing this in favor of https://github.com/spring-projects/spring-batch-extensions/pull/5.

**Comment by deepmalasrivastav** [comment]
Hi , Is couchbase Reader is available in spring batch?
