### ISSUE TITLE
Unable to use Job Scope beans in a multi-threaded or partitioned step [BATCH-2269]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1335]
**[David Geary](https://jira.spring.io/secure/ViewProfile.jspa?name=david_geary)** opened **[BATCH-2269](https://jira.spring.io/browse/BATCH-2269?redirect=false)** and commented

Attempting to access a JobScope bean from a worker thread in a thread pool as part of a multi-threaded or partitioned step gives the following exception

```
Caused by: java.lang.IllegalStateException: No context holder available for job scope
        at org.springframework.batch.core.scope.JobScope.getContext(JobScope.java:153)
        at org.springframework.batch.core.scope.JobScope.get(JobScope.java:92)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:338)
```

This is due to the fact the JobExecution is stored in a ThreadLocal and it isn't set up on the worker threads.

---

**Affects:** 3.0.1

**Reference URL:** http://stackoverflow.com/questions/24558703/multi-threaded-acces-to-job-scope-beans-in-spring-batch-3-0

18 votes, 21 watchers

**Comment by davidvella** [comment]
> **[Carlos Silva](https://jira.spring.io/secure/ViewProfile.jspa?name=alchimystic)** commented
> 
> We also had this problem, so we define a tweaked TaskExecutor that registers each thread in the JobSynchronizationManager, and in finally it releases it:
> 
> ```
>     TaskExecutor taskExecutor() {
>         return new SimpleAsyncTaskExecutor() {
>             @Override
>             protected void doExecute(Runnable task) {
>                 //gets the jobExecution of the configuration thread
>                 def jobExecution = JobSynchronizationManager.context.jobExecution
>                 super.doExecute(new Runnable() {
>                     @Override
>                     void run() {
>                         JobSynchronizationManager.register(jobExecution)
> 
>                         try {
>                             task.run()
>                         } finally {
>                             JobSynchronizationManager.release()
>                         }
>                     }
>                 })
>             }
>         }
>     }
> ```
> 
> Then we use that executor:
> 
> ```
> new FlowBuilder<SimpleFlow>('readControlFilesFlow')
>                .start(firstStep)
>                .split(taskExecutor())
>                .add(anotherStep)
>                .end()
> ```

Still an issue. Was able to resolve with a similar fix:

```Java
    @Bean
    public TaskExecutor taskExecutor(){
        return new SimpleAsyncTaskExecutor(){
            @Override
            protected void doExecute(Runnable task) {
                //gets the jobExecution of the configuration thread
                JobExecution jobExecution = JobSynchronizationManager.getContext().getJobExecution();
                super.doExecute(() -> {
                    JobSynchronizationManager.register(jobExecution);

                    try {
                        task.run();
                    } finally {
                        JobSynchronizationManager.release();
                    }
                });
            }
        };
    }

    @Bean
    public Step batchStep() {
        return stepBuilderFactory.get("processAccounts")
                .<?, ?> chunk(1)
                .reader(reader())
                .processor(processor())
                .writer(writer())
                .taskExecutor(taskExecutor())
                .build();
    }
```

**Comment by f3l1xss** [comment]
is this planned to be fixed?

**Comment by f3l1xss** [comment]
Hi @davidvella, I have tried the above solution you mentioned but still it throws the same exception. Could you post your job configuration in more details? Is your batch step your slave step?  I have a step A which will perform paritition of Step B, whenever I annotate step B with Step or Job scope it is throwing this exception. I needed the scope variable so that I could assign Step B unique names for each partition, Otherwise Spring Batch will treat all Step B executions as the same and thus upon step failure, it will incorrectly obtain the last step execution

**Comment by davidvella** [comment]
Hi @f3l1xss,

I don't think you apply a Scope to the whole 'step' rather the individual reader / processor and writer. The rest is same as above
```
    /**
     * Bean for processor
     */
    @Bean
    public Processor processor() {
        return new Processor();
    }

    /**
     * Bean for reader
     */
    @JobScope
    @Bean
    public Reader reader(){
        return new Reader();
    }

    /**
     * Bean for writer
     */
    @Bean
    public Writer writer(){
        return new Writer();
    }
```

So in this scenario I have a job scope for each reader. In the reader i paginate through a collection and start at index 1. And each job instance starts at the beginning.

So from my understanding you would want to set a @StepScope to your reader?

**Comment by f3l1xss** [comment]
Hi @davidvella, Thanks for your reply.

I think my requirement is different from yours, I needed the execution context at Step Bean so that I am able to obtain Partition String and apply it to my step name to provide uniqueness:

https://stackoverflow.com/questions/63354744/how-to-dynamically-assign-step-name-at-spring-batch-partitioned-step

Having said that, I have an existing Reader, Writer, Tasklet annotated with StepScope and/or Job Scope and it works just fine without having to add any workaround shown in this page.
I am using Spring Boot 2.3.2

Its only when I add Step/Job scope at the step bean, I will get the 'no context available' exception

Do you happen to also have Partitioned Step which have another slave step? how do you maintain the step name uniqueness?

**Comment by f3l1xss** [comment]
Hi @benas 
I am not sure why the bug label has been removed, as far as I understand this is still ongoing concern

**Comment by benas** [comment]
Spring Batch does not control the worker threads spawned from the thread pool, so we don't have the ability to set them up for use cases like that. We will update the documentation accordingly to mention this limitation.

**Comment by f3l1xss** [comment]
Hi @benas 

Looking at the source code, it is the partition handler who is responsible for executing each worker task.

Can't we create one implementation which will check also if the contained step is a flow and then have a way to 'recreate' that flow with the correct naming?

Right now there is no way to obtain existing flow instance from flowStep.

Alternatively, we could modify flowstep itself to store state whether or not it is currently being executed in partitioned environment, and then based on that property configure the step handler to create stepExecution with the correct naming.

What do you think? 

Haven't looked at the step restart logic, so I am not sure if recreating the stepExecution with another name will have unintended impact.

I think this is pretty common use case and would probably be quite inconvenient for most users to only be able to execute one step in partitioned environment

**Comment by benas** [comment]
@f3l1xss That's really a different problem. The issue here is how to get access to a job scoped bean in a multi-threaded or partitioned step. I don't see how "recreating" the flow is related to that.

I added a comment on your SO question, let's continue the discussion there.
