### ISSUE TITLE
Allow use of JSR-352 chunking pattern from spring batch xml namespace. [BATCH-2261]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1342]
**[David Geary](https://jira.spring.io/secure/ViewProfile.jspa?name=david_geary)** opened **[BATCH-2261](https://jira.spring.io/browse/BATCH-2261?redirect=false)** and commented

Our use case is similar to a Driving Query Based Item Reader as described in section 11.4 of the Spring Batch documentation, ie we only read ids in the reader and retrieve additional information from the the database directly in the processor. This has two implications:

1) The time spent in the reader is small compared to the time spent in the processor.
2) The time spent in the processor can vary greatly (depending on the amount of child information for the item id that is retrieved from the database)

We need to execute the step multi-threaded, but due to the processor time variation in order to get the best performance and share the items efficiently between threads we want to use a timeout policy on determining the chunk size. However due to the default spring batch chunking pattern (read loop then processor loop) timeouts are only applied to the reader which does not help us as some threads will just load up a lot of ids in the reader and starve other threads of items to process. We need the timeout to be applied to the processor, ie we need to use the JSR-352 chunk pattern (read and process in a loop until the chunk is complete then write).

Using the new JSR-352 code in Spring Batch 3 we can do this by instead of configuring

```xml
<step id="myStep">
	<tasklet>
		<chunk reader="myReader" processor="myProcessor" writer="myWriter" chunk-completion-policy="chunkCompletionPolicy"/>
	</tasklet>
</step>
```

we use

```xml
<step id="myStep">
 	<tasklet>
		<beans:bean class="org.springframework.batch.core.step.item.ChunkOrientedTasklet">
			<beans:constructor-arg ref="jsrChunkProvider"/>
			<beans:constructor-arg>
		  		<beans:bean class="org.springframework.batch.core.jsr.step.item.JsrChunkProcessor">
					<beans:constructor-arg ref="myReader"/>
					<beans:constructor-arg ref="myProcessor"/>
					<beans:constructor-arg ref="myWriter"/>
					<beans:constructor-arg ref="repeatTemplate"/>
		  		</beans:bean>
			</beans:constructor-arg>
	   	</beans:bean>
	</tasklet>
	<!-- These need to be explicitily added as listeners if they implement StepExectutionListener -->
	<listeners>
           	<listener ref="myReader"/>
           	<listener ref="myProcessor"/>
     </listeners>		
</step>

<beans:bean id="jsrChunkProvider" class="org.springframework.batch.core.jsr.step.item.JsrChunkProvider"/>
	
<beans:bean id="repeatTemplate" class="org.springframework.batch.repeat.support.RepeatTemplate">
	<beans:property name="completionPolicy" ref="chunkCompletionPolicy"/>		
</beans:bean> 
```

and this does give us increased performance when we use a composite chunk completion policy (simple and timeout). However obviously we are losing some of the convenience of the spring batch name space. It would be nice if we could just write something like

```xml
<step id="myStep">
	<tasklet>
		<chunk reader="myReader" processor="myProcessor" writer="myWriter" chunk-completion-policy="chunkCompletionPolicy" chunking-pattern="jsr-352"/>
	</tasklet>
</step>
```

NOTE: The chunking documentation (section 5.1) is still incorrect in Spring Batch 3.0 documentation and a source of confusion since it has never been implemented like that (although it is the way the new JSR-352 code does it). It would be better if the two patterns were clearly documented and this enhancement would then allow you to easily choose which you want.

---

**Affects:** 3.0.0

**Comment by fmbenhassine** [comment]
Closing this feature request as the implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).
