### ISSUE TITLE
Add ability to launch JSR-352 based jobs from command line [BATCH-2249]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1351]
**[Michael Minella](https://jira.spring.io/secure/ViewProfile.jspa?name=mminella)** opened **[BATCH-2249](https://jira.spring.io/browse/BATCH-2249?redirect=false)** and commented

As of the 3.0.0.RELEASE version, JSR-352 based jobs require the writing of a main class to launch them.  We should update the `CommandLineJobRunner` to handle the JSR-352 use case.

---
No further details from [BATCH-2249](https://jira.spring.io/browse/BATCH-2249?redirect=false)

**Comment by hpoettker** [comment]
I think this issue can be closed. The JSR-352 implementation has been removed in the course of #3894.

**Comment by fmbenhassine** [comment]
Closing this feature request as the implementation of the JSR-352 was [discontinued in v5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#jsr-352-implementation-removal).
