### ISSUE TITLE
Groovy configuration for Spring Batch [BATCH-2244]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1356]
**[Michael Minella](https://jira.spring.io/secure/ViewProfile.jspa?name=mminella)** opened **[BATCH-2244](https://jira.spring.io/browse/BATCH-2244?redirect=false)** and commented

---
No further details from [BATCH-2244](https://jira.spring.io/browse/BATCH-2244?redirect=false)

**Comment by mminella** [comment]
Closing as won't implement.
