### ISSUE TITLE
Provide a way to specify the class loader to be used by a ClassPathXmlApplicationContextFactory [BATCH-2182]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1417]
**[Mauro Molinari](https://jira.spring.io/secure/ViewProfile.jspa?name=mauromol)** opened **[BATCH-2182](https://jira.spring.io/browse/BATCH-2182?redirect=false)** and commented

A `ClassPathXmlApplicationContextFactory` creates `ClassPathXmlApplicationContext` instances. The latter, by extending `DefaultResourceLoader` would allow to specify the class loader to use to locate resources. It would be very useful if the factory and the corresponding `ClasspathXmlApplicationContextsFactoryBean` (which, IMHO, should better be called `ClassPathXmlApplicationContextFactoryFactoryBean`, since it's a `FactoryBean` that creates factories and also would need an upper case "P" in "ClassPath") allowed to specify the class loader to use. This would allow to create an `AutomaticJobRegistrar` which registers jobs defined in child contexts loaded through a suitable class loader (which may in turn load classes at runtime from hot-deployed JARs, for instance).

Being able to specify just one class loader on the FactoryBean for all created factories would be better than nothing.

Right now I have to write my own FactoryBean and factory to achieve this, but I think that supporting this out-of-the-box should be quite simple and valuable.

By the way, I see that with 3.0.0.M2 `ClassPathXmlApplicationContextFactory` has been deprecated in favour of `GenericApplicationContextFactory`, which creates generic `ConfigurableApplicationContexts`. This enhancement might give a reason to revert the deprecation on `ClassPathXmlApplicationContextFactory` and add some additional value to it...

---

**Affects:** 2.1.9

**Comment by benas** [comment]
`ClassPathXmlApplicationContextFactory` has been deprecated since v3 and will be removed in v5 (see #3836), so I see no value in putting efforts on it for the rest of its short life.
