### ISSUE TITLE
SqlWindowingPagingQueryProvider does not generate correct SQL when the Select Clause contains a Join [BATCH-2168]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1429]
**[Philippe BAYE](https://jira.spring.io/secure/ViewProfile.jspa?name=pbaye)** opened **[BATCH-2168](https://jira.spring.io/browse/BATCH-2168?redirect=false)** and commented

Because the over clause is built suppressing the alias table name prefix (if exists) of the sortKey property, the request SQL can contain an "ambiguous identifier"

Example with these properties :
- selectClause = a.ID, a.JJ
- fromClause = TABLE_A a, TABLE_B b
- whereClause = a.REF_CODE_A=b.REF_CODE_B AND b.CODE=:code
- sortKey = a.ID

The the first page request SQL built looks like this :
SELECT *
FROM
(SELECT a.ID,
a.JJ,
ROW_NUMBER() OVER (ORDER BY ID ASC) AS ROW_NUMBER
FROM TABLE_A a,
TABLE_B b
WHERE a.REF_CODE_A         =b.REF_CODE_B
AND b.CODE                 =:code
)
WHERE ROW_NUMBER <= 500

So, if TABLE_A and TABLE_B contain both a column named "ID", the "ID" referenced in the "ORDER BY ID ASC" clause is ambiguous.

It works well in 2.0.4 version.
Looking in the source code, the 2.2.3 version seems not to have this issue.

---

**Affects:** 2.1.9

**Comment by cppwfs** [comment]
Based on previous comments, this issue will be closed.   If you feel this issue was closed in error please leave a comment.   Thank you!
