### ISSUE TITLE
JobParametersValidator.validate(JobParameters) method is invoked twice when a Job is started. [BATCH-2143]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1452]
**[Ying Hou](https://jira.spring.io/secure/ViewProfile.jspa?name=danielhou)** opened **[BATCH-2143](https://jira.spring.io/browse/BATCH-2143?redirect=false)** and commented

SimpleJobLauncher.run(Job, JobParameters) method is used to start a Job, processes of this method can be shown:
1) Validate parameters. job.getJobParametersValidator().validate(jobParameters);
2) Create JobExecution. jobExecution = jobRepository.createJobExecution(job.getName(), jobParameters);
3) Execute JobExecution. job.execute(jobExecution);
   The first process is used to validate job parameters, a Job is started at the third process. The question is that jobParametersValidator.validate(execution.getJobParameters()) is invoked in the AbstractJob.execute(JobExecution) method. So JobParametersValidator.validate(JobParameters) method is invoked twice when a Job is started.

---

**Affects:** 2.2.2

1 votes, 2 watchers

**Comment by benas** [comment]
I believe this is not an issue. There should be a good reason for this double check but my thinking is the following:

* Jobs that extend `AbstractJob` and which are not launched via the `SimpleJobLauncher` (simple call to `execute`) should still validate parameters before starting
* Jobs that do not extend `AbstractJob` may forget to validate parameters in the `execute` method. When those jobs are launched via `SimpleJobLauncher`, parameters are still validated upfront in the launcher

Both cases are covered today with this double check. Double checking the validity of parameters should not harm (and does not harm in this case). If you still think this is an issue, please provide a use case where this can be problematic and we can re-open this ticket for discussion.
