### ISSUE TITLE
Allow the switching of different implementation class for Spring Batch JavaConfig [BATCH-2137]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1458]
**[Simon Wong](https://jira.spring.io/secure/ViewProfile.jspa?name=simonwg)** opened **[BATCH-2137](https://jira.spring.io/browse/BATCH-2137?redirect=false)** and commented

In current JavaConfig of Spring Batch, it is difficult for me to switch another implementation.

e.g. If I have to switch another implementation of JobLoader in ModularBatchConfiguration, I have to modify
AbstractBatchConfiguration, BatchConfigurationSelector, EnableBatchProcessing and ModularBatchConfiguration

It is better for me to choose the implementation class in EnableBatchProcessing annotation.

e.g. `@EnableBatchProcessing`(modular = true, jobLoader = MyCustomJobLoader.class)

---

**Affects:** 2.2.2

**Comment by fmbenhassine** [comment]
No feedback, I am closing this issue.
