### ISSUE TITLE
Infinite recursion (StackOverflowError) when serializing JobExecution to JSON [BATCH-2109]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1488]
**[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert)** opened **[BATCH-2109](https://jira.spring.io/browse/BATCH-2109?redirect=false)** and commented

Steps to reproduce:

```
		JobExecution jobExecution = new JobExecution(1L);
		StepExecution stepExecution = new StepExecution("s1", jobExecution);

		List<StepExecution> stepExecutions = new ArrayList<StepExecution>();
		stepExecutions.add(stepExecution);

		jobExecution.addStepExecutions(stepExecutions);
		ObjectMapper mapper = new ObjectMapper();
		String result = mapper.writeValueAsString(jobExecution); //<--infinite recursion
```

---

**Affects:** 2.2.2

**Issue Links:**
- [XD-999](https://jira.spring.io/browse/XD-999) Return the step execution information in the current job execution controller

**Comment by ajain72** [comment]
7 years later I have hit the same issue while trying to use Remote Chunking. Need to convert the Chunked Payload to Json String to send it across the messaging queue to the worker process and ran in to this issue. I see some workarounds using MixIns but haven't tried them yet but will be soon.

**Comment by ajain72** [comment]
//This seems to work fine.
       //reference - https://stackoverflow.com/questions/58288040/spring-batch-serialization-problem-when-using-jackson

      public abstract class JobExecutionMixin {
		@JsonManagedReference
		private Collection<StepExecution> stepExecutions;
	}

	public abstract class StepExecutionMixin {
		@JsonBackReference
		private final JobExecution jobExecution = null;
	}

	@Bean // Serialize message content to json using TextMessage
	public MessageConverter messageConverter() {
		ObjectMapper mapper = new ObjectMapper();
		mapper.addMixIn(org.springframework.batch.core.StepExecution.class, StepExecutionMixin.class);
		mapper.addMixIn(org.springframework.batch.core.JobExecution.class, JobExecutionMixin.class);
		mapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false);
		mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

		MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
		converter.setObjectMapper(mapper);

		converter.setTargetType(MessageType.TEXT);
		converter.setTypeIdPropertyName("_type");
		return converter;
	}

**Comment by benas** [comment]
I agree with Michael here: https://github.com/spring-projects/spring-batch/issues/1488#issuecomment-566278703, this is a Jackson issue and not a Spring Batch issue. Other libraries are able to handle object graphs with bi-directional relations **by default**, and Jackson 2 is not one of them (it requires some configuration to support this).

We cannot remove all bi-directional relations from the core domain model or add default constructors to all entities just to make Jackson work by default. The presence of such relations and the absence of default constructors in some entities are for a good reason which is making the domain model consistent and enforcing data integrity constraints. Jackson users should teach Jackson how to deal with such objects, like shown above with mixins or other mechanisms that Jackson provides.
