### ISSUE TITLE
Allow customisation of FlatFileItemWriter [BATCH-2070]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1524]
**[Cliff Evans](https://jira.spring.io/secure/ViewProfile.jspa?name=mipper)** opened **[BATCH-2070](https://jira.spring.io/browse/BATCH-2070?redirect=false)** and commented

It should be possible to customise the writing of data for the FlatFileItemWriter in a similar way to the FlatFileItemReader to allow insertion of a custom stream.  The particular use case I have for this is to allow data to be written directly to a compressed file.  I realise there will be issues with resuming failed operations, but whether recovery or re-run should be used on failure should be a decision for the user.

---

**Affects:** 2.2.1

**Comment by benas** [comment]
This is a duplicate of #1777.
