### ISSUE TITLE
Support for TimesTen database

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1565]
**[Nayan Hajratwala](https://jira.spring.io/secure/ViewProfile.jspa?name=nhajratw)** opened **[BATCH-2029](https://jira.spring.io/browse/BATCH-2029?redirect=false)** and commented

TimesTen is an in-memory database from Oracle. I've created a pull request that provides support for it.

---

**Affects:** 2.2.0.RC2

**Reference URL:** https://github.com/SpringSource/spring-batch/pull/172

**Comment by fmbenhassine** [comment]
There is no plan to support TimesTen in Spring Batch. This can be contributed to the community-driven extension repository:  https://github.com/spring-projects/spring-batch-extensions
