### ISSUE TITLE
Add XML namespace equivalent to @EnableBatchProcessing [BATCH-2021]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1571]
**[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert)** opened **[BATCH-2021](https://jira.spring.io/browse/BATCH-2021?redirect=false)** and commented

While Spring Batch supports `@EnableBatchProcessing` for JavaConfig (see: [BATCH-1918](https://jira.spring.io/browse/BATCH-1918)), there is no equivalent XML namespace support, e.g.:

\<enable-batch-processing/>

---

**Affects:** 2.2.0.RC1

**Issue Links:**
- [BATCH-1918](https://jira.spring.io/browse/BATCH-1918) `@Configuration` support for batch (e.g. `@EnableBatchProcessing`)
 (_**"depends on"**_)

1 votes, 1 watchers

**Comment by fmbenhassine** [comment]
With the decline of the XML configuration style, there is no plan to work on this anytime soon.
