### ISSUE TITLE
Making tasklet as non transactional not working [BATCH-2020]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1572]
**[Praveen Billakanti](https://jira.spring.io/secure/ViewProfile.jspa?name=bpraveen02)** opened **[BATCH-2020](https://jira.spring.io/browse/BATCH-2020?redirect=false)** and commented

Our spring batch job(writer) calls an EJB which has `@TransactionAttribute`(TransactionAttributeType.NEVER).

Due to this we are getting exception "IllegalArgumentException – Transaction present on server in  NEVER call."

For some reason a transaction is started and that is propagated till the EJB.

We have tried the below ways but none of them worked.

1.Added transaction attributes(NEVER and NOT_SUPPORTED)  to batch step and tasklet. <batch:transaction-attributes isolation="DEFAULT" propagation="NEVER"/>

Getting the below exception when using NOT_SUPPORTED.

"Already value [org.springframework.orm.hibernate3.SessionHolder@2317a576] for key [org.hibernate.impl.SessionFactoryImpl@3a991adc] bound to thread [SimpleAsyncTaskExecutor-1]"

2.Created a new step that extends TaskletStep and in the execute method, called super.setTransactionAttrubute(new DefaultTransactionAttribute(4/5));, super.execute(); Added this new step as parentStep to the tasklet.

3. 

<batch:chunk processor-transactional="false" retry-limit="1"
reader="reader"
processor="processor"
writer="writer"
commit-interval="100">
<batch:retryable-exception-classes><batch:exclude class="java.lang.Exception"/></batch:retryable-exception-classes>
</batch:chunk>

Please suggest us if there is any other way of solving this issue.

---

**Affects:** 2.1.2

**Comment by benas** [comment]
I agree with Dave [here](https://github.com/spring-projects/spring-batch/issues/1572#issuecomment-566279747). This issue is probably outdated since it was opened against v2.1.2 which is not maintained anymore. I'm not able to reproduce the problem with Spring Batch v4.2.1. Here is a quick example:

```java
import javax.sql.DataSource;

import com.mysql.cj.jdbc.MysqlDataSource;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.interceptor.DefaultTransactionAttribute;

@Configuration
@EnableBatchProcessing
public class GH1572 {

	@Bean
	public Job job(JobBuilderFactory jobs, StepBuilderFactory steps) {
		DefaultTransactionAttribute transactionAttribute = new DefaultTransactionAttribute();
		transactionAttribute.setPropagationBehavior(TransactionDefinition.PROPAGATION_NOT_SUPPORTED);
//		transactionAttribute.setPropagationBehavior(TransactionDefinition.PROPAGATION_NEVER);

		return jobs.get("gh1572-job")
				.start(steps.get("gh1572-step")
						.tasklet((contribution, chunkContext) -> {
							System.out.println("hello world");
							return RepeatStatus.FINISHED;
						})
						.transactionAttribute(transactionAttribute)
						.build())
				.build();
	}

	@Bean
	public DataSource dataSource() {
		return new EmbeddedDatabaseBuilder()
				.setType(EmbeddedDatabaseType.H2)
				.addScript("/org/springframework/batch/core/schema-drop-h2.sql")
				.addScript("/org/springframework/batch/core/schema-h2.sql")
				.build();
	}

//	@Bean
//	public DataSource dataSource() {
//		MysqlDataSource datasource = new MysqlDataSource();
//		datasource.setURL("jdbc:mysql://localhost:3306/test");
//		datasource.setUser("root");
//		datasource.setPassword("");
//		return datasource;
//	}

	public static void main(String[] args) throws Exception {
		ApplicationContext context = new AnnotationConfigApplicationContext(GH1572.class);
		JobLauncher jobLauncher = context.getBean(JobLauncher.class);
		Job job = context.getBean(Job.class);
		jobLauncher.run(job, new JobParameters());
	}

}
```

Both propagation levels (`NEVER` and `NOT_SUPPORTED`) work as expected and tested with H2 and MySQL.

I'm closing this issue for now. But feel free to re-open it if you still have the problem (in which case, please provide minimal complete example to reproduce it).
