### ISSUE TITLE
In JOB_PARAMS table DATE_VAL column is updated incorrectly Like "1/1/1970 1:00:00.000000 AM" instead to the current date. [BATCH-2015]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1577]
**[Sonali Singhal](https://jira.spring.io/secure/ViewProfile.jspa?name=sonalisinghal)** opened **[BATCH-2015](https://jira.spring.io/browse/BATCH-2015?redirect=false)** and commented

---

**Affects:** 2.1.8

0 votes, 5 watchers

**Comment by benas** [comment]
I agree with Michael, `null` is a better default value than the suggested current date or the start or epoch date (as implemented currently). I just checked all DDLs and they all declare the `DATE_VAL` column to be nullable by default. So changing `new Timestamp(0L)` with `null` in [`JdbcJobExecutionDao#insertParameter`](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcJobExecutionDao.java#L346-L354) should be safe.

**Comment by parikshitdutta** [comment]
Hi @benas, Please have a look at my submitted PR #3869, I will look forward to your feedback.

Thank you.
