### ISSUE TITLE
Integration with Spring Security [BATCH-1983]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1611]
**[Adriano Machado](https://jira.spring.io/secure/ViewProfile.jspa?name=amachado)** opened **[BATCH-1983](https://jira.spring.io/browse/BATCH-1983?redirect=false)** and commented

Is there a way to integrate Spring Security with Spring Batch?

In my case, I'd like to inherit the SecurityContext of the user which started the job to the steps.

---

**Affects:** 2.1.9

1 votes, 4 watchers

**Comment by benas** [comment]
I agree with Michael [here](https://github.com/spring-projects/spring-batch/issues/1611#issuecomment-566280183) and I don't even see what could be done in Spring Batch to support this.

In regards to the use case of the previous comment,  A security context can be populated/cleared using a job listener and shared with the item processor through the job execution context.
