### ISSUE TITLE
StepScopePerformanceTests fails when building with 1.7 even if the compile level is set to 1.6 in the POM [BATCH-1976]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1619]
**[Michael Minella](https://jira.spring.io/secure/ViewProfile.jspa?name=mminella)** opened **[BATCH-1976](https://jira.spring.io/browse/BATCH-1976?redirect=false)** and commented

When building with JDK 1.7 (on a Mac using Oracle's distribution), StepScopePerformanceTests#testProxied fails with an IllegalStateException: No context holder available for step scope.

---

**Affects:** 2.2.0

**Comment by benas** [comment]
Spring Batch v3 (Java 7 baseline) is not maintained anymore.

For Spring Batch v4 (Java 8 baseline), the test `StepScopePerformanceTests` passes with both Oracle JDK and Open JDK.

I'm closing this issue as outdated.
