### ISSUE TITLE
chunk-oriented-processing and completion-policy inconsistent with documentation [BATCH-1967]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1629]
**[Jimmy Praet](https://jira.spring.io/secure/ViewProfile.jspa?name=jpraet)** opened **[BATCH-1967](https://jira.spring.io/browse/BATCH-1967?redirect=false)** and commented

https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#chunkOrientedProcessing
https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#stoppingAJobManuallyForBusinessReasons

According to the documentation chunk-oriented-processing has a (read+process) loop until the completion-policy is reached, and then the chunk is handed to the ItemWriter. In actuality it is a read-loop until the completion-policy is reached (ChunkProvider), and then the chunk is handed to the ChunkProcessor that has a process-loop after which the chunk is handed to the ItemWriter.

This means it is not possible to use a completion-policy to for example commit your chunk after 100 records are processed, or 1 minute has passed (whichever comes first).

---

**Reference URL:** http://forum.springsource.org/showthread.php?116507-chunk-completion-policy

2 votes, 2 watchers

**Comment by tomasz-belina-nes** [comment]
What are the plans related to this issue ?

**Comment by benas** [comment]
I just planned this issue to be included in the next release.

**Comment by tomasz-belina-nes** [comment]
> 
> 
> I just planned this issue to be included in the next release.

Documentation will be updated or behavior will be changed ?

**Comment by benas** [comment]
This is a documentation issue, so we will update the docs to correctly reflect the current implementation. There is no plan to change the behavior.
