### ISSUE TITLE
Updating generate-sql for auto-generated *.sql files [BATCH-1963]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1632]
**[Wayne Lund](https://jira.spring.io/secure/ViewProfile.jspa?name=wxlund)** opened **[BATCH-1963](https://jira.spring.io/browse/BATCH-1963?redirect=false)** and commented

After creating sqlfire*.sql files for core and samples and modifying postgresql I realized that these are meant to be auto-generated.  I've added the creates and mods into the src/main/sql/\<relevant-files> and am creating the distinct way postgres has to drop constraints when cleaning out the database.

---

**Affects:** 3.0.2

**Comment by benas** [comment]
Closing this issue since the auto-generation of sql scripts has been removed (see f19f32fd79a340b798ab84f21216b4668f79e15a). Moreover, the issue is related to sqlfire support which has been deprecated in #815 .
