### ISSUE TITLE
Batch PAUSE/RESUME flow option [BATCH-1962]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1633]
**[Will Schipp](https://jira.spring.io/secure/ViewProfile.jspa?name=willschipp)** opened **[BATCH-1962](https://jira.spring.io/browse/BATCH-1962?redirect=false)** and commented

Allow a job to be preconfigured (xml) to PAUSE at a given position in an execution and RESUMED later.

This can be achieved by modifying the FlowExecutor to have a function of pauseJob() and a FlowState of PAUSED.  Once the state is triggered, the BatchStatus and ExitStatus are set to PAUSED/PAUSING and persisted.  To RESUME the job, a the PausedJobManager.resumeJob(Long jobExecutionId) is called which resumes the same job execution in the task executor, skipping already completed steps and starting at the next in the flow.

Key changes to support this are in the new JobManager that would allow for the resetting of the JobExecution state (from PAUSED to STARTING).

NamespaceHandler changes would need to support a "step-level" <batch:pause id="someJob.pause"/> element that is referenced by a "next-step".

---

**Affects:** 2.2.0 Backlog

1 votes, 3 watchers

**Comment by benas** [comment]
Closing this issue as the requested feature was removed in #2626 (see 5d62e4d4364c0eec031bc173024cff3567ad1c8b).
