### ISSUE TITLE
SimpleRetryPolicy javadoc is missing some important informations [BATCH-1941]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1651]
**[Sebastien Lorber](https://jira.spring.io/secure/ViewProfile.jspa?name=sebastienlorber)** opened **[BATCH-1941](https://jira.spring.io/browse/BATCH-1941?redirect=false)** and commented

My usecase was pretty simple:

I wanted a RetryPolicy that would retry all Exception class and subclasses, except a custom exception NoRetryException - which is a RuntimeException - which would make the RetryTemplate abord the retries.

After reading the Javadoc and code of some retry classes of the Retry/Batch framework, I found out that I had to create my custom RetryPolicy.

Finally after loosing some time I noticed something: the use of a TreeSet and of org.springframework.classify.SubclassClassifier.ClassComparator

This means that my usecase was handled by SimpleRetryPolicy, but the Javadoc doesn't mention it. Perhaps for some people it seems to be the obvious behavior, but it was not for me.

The Javadoc doesn't mention this on class level javadoc of BinaryExceptionClassifier and SubclassClassifier too.

"If the object to be classified is one of the keys of the provided
map, or is a subclass of one of the keys, then the map entry value for that
key is returned."

The only Javadoc reference to this feature is:
"Return the value from the type map whose key is the class of the given Throwable, or its nearest ancestor if a subclass."

I think this should be better explained on the SimpleRetryPolicy

---

**Affects:** 2.1.9

**Comment by benas** [comment]
`SimpleRetryPolicy` is not part of Spring Batch anymore, we can't change its Javadoc here. It is now part of [spring-retry](https://github.com/spring-projects/spring-retry) project.

> The Javadoc doesn't mention this on class level javadoc of BinaryExceptionClassifier and SubclassClassifier too.

The class level Javadocs of both [BinaryExceptionClassifier](https://www.javadoc.io/static/org.springframework.retry/spring-retry/1.2.5.RELEASE/org/springframework/classify/BinaryExceptionClassifier.html) and [SubclassClassifier](https://www.javadoc.io/static/org.springframework.retry/spring-retry/1.2.5.RELEASE/org/springframework/classify/SubclassClassifier.html) mention that:

```
If the object to be classified is one of the provided types, or is a subclass of one of the types, then the non-default value is returned (usually true).
```

> I think this should be better explained on the SimpleRetryPolicy

The Javadoc of [`SimpleRetryPolicy`](https://www.javadoc.io/static/org.springframework.retry/spring-retry/1.2.5.RELEASE/org/springframework/retry/policy/SimpleRetryPolicy.html) mentions that as well:

```
Simple retry policy that retries a fixed number of times for a set of named exceptions (and subclasses)
```

I believe this is outdated so I'm closing this issue for now. If you think this is not clear enough, please open this issue against `spring-retry`.
