### ISSUE TITLE
Add support for named queries on JpaPagingItemReader [BATCH-1926]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1667]
**[David Zeigler](https://jira.spring.io/secure/ViewProfile.jspa?name=dzeigler)** opened **[BATCH-1926](https://jira.spring.io/browse/BATCH-1926?redirect=false)** and commented

The Hibernate ItemReaders support queryName as an alternative to queryString allowing the reader to use a named query.

JpaPagingItemReader needs to support this option as well.  When queryName is set, the javax.persistence.Query should be created using entityManager.createNamedQuery(queryName);

---

**Affects:** 2.1.9

**Comment by parikshitdutta** [comment]
Hi @benas, if you feel like, you can assign this to me.

Thank you.

**Comment by parikshitdutta** [comment]
Hi @benas, as you find time, please review the PR #3726. I will look forward to your feedback.

Thank you.

**Comment by benas** [comment]
Resolved with #3726 .
