### ISSUE TITLE
Modify AssertFile class to work properly with classpath (ex: in jar file) based resources  [BATCH-1910]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1686]
**[Jeff Evans](https://jira.spring.io/secure/ViewProfile.jspa?name=jeff.evans)** opened **[BATCH-1910](https://jira.spring.io/browse/BATCH-1910?redirect=false)** and commented

The AssertFile class does not work when one or more of the resources is in the jar file (and referenced via the classpath URI prefix).  That's because the current implementation uses the .getFile() method on the resource, which can fail if the file is actually in the jar and not on the filesystem.  In cases where we want to include the "expected" result file in the jar, it would be desirable for the reference to the resource to work.

---

**Affects:** 2.1.9

**Comment by hpoettker** [comment]
As `AssertFile` has been deprecated in Spring Batch 5.0 with #4181, I think it would make sense to close the issue.
