### ISSUE TITLE
Support for binary files [BATCH-1855]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1734]
**[Michael Wirth](https://jira.spring.io/secure/ViewProfile.jspa?name=tagedieb)** opened **[BATCH-1855](https://jira.spring.io/browse/BATCH-1855?redirect=false)** and commented

Add support for files with records in binary format and process the lines as byte array without being forced to convert the records into Strings.

---
No further details from [BATCH-1855](https://jira.spring.io/browse/BATCH-1855?redirect=false)

**Comment by benas** [comment]
Closing this as duplicate of #2225.
