### ISSUE TITLE
StepExecutionContext: Truncated short context leads to deserialisation failure  [BATCH-1851]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1738]
**[David Victor](https://jira.spring.io/secure/ViewProfile.jspa?name=dvb123)** opened **[BATCH-1851](https://jira.spring.io/browse/BATCH-1851?redirect=false)** and commented

The `JdbcExecutionContextDao` truncates the StepExecution short context where overall serialized context length execeeds the 2,500 varchar limit in the schema.

```
	private void persistSerializedContext(final Long executionId, String serializedContext, String sql) {

		final String shortContext;
		final String longContext;
		if (serializedContext.length() > shortContextLength) {
			// Overestimate length of ellipsis to be on the safe side with
			// 2-byte chars
			shortContext = serializedContext.substring(0, shortContextLength - 8) + " ...";
			longContext = serializedContext;
```

This means that an invalid JSON structure can be saved in the short context column.

The Javadoc explains that this is done for readability, however the consequence is that when we try to read back this row from the db some time later it can fail in _xstream_ with an exception when it attempts to "unmarshal" the short context.  E.g. `SimpleJobExplorer.getJobExecutions()`

```
	/**
	 * The maximum size that an execution context can have and still be stored
	 * completely in short form in the column <code>SHORT_CONTEXT</code>.
	 * Anything longer than this will overflow into large-object storage, and
	 * the first part only will be retained in the short form for readability.
	 * Default value is 2500. Clients using multi-bytes charsets on the database
	 * server may need to reduce this value to as little as half the value of
	 * the column size.
	 * @param shortContextLength
	 */
	public void setShortContextLength(int shortContextLength) {
		this.shortContextLength = shortContextLength;
	}

```

Will try to add a backtrace when I get one.

---

**Affects:** 2.1.8

**Reference URL:** http://forum.springsource.org/showthread.php?125329-BATCH_STEP_EXECUTION_CONTEXT-SHORT_CONTEXT-truncation-leads-to-invalid-serialisation

**Comment by cmananth27** [comment]
Do we have any solution for this issue ?

**Comment by benas** [comment]
@cmananth27 This was opened against v2 (which is not maintained anymore) and then closed as "Cannot Reproduce" (See [BATCH-1851](https://jira.spring.io/browse/BATCH-1851?redirect=false)) . If you are still having the issue with v4.3 and have a failing test or a minimal complete example that reproduces the problem, then please add a comment here and we will re-open this issue if necessary.
