### ISSUE TITLE
MultiResourceItemReader.getCurrentResource not usable with StepScope [BATCH-1831]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1758]
**[Michael Pralow](https://jira.spring.io/secure/ViewProfile.jspa?name=daywalker2000@gmx.net)** opened **[BATCH-1831](https://jira.spring.io/browse/BATCH-1831?redirect=false)** and commented

actual implemention of MultiResourceItemReader does not permit usage with step scope, to get it working the getCurrentResource needs to be added to an interface (itemstream perhaps?) or a new interface has to be introduced

---

**Affects:** 2.1.8

This issue is a sub-task of [BATCH-1243](https://jira.spring.io/browse/BATCH-1243)

**Comment by benas** [comment]
I'm closing this issue as `MultiResourceItemReader#getCurrentResource()` has been deprecated for removal (see #3776).
