### ISSUE TITLE
Introduce BufferedWriterFactory abstraction [BATCH-1816]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1777]
**[Jimmy Praet](https://jira.spring.io/secure/ViewProfile.jspa?name=jpraet)** opened **[BATCH-1816](https://jira.spring.io/browse/BATCH-1816?redirect=false)** and commented

A BufferedWriterFactory abstraction could be introduced in the FlatFileItemWriter, which for example would make it possible to write directly to a gzipped output stream. This is consistent with the BufferedReaderFactory that already exists for FlatFileItemReader.

---
No further details from [BATCH-1816](https://jira.spring.io/browse/BATCH-1816?redirect=false)

**Comment by parikshitdutta** [comment]
Hi @benas, please assign this to me.

Thank you.

**Comment by parikshitdutta** [comment]
Hi @benas, please take a look at my PR #3724 as you find time. I will look forward to your feedback.

Thank you.

**Comment by benas** [comment]
Closing this issue as explained in #3724 .
