### ISSUE TITLE
AggregateItemReader from Appendix A. List of ItemReaders and ItemWriters does not exist in core/infrastructure, but in samples [BATCH-1796]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1793]
**[Michael Pralow](https://jira.spring.io/secure/ViewProfile.jspa?name=daywalker2000@gmx.net)** opened **[BATCH-1796](https://jira.spring.io/browse/BATCH-1796?redirect=false)** and commented

In Appendix A. List of ItemReaders and ItemWriters from Spring Batch Documentation the reader list mentions an AggregateItemReader.

This AggregateItemReader does not exist in core or infrastructure, but can be found in samples.

---

**Affects:** 2.1.8

**Comment by benas** [comment]
Indeed, the `AggregateItemReader` is not part of the standard library of readers provided by Spring Batch, but I see no harm in keeping it in the appendix for reference. I added a note about that in the appendix, see 6ab141bb44bb86ee7aacd5d604fd37971a7344ee.

I also took the opportunity to fix some incorrect references in its description, and I will update the title of the issue accordingly.
