### ISSUE TITLE
Suggestion: recoveryCallback should be a property in RetryTemplate [BATCH-1792]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1797]
**[Dmitry Katsubo](https://jira.spring.io/secure/ViewProfile.jspa?name=dma_k)** opened **[BATCH-1792](https://jira.spring.io/browse/BATCH-1792?redirect=false)** and commented

AT the moment recoveryCallback is passed to RetryTemplate's interface methods as a parameter. I think the role of recoveryCallback suppose it to be a property. This will:

- Allow to create RetryTemplate with pre-defined recoveryCallback, e.g. currently it is not possible to use this ability via RetryOperationsInterceptor
- Simplify the interface for RetryOperations, leaving 2 methods out of 4.

---

**Affects:** 2.1.8

**Comment by benas** [comment]
Spring Retry has been pulled out of Spring Batch and is now a separate project: https://github.com/spring-projects/spring-retry. This issue should be opened against spring-retry project.
