### ISSUE TITLE
improve generation of pdf documentation [BATCH-1781]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1808]
**[guillaume peron](https://jira.spring.io/secure/ViewProfile.jspa?name=gperon)** opened **[BATCH-1781](https://jira.spring.io/browse/BATCH-1781?redirect=false)** and commented

The pdf documentation can be improved.

-1-  Some tables overlaps or go beyond page boundaries, making tables unreadable.
Found in release 2.1.8 doc, page numbered 81 and 122 - actual pages 86 and 127.

It looks like (not being an expert) docbook has some "keep-together" tag on xsl-fo table object.
A non clean workaround is to break that with an improper parameter:
=> adding in file : src/docbkx/resources/xsl/fopdf.xsl

+ <xsl:attribute-set name="table.properties" use-attribute-sets="formal.object.properties">

+ 

      <xsl:attribute name="keep-together.within-column">"1"</xsl:attribute>

+ </xsl:attribute-set>

-2- The reference guide, with more than 200 pages, would be much easier to read if it included bookmarks to the different chapters.
Than in your pdf reader you can have permanently the tag pane displayed and jump to any paragraph by clicking on the tags in that pane.

To get the tags generated, just switch on the extension param.
The current comment saying it is valid only for pdf is not relevant, as the fop configuration file fopdf.xsl is only used for pdf.
=> in file : src/docbkx/resources/xsl/fopdf.xsl

    

- \

+ <xsl:param name="fop1.extensions">1</xsl:param>

-3- Eventually, not sure if it would be useful to others...
Images were not included when I built the pdf on my local system.
To get the images included I had to change the configuration, and after it worked
(I dont know why, I just changed the place where the resource was declared, nothing more...)

=> in file : pom.xml

             <goal>generate-pdf</goal>
    </goals>
    <configuration>

- 

      <imgSrcPath>src/site/docbook/reference/</imgSrcPath>

- 

      <admonGraphicsPath>src/docbkx/resources/images/</admonGraphicsPath>

+ 

      

=> in file : src/docbkx/resources/xsl/fopdf.xsl

    
     <xsl:param name="admon.graphics">'1'</xsl:param>

- \

+ <xsl:param name="admon.graphics.path">src/docbkx/resources/images/</xsl:param>

+ \+ 

      Images

+ ################################################### -->

+ <xsl:param name="img.src.path">src/site/docbook/reference/</xsl:param>

+ 

---

**Affects:** 2.1.8

**Comment by benas** [comment]
None of the reported issues could be found in the current [PDF](https://docs.spring.io/spring-batch/docs/4.2.x/reference/pdf/spring-batch-reference.pdf). This is outdated (and the tooling has changed from docbook to asciidoc since then).
