### ISSUE TITLE
DelimitedLineTokenizer : Bug with quote character inside an unquoted field [BATCH-1771]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1822]
**[Jérôme Morille](https://jira.spring.io/secure/ViewProfile.jspa?name=jmorille)** opened **[BATCH-1771](https://jira.spring.io/browse/BATCH-1771?redirect=false)** and commented

For a CVS file read by DelimitedLineTokenizer (configured like the DelimitedLineTokenizerTests)
Sophie,"Good, afternoon",London
Martin,good morning,Paris
Henry,Good "Morning,Vietnam

The [Henry line] case, The character ["] is considered like a Quote demarcation instead of a character of the field
That produce an  as 2 fields intead of 3 as expected.

To demonstrated it need to add
```java
@Test
public void testTokenizeRegularUseWithQuoteCharInside() {
   FieldSet tokens = tokenizer.tokenize("sfd,Well I have no idea \"what to do in the afternoon,sFj, asdf,,as\n");
   assertEquals(6, tokens.getFieldCount());
   assertTrue(TOKEN_MATCHES, tokens.readString(0).equals("sfd"));
   assertTrue(TOKEN_MATCHES,tokens.readString(1).equals("Well I have no idea \"what to do in the afternoon"));
   assertTrue(TOKEN_MATCHES, tokens.readString(2).equals("sFj"));
   assertTrue(TOKEN_MATCHES, tokens.readString(3).equals("asdf"));
   assertTrue(TOKEN_MATCHES, tokens.readString(4).equals(""));
   assertTrue(TOKEN_MATCHES, tokens.readString(5).equals("as"));

}
```

---

**Affects:** 2.1.8

**Issue Links:**
- [BATCH-2581](https://jira.spring.io/browse/BATCH-2581) DelimitedLineTokenizer always interprets quotes
 (_**"is duplicated by"**_)

**Comment by cppwfs** [comment]
Thank you for raising this issue.  Closing this issue due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
