### ISSUE TITLE
How to Delete data from Spring Batch Metadata tables that are 90 days old. [BATCH-1747]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1844]
**[Mariam](https://jira.spring.io/secure/ViewProfile.jspa?name=mpat)** opened **[BATCH-1747](https://jira.spring.io/browse/BATCH-1747?redirect=false)** and commented

I want to write stored procedure to delete records that are created in spring batch metadata. Can you please let me know the query to do it. I need to delete data that are 90 days old.  We are using oracle as DB.

---

**Affects:** 2.1.5

**Comment by javaHelper** [comment]
@Elryk - https://github.com/arey/spring-batch...ryTasklet.java - This link is no more active now. Could you please share us the correct link or share code to delete Spring Batch Metadata tables 30 days old.

**Comment by arey** [comment]
Hi @javaHelper, here is the link: https://github.com/arey/spring-batch-toolkit/blob/spring-batch-toolkit-4.0.0/src/main/java/com/javaetmoi/core/batch/tasklet/RemoveSpringBatchHistoryTasklet.java

**Comment by hmojicag** [comment]
Spring batch metadata is actually ephemeral and data that is in COMPLETED or FAILED status seem to not be used anymore by anything, I would recommend deleting it to free up storage space, unless you actually want to keep those 90 days of historic batch processes for audit reasons.

I implemented this script which basically deletes everything that is not in use in the right order to avoid dependency problems:

```sql
DELETE FROM BATCH_STEP_EXECUTION_CONTEXT WHERE STEP_EXECUTION_ID IN (SELECT BATCH_STEP_EXECUTION.STEP_EXECUTION_ID FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS IN ('COMPLETED','FAILED')));
DELETE FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS IN ('COMPLETED','FAILED'));
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS IN ('COMPLETED','FAILED'));
DELETE FROM BATCH_JOB_EXECUTION_PARAMS WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS IN ('COMPLETED','FAILED'));
DELETE FROM BATCH_JOB_EXECUTION WHERE STATUS IN ('COMPLETED','FAILED');
DELETE FROM BATCH_JOB_INSTANCE WHERE JOB_INSTANCE_ID NOT IN (SELECT BATCH_JOB_EXECUTION.JOB_INSTANCE_ID FROM BATCH_JOB_EXECUTION);
```
