### ISSUE TITLE
Demultiplexer support in ItemWriter [BATCH-1736]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1853]
**[Tom Van den heuvel](https://jira.spring.io/secure/ViewProfile.jspa?name=sparkwired)** opened **[BATCH-1736](https://jira.spring.io/browse/BATCH-1736?redirect=false)** and commented

The setup is as follows:

Suppose the last ItemProcessor<I,O> in the chain (in case there's more than one processor in play) produces O typed objects. Suppose these are not intrinsic output objects but rather encapsulations of both intrinsic output and enriching information. Suppose one input record (originating from the reader) results in n output records, encapsulated in a collection property of the O typed object produced by the last processor.

For instance, one book item price reduction that was read in by an ItemReader has to be communicated via mail to n book item price watchers via an EmailItemWriter

The ItemWriter\<O> has to receive O typed objects (matching the output type of the last ItemProcessor), but an ItemWriter implementation will never know how to demultiplex this object to find the prepared email messages stored in the collection. The only solution to this at this moment is to write a custom DemultiplexingItemWriter\<O> that will delegate n times to the EmailItemWriter implementation for each O received.

Perhaps this can be simplified by allowing to set a "Demultiplexer<O, Collection\<M>>" on the ItemWriter interface, that is called in the write method of the ItemWriter? By default (when not set) this would be a no-op demultiplexer, just writing out the object that is received.

---

**Affects:** 2.1.7

2 votes, 4 watchers

**Comment by benas** [comment]
Based on the last comments, I'm closing this issue for now.
