### ISSUE TITLE
ExecutionContext is not properly updated in the Job Repository [BATCH-1699]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1888]
**[Moose99](https://jira.spring.io/secure/ViewProfile.jspa?name=mrahimi99)** opened **[BATCH-1699](https://jira.spring.io/browse/BATCH-1699?redirect=false)** and commented

During the persistance of the execution context in the job repository, I get the following exception:

Caused by: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [UPDATE SBATCH.BATCH_JOB_EXECUTION_CONTEXT SET SHORT_CONTEXT = ?, SERIALIZED_CONTEXT = ? WHERE JOB_EXECUTION_ID = ?]; SQL state [72000]; error code [1461]; ORA-01461: can bind a LONG value only for insert into a LONG column
; nested exception is java.sql.SQLException: ORA-01461: can bind a LONG value only for insert into a LONG column.

It appears that the SHORT_CONTEXT or SERIALIZED_CONTEXT fields are not updated properly.  They are of type varchar and CLOB, but the spring framework is attempting to insert a LONG value into one of these two columns.  Please see attached for the complete stacktrace and job configuration.  T

---

**Affects:** 2.1.0

**Attachments:**
- [defect data.zip](https://jira.spring.io/secure/attachment/17638/defect+data.zip) (_4.95 kB_)

**Comment by benas** [comment]
Based on previous comments, it seems like increasing the length of the SHORT_CONTEXT column fixed the issue. This issue is old and seems outdated, so if anyone is still having the same problem with the latest Spring Batch version, please provide a minimal example and we will re-open it if necessary.
