### ISSUE TITLE
DelimitedLineTokenizer always trims the input data [BATCH-1696]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1890]
**[Arun Yogesh](https://jira.spring.io/secure/ViewProfile.jspa?name=ayogi)** opened **[BATCH-1696](https://jira.spring.io/browse/BATCH-1696?redirect=false)** and commented

The Delimited Line tokenizer seems to trim all the tokens by default, there is no way to get non trimmed raw data without implementing a custom tokenizer.

I guess this bug arose when fixing the JIRA [BATCH-285](https://jira.spring.io/browse/BATCH-285).
The method 'maybeStripQuotes' trims the data blindly and returns it to 'doTokenize'

---

**Affects:** 2.1.5

**Referenced from:** commits https://github.com/spring-projects/spring-batch/commit/57b0cb7498638624ca39c87576504c3bb487381f

**Comment by wims-tijd** [comment]
DelimitedLineTokenizer should trim or have this option to do so ,
it breaks JSR 380 : jakarta.validation.constraints.NotEmpty ,
workaround : 
DelimitedLineTokenizer lineTokenizer = new DelimitedLineTokenizer() {
			
			@Override
			protected List<String> doTokenize(String line) {
				List<String> tokens = super.doTokenize(line);
				List<String> trimmed = new ArrayList<>();
				tokens.forEach(s -> trimmed.add(s.trim()));
				return trimmed;
			}
		};

**Comment by wims-tijd** [comment]
oops : jakarta.validation.constraints.NotBlank did the trick
