### ISSUE TITLE
SimpleStepExecutionSplitter should call methods on Step lazily [BATCH-1692]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1893]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[BATCH-1692](https://jira.spring.io/browse/BATCH-1692?redirect=false)** and commented

SimpleStepExecutionSplitter should call methods on Step lazily, otherwise if it is a remote proxy, it might not be initialized in time.

---

**Affects:** 2.1.6

**Comment by benas** [comment]
This is outdated. In fact, `SimpleStepExecutionSplitter` initially [had](https://github.com/spring-projects/spring-batch/commit/f6487f6b533079ca905d30f316d876e43438a645#diff-1ccc98868257080253b51baded74a755478f3f85f754e0dc8ef05144ecd7dc02R25) a reference to a `Step` on which it called methods (which should be called lazily as described in this issue), but this has been changed in 8e1f054bd29346705ac96ac1fccc9366e189e5b5.
