### ISSUE TITLE
Fix up samples and test with a few different database platforms

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1926]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[BATCH-1658](https://jira.spring.io/browse/BATCH-1658?redirect=false)** and commented

---

**Affects:** 2.1.5

**Comment by fmbenhassine** [comment]
Resolved in a0316379945a813b6516aaa37d110dc425693fed.
