### ISSUE TITLE
Ordering of JobRepository operations in TaskletStep$ChunkTransactionCallback.doInTransaction creates potential for deadlock [BATCH-1626]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1956]
**[Andy Neilson](https://jira.spring.io/secure/ViewProfile.jspa?name=aneilson)** opened **[BATCH-1626](https://jira.spring.io/browse/BATCH-1626?redirect=false)** and commented

The ordering of the operations in JobRepository operations in TaskletStep$ChunkTransactionCallback.doInTransaction creates the potential for deadlock. The particular scenario is that a partitioned job is launched, and the main thread is polling waiting for all the steps to complete by calling jobExplorer.getStepExecution(Long, Long). This will lock database objects in the order { BATCH_STEP_EXECUTION, BATCH_STEP_EXECUTION_CONTEXT }. Immediately before TaskletStep$ChunkTransactionCallback.doInTransaction exits, it issues updates in the order { BATCH_STEP_EXECUTION_CONTEXT, BATCH_STEP_EXECUTION }. Because the ordering is reversed relative to what happens in SimpleJobExplorer.getStepExecution(Long, Long), it creates potential for deadlock.

The proposed solution is to reorder the operations in TaskletStep$ChunkTransactionCallback.doInTransaction to match the ordering in SimpleJobExplorer.getStepExecution(Long, Long).

---

**Affects:** 2.1.2

**Reference URL:** http://forum.springsource.org/showthread.php?p=318317

**Comment by benas** [comment]
The code of `TaskletStep` referenced here has changed significantly since this issue was opened back in 2010. Based on the last comments, I'm closing this for now. If someone is still experiencing the problem with v4+, feel free to re-open the issue with a minimal complete example to reproduce it.

**Comment by ctunc** [comment]
I upgrade the project  to spring 2.0.x to spring 2.2.x and java jdk 8 to jdk 11. When cron job launched or scheduled I get this exception. Is this spring batch bug? Does this exception still persist in version spring 2.2.0.Release?
