### ISSUE TITLE
Add support for Sybase IQ database [BATCH-1611]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1966]
**[Shiva Prasad Sahoo](https://jira.spring.io/secure/ViewProfile.jspa?name=spsahoo)** opened **[BATCH-1611](https://jira.spring.io/browse/BATCH-1611?redirect=false)** and commented

Spring Batch is not supporting for Sybase IQ database. It's working perfectly with Derby H2 databases etc. Please let me know if any work around is there to make it work for Sybase IQ database.

---
No further details from [BATCH-1611](https://jira.spring.io/browse/BATCH-1611?redirect=false)

**Comment by fmbenhassine** [comment]
There is no plan for now to support Sybase IQ in Spring Batch. This can be contributed to the community-driven extension repository:  https://github.com/spring-projects/spring-batch-extensions
