### ISSUE TITLE
Support for NoSQL database persistence [BATCH-1596]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1988]
**[Baruch Sadogursky](https://jira.spring.io/secure/ViewProfile.jspa?name=jbaruch)** opened **[BATCH-1596](https://jira.spring.io/browse/BATCH-1596?redirect=false)** and commented

Forum reference provides MongoDB implementation that passes all SpringBatch tests.

---

**Reference URL:** http://forum.springsource.org/showthread.php?t=88445

**Issue Links:**
- [BATCH-2727](https://jira.spring.io/browse/BATCH-2727) Support Mongo for JobRepository

4 votes, 3 watchers

**Comment by benas** [comment]
"Support for NoSQL database persistence" is too generic. Based on the previous [comment](https://github.com/spring-projects/spring-batch/issues/1988#issue-538731256), it looks like this is referring to MongoDB. I'm closing this in favor of the more specific feature request  #877.
