### ISSUE TITLE
Allow user to switch off chunk monitor warnings [BATCH-1515]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#2067]
**[Stéphane Nicoll](https://jira.spring.io/secure/ViewProfile.jspa?name=snicoll)** opened **[BATCH-1515](https://jira.spring.io/browse/BATCH-1515?redirect=false)** and commented

We have configured one of our reader to use a asyn task executor and we get this in the log

```
[main] core.step.item.FaultTolerantStepFactoryBean [WARN] Asynchronous TaskExecutor detected (class org.springframework.core.task.SimpleAsyncTaskExecutor) with ItemStream reader.  This is probably an error, and may lead to incorrect restart data being stored.
[main] core.step.item.ChunkMonitor [WARN] No ItemReader set (must be concurrent step), so ignoring offset data.
[SimpleAsyncTaskExecutor-1] core.step.item.ChunkMonitor [WARN] ItemStream was opened in a different thread.  Restart data could be compromised.
[SimpleAsyncTaskExecutor-2] core.step.item.ChunkMonitor [WARN] ItemStream was opened in a different thread.  Restart data could be compromised.
[SimpleAsyncTaskExecutor-3] core.step.item.ChunkMonitor [WARN] ItemStream was opened in a different thread.  Restart data could be compromised.
[SimpleAsyncTaskExecutor-4] core.step.item.ChunkMonitor [WARN] ItemStream was opened in a different thread.  Restart data could be compromised.
[SimpleAsyncTaskExecutor-5] core.step.item.ChunkMonitor [WARN] ItemStream was opened in a different thread.  Restart data could be compromised.
```

The problem is that we use item stream only because we need to use `JdbcCursorItemReader` but we configure it in such a way that saveState is **always** false.

I understand the "item stream was opened in a different thread" . I don't understand the other warning "No ItemReader set (must be concurrent step), so ignoring offset data."

I believe that a flag is missing here, something that specifies if the data will be saved or not. In the case it returns false, those warning should not occur. Hopefully, most warnings are coming from the chunkmonitor so we can isolate them but it makes the logging configuration in case of valid usage of the api more complex

---

1 votes, 0 watchers

**Comment by mihaelait** [comment]
Hi,

I encountered same situation of multiple warning messages in log:

2022-08-10 13:54:41.981  WARN 136964 --- [  offset_batch6] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:41.987  WARN 136964 --- [  offset_batch7] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:41.994  WARN 136964 --- [  offset_batch8] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:41.994  WARN 136964 --- [  offset_batch5] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:42.159  WARN 136964 --- [  offset_batch3] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:42.165  WARN 136964 --- [  offset_batch9] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.
2022-08-10 13:54:42.174  WARN 136964 --- [ offset_batch10] o.s.b.c.s.i.ChunkMonitor                 : ItemStream was opened in a different thread.  Restart data could be compromised.

What i discovered is the fact it is related to the job configuration:
        .faultTolerant()
        .skip(SException.class)
        .retry(SException.class)
        .retryLimit(retries)
        .skipLimit(threshold)
If i remove these lines the log won't have the warning anymore.
Any idea of how to keep this fault tolerance configuration and to not see the warning?

Thanks

**Comment by fmbenhassine** [comment]
@mihaelait @beks2016 

The Javadoc of `ChunkMonitor` says the following:

```
Only works with single threaded steps
```

Are you having these warnings even with single threaded steps? If yes, can you please provide a minimal example we can run to reproduce the issue?

**Comment by beks2016** [comment]
Hi @fmbenhassine 
Everythinng worked well untill we add faultTolerant to our step
`
For the reader we have 
public class S3CsvItemReader implements **ItemStreamReader**<Map<String, String>> {
    
    private CSVReaderHeaderAware csvReaderHeaderAware;

    @Override
    public void open(ExecutionContext executionContext) {
        try {

          csvReaderHeaderAware = (CSVReaderHeaderAware) new CSVReaderHeaderAwareBuilder(SOME_S3_INPUT_STREAM)
                    .withCSVParser(SOME_PARSER)
                    .build();
        }catch (AmazonS3Exception amazonS3Exception){
            throw amazonS3Exception;
        }
    }

    @Override
    public void close() {
        try {
            if (csvReaderHeaderAware != null) {
                csvReaderHeaderAware.close();
            }
        } catch (IOException ex) {
            throw new ItemStreamException(ex);
        }
    }

    @Override
    public Map<String, String> read() throws Exception {

        synchronized (csvReaderHeaderAware) {
                return csvReaderHeaderAware.readMap();
        }
    }


    @Override
    public void update(ExecutionContext executionContext) {
        //DO Nothing
    }

}
`

for the step we have 
`stepBuilderFactory.get("s3ImportStep")
                .<Map<String, String>, PmuBaseEntity>chunk(700)
                .reader(new S3CsvItemReader(s3client, bucketName, objectKey))

                .processor(mapper)
                .writer(elasticsearchWriter)

                **.faultTolerant()**
                .skip(Exception.class)
                .skipLimit(100)
                .listener(new Skiplistener())
                .taskExecutor(batchTaskExecutor)
                .throttleLimit(30)

                .build();`

**Comment by beks2016** [comment]
Hi @fmbenhassine ,
Did you have some time to reproduce the issue , we couldn't find the link between adding faulTolerant step and the warning !

regards
