### ISSUE TITLE
StaxEventItemWriter: Handle namespace for the root tag [BATCH-1377]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2204]
**[Arnaud Jeansen](https://jira.spring.io/secure/ViewProfile.jspa?name=ajeans)** opened **[BATCH-1377](https://jira.spring.io/browse/BATCH-1377?redirect=false)** and commented

I need to push the namespace of the root tag for the XML files I generate. As I found a reference to this request in the forum, I guess it would be useful to more than just me.

I could even generate the patch if you want, It should be a simple matter of adding a "rootNamespace" field and making use of it in startDocument()

Here is what I am using now (subclassing with an override on startDocument())

public class CustomStaxEventItemWriter\<T> extends StaxEventItemWriter\<T>
private String rootTagNamespace = "";

    /**
     * 
     * @return
     */
    public String getRootTagNamespace()
    {
        return rootTagNamespace;
    }
    
    /**
     * 
     * @param rootTagNamespace
     */
    public void setRootTagNamespace(String rootTagNamespace)
    {
        this.rootTagNamespace = rootTagNamespace;
    }
    
    /**
     * Replace the standard startDocument with one that lets us put a XML
     * namespace on the root tag.
     */
    @Override
    protected void startDocument(XMLEventWriter writer)
        throws XMLStreamException
    {
    
        XMLEventFactory factory = XMLEventFactory.newInstance();
    
        // write start document
        writer.add(factory.createStartDocument(getEncoding(), getVersion()));
    
        // write root tag
        Iterator<Namespace> nsIt = null;
        if (StringUtils.hasText(getRootTagNamespace()))
        {
            // Create the namespace for the root tag
            Namespace ns = factory.createNamespace("", getRootTagNamespace());
            nsIt = Collections.singletonList(ns).iterator();
        }
        QName rootTag = new QName(getRootTagNamespace(), getRootTagName(), "");
        StartElement startElement =
            factory.createStartElement(rootTag, null, nsIt);
        writer.add(startElement);
    
        // write root tag attributes
        if (!CollectionUtils.isEmpty(getRootElementAttributes()))
        {
            for (Map.Entry<String, String> entry : getRootElementAttributes()
                .entrySet())
            {
                writer.add(factory.createAttribute(entry.getKey(), entry
                    .getValue()));
            }
        }
    
        writer.flush();
    }

}

---

**Affects:** 2.1.0

**Reference URL:** http://forum.springsource.org/archive/index.php/t-69060.html

**Referenced from:** commits https://github.com/spring-projects/spring-batch/commit/f56ee747296961917caa38fa9e14785dafc0b18b, https://github.com/spring-projects/spring-batch/commit/d0f94cb0eec47c8f36d351dc9d0e6db305049c60, https://github.com/spring-projects/spring-batch/commit/9790174503a8be4a4205939d9fab5bbad9f6f710, https://github.com/spring-projects/spring-batch/commit/822f8bb86822c28da43aa4c44f005ca1fbe244fb

3 votes, 2 watchers

**Comment by sgebauer-kgu** [comment]
I've just encountered this issue and it seems that this is still not fixed. Is that correct? I'm not able to set a namespace with StaxEventItemWriter :(

**Comment by benas** [comment]
@sgebauer-kgu You should be able to set a namespace on the root element as shown here: https://stackoverflow.com/a/58181423/5019386. Otherwise, please ask a question on StackOverflow and provide a minimal complete example that reproduces your issue and we will take a look.
