### ISSUE TITLE
Deprecate throttle limit in favour of using similar features in TaskExecutor implementations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2218]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[BATCH-1364](https://jira.spring.io/browse/BATCH-1364?redirect=false)** and commented

---
No further details from [BATCH-1364](https://jira.spring.io/browse/BATCH-1364?redirect=false)

**Comment by hpoettker** [comment]
I'm not sure that it's a good idea to deprecate the throttle limit. As explained in https://github.com/spring-projects/spring-batch/issues/3857#issuecomment-827901009 , the thread pool must be big enough to cover the waiting of `SplitState` nodes if there are nested splits in the job.

As far as I know, the throttle limit is the only effective way to set a maximal number of concurrent steps if a job has nested splits.
