### ISSUE TITLE
ResourceSuffixCreator too limited for multiple files support [BATCH-1352]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#2229]
**[Arnaud Jeansen](https://jira.spring.io/secure/ViewProfile.jspa?name=ajeans)** opened **[BATCH-1352](https://jira.spring.io/browse/BATCH-1352?redirect=false)** and commented

I am using the MultiResourceItemWriter to generate xml files. I would need to push timestamps into the output files, that is:
- Configure the MultiResourceItemWriter with a resource "file:output/export.xml"
- Get several files at the end of the step: "output/export-20090731144500.xml" and "output/export-20090731144524.xml"

Unfortunately, the only configuration possible at the moment (subclassing ResourceSuffixCreator  and injecting it into the multiple writer) cannot provide this feature.

public interface ResourceSuffixCreator {

    String getSuffix(int index);

}

What I would be hoping for would look like this:

public interface ResourceFilenameCreator {

    String getFilepath(String filePath, int index);

}

The change would be quite straightforward for all the writers, the class SimpleResourceSuffixCreator could still be implemented with this, and I would be able to put timestamps in my output files.

For now, I have to duplicate the MultiResourceItemWriter in my code, and change the setResourceToDelegate() method to do what I need.

If there is any interest in this functionality, I could even provide a patch (it is really simple AFAICS)

---

**Affects:** 2.0.2

**Comment by benas** [comment]
I agree with Dave, I see no need to change the current `ResourceSuffixCreator` interface.

> I would need to push timestamps into the output files, that is:
> 
> * Configure the MultiResourceItemWriter with a resource "file:output/export.xml"
> * Get several files at the end of the step: "output/export-20090731144500.xml" and "output/export-20090731144524.xml"

Here is a quick and dirty sample for this requirement:

```java
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.item.ItemReader;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.file.FlatFileItemWriter;
import org.springframework.batch.item.file.builder.FlatFileItemWriterBuilder;
import org.springframework.batch.item.file.builder.MultiResourceItemWriterBuilder;
import org.springframework.batch.item.file.transform.PassThroughLineAggregator;
import org.springframework.batch.item.support.ListItemReader;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.FileSystemResource;

@Configuration
@EnableBatchProcessing
public class MyJob {

	@Bean
	public ItemReader<Integer> itemReader() {
		return new ListItemReader<>(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
	}

	@Bean
	public ItemWriter<Integer> itemWriter() {
		FlatFileItemWriter<Integer> delegate = new FlatFileItemWriterBuilder<Integer>()
				.name("fileWriter")
				.lineAggregator(new PassThroughLineAggregator<>())
				.build();
		return new MultiResourceItemWriterBuilder<Integer>()
				.name("multiFileWriter")
				.delegate(delegate)
				.resource(new FileSystemResource("export"))
				.itemCountLimitPerResource(5)
				.resourceSuffixCreator(index -> "-" + format(LocalDateTime.now()) + ".txt")
				.build();
	}

	private String format(LocalDateTime now) {
		return now.format(DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS"));
	}

	@Bean
	public Job job(JobBuilderFactory jobs, StepBuilderFactory steps) {
		return jobs.get("job")
				.start(steps.get("step")
						.<Integer, Integer>chunk(5)
						.reader(itemReader())
						.writer(itemWriter())
						.build())
				.build();
	}

	public static void main(String[] args) throws Exception {
		ApplicationContext context = new AnnotationConfigApplicationContext(MyJob.class);
		JobLauncher jobLauncher = context.getBean(JobLauncher.class);
		Job job = context.getBean(Job.class);
		jobLauncher.run(job, new JobParameters());
	}

}
```

It generates two files `export-20200114115644961.txt` and `export-20200114115644974.txt` (the index can be added to the suffix if needed).

> I would have to hardcode the extension of the file in the implementation of ResourceSuffixCreator (and configure it there, rather than in the writer configuration).

This is not an issue if we consider the extension as part of the suffix.

> For now I implemented this with a custom multi item writer

There is no need for that as shown in the previous example.

> This would break API completely, so even if you think this change makes sense, it is either a change that would go to 3.0.0, or we would need to preserve behavior by handling a ResourceSuffixCreator (deprecated) and a ResourcePathCreator at the same time.

I agree, it's a breaking change. So I would keep it simple as it is now (and avoid API Bloat, see #3242), there is really no need for two interfaces to generate a suffix.
