### ISSUE TITLE
IllegalArgumentException thrown from FlatFileItemReader where IllegalState would be more appropriate [BATCH-1337]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2244]
**[Iwein Fuld](https://jira.spring.io/secure/ViewProfile.jspa?name=iwein)** opened **[BATCH-1337](https://jira.spring.io/browse/BATCH-1337?redirect=false)** and commented

```
public void afterPropertiesSet() throws Exception {
		Assert.notNull(lineMapper, "LineMapper is required");
	}
```

Should use Assert.state instead imo.

---

**Affects:** 2.0.1

**Comment by danilopiazza** [comment]
Hi, I opened PR #4055 to address this issue.
