### ISSUE TITLE
Support RetryOperations within SimpleJobRepository [BATCH-1329]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2251]
**[Ian Brandt](https://jira.spring.io/secure/ViewProfile.jspa?name=ibrandt)** opened **[BATCH-1329](https://jira.spring.io/browse/BATCH-1329?redirect=false)** and commented

See the referenced forum post for motivation and details.  If SimpleJobRepository had a get/setRetryOperations that was used to wrap all DAO calls it would have a very flexible and durable way to deal with transient failures such as CannotSerializeTransactionException (which is to be anticipated given the default transaction SERIALIZABLE isolation level set by AbstractJobRepositoryFactoryBean).  Of course AbstractJobRepositoryFactoryBean would need equivalent getters and setters, and in the absence of given configuration would set a default.  The default could be a RetryTemplate with the NeverRetryPolicy to preserve current behavior, or one could get fancy and start handling given TransientDataAccessException subclasses with an ExceptionClassifierRetryPolicy.  The latter would require the determination of sensible defaults.  I'm not sure if that would result in endless back and forth by users with different needs, or if a "retry 3 times with 1-2 second pause" would be a generally welcomed default?

Per Dave's post earlier in the referenced forum thread an alternative would be put it on the user to wrap the JobLauncher with RetryOperations.  Given that transient failures can be anticipated for JobRepository in particular I think it would be better to handle them at a lower level out of the box (i.e. I'm in favor of a default that's more robust than NeverRetryPolicy).  Perhaps there is a case to add RetryOperations to SimpleJobLauncher instead of SimpleJobRepository?  I didn't notice a JobLauncherFactoryBean equivalent to AbstractJobRepositoryFactoryBean.

---

**Affects:** 2.0.0

**Reference URL:** http://forum.springsource.org/showpost.php?p=249913

**Comment by javaHelper** [comment]
@benas - Thanks for sharing the sample example.  We've a multiple chunk based steps in a single Job. Assume if 2nd step got failed, will `retryTemplate.execute` ensure that it will restart at the point where it has failed ?  Could you please confirm if passing the same job parameters will be sufficient?

**Comment by mminella** [comment]
It's not the `RetryTemplate` that enables that support. It's the statefulness of the components (those that implement `ItemStream`. These questions are better asked on StackOverflow and tagged with `spring-batch`.

**Comment by javaHelper** [comment]
@mminella - Ok thanks, will you please guide here: https://stackoverflow.com/questions/63705853/how-can-we-resume-spring-batch-job-where-it-had-failed ?
