### ISSUE TITLE
Add flag to FlatFileItemWriter to delete empty files [BATCH-1317]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2262]
**[Alexander Kuleshov](https://jira.spring.io/secure/ViewProfile.jspa?name=arhat)** opened **[BATCH-1317](https://jira.spring.io/browse/BATCH-1317?redirect=false)** and commented

In some cases there are need to delete empty files after processing.
May be possible to create boolean property with corresponding functionality.

---

**Referenced from:** commits https://github.com/spring-projects/spring-batch/commit/758082e28fe8f90e6bc11190b337a4fea71e7005, https://github.com/spring-projects/spring-batch/commit/822f8bb86822c28da43aa4c44f005ca1fbe244fb

**Comment by akhettar** [comment]
Has anyone tested this feature? It looks like the flag is deleting empty and not empty files in my case.

**Comment by mminella** [comment]
@akhettar That question is best asked on StackOverflow.
