### ISSUE TITLE
site:deploy - Missing distribution management information in the project [BATCH-1191]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2388]
**[Thomas Risberg](https://jira.spring.io/secure/ViewProfile.jspa?name=thomas.risberg)** opened **[BATCH-1191](https://jira.spring.io/browse/BATCH-1191?redirect=false)** and commented

running site:deploy there is an error saying "Missing distribution management information in the project".

Here is the log output:

[INFO] ------------------------------------------------------------------------
[INFO] Building Commandline
[INFO]    task-segment: [site:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [site:deploy]
file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli - Session: Opened  
file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli - Session: Disconnecting  
file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli - Session: Disconnected
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Batch
[INFO]    task-segment: [site:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [site:deploy]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Missing distribution management information in the project
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 minutes 28 seconds
[INFO] Finished at: Wed Apr 01 15:42:59 EDT 2009
[INFO] Final Memory: 8M/15M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.0.RC3

**Referenced from:** commits https://github.com/spring-projects/spring-batch/commit/822f8bb86822c28da43aa4c44f005ca1fbe244fb, https://github.com/spring-projects/spring-batch/commit/e755d0848a0a0da3ddb64c61e25a7d1acb66eb56

**Comment by xiaobaimai** [comment]
> **[托马斯·里斯伯格](https://jira.spring.io/secure/ViewProfile.jspa?name=thomas.risberg)**开设了 **[BATCH-1191](https://jira.spring.io/browse/BATCH-1191?redirect=false)** 并发表评论
> 
> 正在运行的站点：deploy 出现错误，指出“项目中缺少分发管理信息”。
> 
> 以下是日志输出：
> 
> [信息] ------------------------------------------------------------------------ [信息] 构建命令行 [信息] 任务段： [站点：部署] [信息] ------------------------------------------------------------------------ [信息] [网站：部署] file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli -会话：已打开 file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli - 会话：断开 file:////home/trisberg/Projects/spring-batch/tags/2.0.0.RC3/target/staging/org.springframework.batch.archetype/org.springframework.batch.archetype.simple.cli - 会话：已断开连接 [INFO] ------------------------------------------------------------------------ [信息] 生成春季批处理 [信息] 任务段： [站点：部署] [信息] ------------------------------------------------------------------------ [信息] [站点：部署] [信息] ------------------------------------------------------------------------ [错误] 构建错误 [信息] ------------------------------------------------------------------------ [信息]项目中缺少分发管理信息 [INFO] ------------------------------------------------------------------------ [INFO] 有关更多信息，请使用 -e 开关运行 Maven [INFO] ------------------------------------------------------------------------ [INFO] 总时间： 3 分 28 秒 [INFO] 完成时间： 周三 4 月 01 日 15：42：59 EDT 2009 [信息] 最终内存： 8M/15M [信息] --------------------------------------------------------------------
> 
> **影响：** 2.0.0.RC3
> 
> **引用自：**提交 [822f8bb](https://github.com/spring-projects/spring-batch/commit/822f8bb86822c28da43aa4c44f005ca1fbe244fb)、[e755d08](https://github.com/spring-projects/spring-batch/commit/e755d0848a0a0da3ddb64c61e25a7d1acb66eb56)

我的maven也是这个问题，解决不了怎么办，大佬留个联系方式救救急可以吗
