### ISSUE TITLE
Mainframe console commands for spring-batch JCL using JZOS [BATCH-257]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#3322]
**[Nigel DeFreitas](https://jira.spring.io/secure/ViewProfile.jspa?name=ndefreitas)** opened **[BATCH-257](https://jira.spring.io/browse/BATCH-257?redirect=false)** and commented

I think someone should write a module to route mainframe console commands to interact with the spring-batch JCL commands. e.g. start | stop | purge | status | others...

This would allow mainframe operators to control spring-batch jobs running on the mainframe the way they've always controlled other COBOL jobs - no training needed.

---

**Affects:** 1.0.0.m4

**Comment by benas** [comment]
> **[Nigel DeFreitas](https://jira.spring.io/secure/ViewProfile.jspa?name=ndefreitas)** opened **[BATCH-257](https://jira.spring.io/browse/BATCH-257?redirect=false)** and commented
> 
> I think someone should write a module to route mainframe console commands to interact with the spring-batch JCL commands.

If someone is interested in implementing this module, he/she can contribute it to the https://github.com/spring-projects/spring-batch-extensions repo.
