### ISSUE TITLE
The dependencies for Micrometer should be optional

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-batch#3629]
Currently the micrometer dependencies have a scope of compile time, even if we don't or are interested in the metrics we get these dependencies. 

Would be better if they were optional instead.

**Comment by mminella** [comment]
This really isn't possible given the way we need to implement the functionality within Spring Batch.  We view these dependencies similar to logging.  You can not use logging in your application but we still require the libraries to be included.
