### ISSUE TITLE
Fix dead link to gihub help in Contributor Guidelines

### ISSUE THREAD

**Issue by benoitdupont** [spring-projects/spring-batch#3641]
Hello, 

the link https://help.github.com/en/send-pull-requests is dead in https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md.

I updated it with https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by benas** [comment]
Closing this as it was fixed in #3642 .
