### ISSUE TITLE
StepExecution counts integer overflow

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-projects/spring-batch#3650]
Hi,

In StepExecution class counts like readCount/writeCount, etc has int type.
In case when step operates on a big amount of items, there may be an int overflow and may affect e.g. progress monitoring if someone use these counters.

Should we change it to long instead?

**Comment by ArtyomGabeev** [comment]
Also noted, apply method which increments counts is synchronized. Should we switch from volatile to atomic long?

**Comment by benas** [comment]
Similar/Related to #1055.

**Comment by ArtyomGabeev** [comment]
@benas any update on this? we are getting integer overflow :)

**Comment by adityausathe** [comment]
@benas, If this is up for grabs, I would like to take a shot at it. It would be helpful if you could provide some pointers.

**Comment by benas** [comment]
@ArtyomGabeev Thank you for reporting this issue. The problem can also happen in a locally or remotely partitioned/chunked step: each worker could contribute a read/write count and the aggregation might silently fail with an integer overflow on the manager side, leading to incorrect counters in the aggregate `StepExecution`. An example can be found [here](https://github.com/benas/spring-batch-lab/blob/main/issues/gh3650/src/main/java/io/spring/PartitionJobSample.java).

Changing the type of metrics from `int` to `long` seems reasonable to me for a major version. Moreover, columns in the `BATCH_STEP_EXECUTION` table are already designed to accept `long` values.
