### ISSUE TITLE
Set topic to KafkaItemWriter

### ISSUE THREAD

**Issue by ta7uw** [spring-projects/spring-batch#3654]
Hi, 
I’d like to set a topic other than the default topic to `KafkaItemWriter`.

```java
    @Bean
    public KafkaItemWriter<K, V> kafkaItemWriter() {
        return new KafkaItemWriterBuilder<K, V>()
                .topic(topic)
                .kafkaTemplate(kafkaTemplate)
                .build();
    }
```

That’s  because `KafkaItemWriter` uses only a default topic of the `KafkaTemplate` and I cannot use two `KafkaItemWriter` at the same time for different topics.

`KafkaTemplate` that is used in `KafkaItemWriter` is designed to be thread-safe.
Therefore It might be a good idea to design `KafkaItemWriter` is thread-safe.

I think we can do it  by providing a API like `send(String topic, K key,V data)` method in `KafkaTemplate`.

**Comment by mminella** [comment]
KafkaTemplate is not a Spring Batch class.  You would need to take that up
with the Spring for Apache Kafka project to get that method added.

That being said, I’m it sure it would matter.  You can write two two topics
via two ItemWriters using two KafkaTemplate instances so this use case can
be addressed with the current code.

**Comment by ta7uw** [comment]
>  You can write two two topics
via two ItemWriters using two KafkaTemplate instances so this use case can
be addressed with the current code.

That's definitely correct but I think that auto-configured `KafkaTempalte`([KafkaAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java#L66))  is used in many cases.
So, It might be a good idea to call `send(String topic, K key,V data)` [method](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java#L220) in `KafkaItemWriter` .

**Comment by benas** [comment]
Closing this as discussed in #3662 .
