### ISSUE TITLE
Create versions of samples using Java configuration

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-batch#3663]
Currently the vast majority of the Spring Batch examples are configured using XML configuration.  This issue is to create an equivalent sample of each using Java configuration.

**Comment by dimitrisli** [comment]
Hi @mminella , from 'structural' point of view how are you envisioning this? For example in the spring-batch-samples for each /resources/jobs/**/*.xml job context file to have a respective config class and secondarily for each *Tests.java underneath the test folder to have an equivalent Test class pointing to the respective config class files? Or other ideas on structure/name-conventions?
