### ISSUE TITLE
Migrate to SLF4J

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-batch#3665]
At the moment you are using commons-logging and that one does not support features like embedding placeholders like this:
```
LOG.error ("Item {} is wrong", itemId);
```
SLF4J supports this, and is also implementation agnostic. Please consider switching to SLF4J

**Comment by benas** [comment]
Being based on Spring Framework, Spring Batch follows the same choice as SF in regards to the logging framework for consistency. Here are some issues that explain why SF is still using commons-logging:

* [Consider migrating from Commons-Logging to SLF4j](https://github.com/spring-projects/spring-framework/issues/10000)
* [Why Spring does not use placeholders to output logs?](https://github.com/spring-projects/spring-framework/issues/23242#issuecomment-508986857)
* [Revisit Commons Logging vs java.util.logging vs SLF4J vs Log4j 2](https://github.com/spring-projects/spring-framework/issues/19081)
