### ISSUE TITLE
Propagate exception encountered in partitioned step (Stop job execution)

### ISSUE THREAD

**Issue by gogleowner** [spring-projects/spring-batch#3672]
Hello, I have a problem using partitioner.
this problem is same in stackoverflow link.
(https://stackoverflow.com/questions/35985815/spring-batch-propagate-exception-encountered-in-partitioned-step-stop-job-exe?noredirect=1&lq=1)

Please answer about this question. thank you!

**Comment by benas** [comment]
I answered the question on SO: https://stackoverflow.com/a/60485438/5019386.

If you have any question/comment/concern, please add it in SO. We would like to keep this issue tracker only for bug reports and feature requests.

Thank you.
