### ISSUE TITLE
Possible duplicate state transitions in flow definition

### ISSUE THREAD

**Issue by neo4Play** [spring-projects/spring-batch#3674]
`o.s.b.core.job.flow.support.SimpleFlow` point to `StateTransition` in the variable `transitionMap` parameterized by `Map<String, Set<StateTransition>>`.
We get duplicated entries in the `Set` by using `o.s.b.core.job.builder.FlowJobBuilder` but it doesn't leads to an error!

**Sample**:
```java
final FlowJobBuilder flowJobBuilder = this.parentJobConfig.customJobBuilders()
		.get(jobName)
		.start(step1)
		.on(ExitStatus.FAILED.getExitCode())
		.fail()
		.on(ExitStatus.STOPPED.getExitCode())
		.stop()
		.next(step2)
		.on(ExitStatus.COMPLETED.getExitCode())
		.end()
		.on(ExitStatus.FAILED.getExitCode())
		.fail()
		.on(ExitStatus.STOPPED.getExitCode())
		.stop()
		.build();
```

The basic functions hash() and equals() would avoid the bad code smell!

**Comment by hyosyung** [comment]
Hi team, can I take this issue?

**Comment by Kyoungwoong** [comment]
pr: #4590
