### ISSUE TITLE
JobParameters#toString() leak secrets in logs

### ISSUE THREAD

**Issue by vy** [spring-projects/spring-batch#3680]
We pass authentication credentials to certain batch jobs via parameters. Though the following excerpt from `SimpleJobLauncher` leaks these secrets unconditionally:

```java
logger.info("Job: [" + job + "] launched with the following parameters: [" + jobParameters + "]");
```

This is due the way `JobParameters#toString()` is implemented:

```java
private final Map<String,JobParameter> parameters;

@Override
public String toString() {
    return parameters.toString();
}
```

We can indeed tune logging level for the class as a hotfix. Though I'd rather prefer Spring Batch wildcarding secret parameters, that is, the ones that end with a `*` suffix, AFAIK.

**Comment by benas** [comment]
That is not a Spring Batch concern. Spring Batch cannot (and should not) know that a parameter is a secret (starts with `*`? ends with `*`? contains `*`..?). As far as Spring Batch is concerned, it should log the job parameters passed to it without any modification. 

You should not pass secrets as job parameters. This is not only unsecure (even if they are hashed/encrypted), but also a wrong usage of job parameters. Job parameters are meant to identify job instances, not to pass config/secret parameters. Even if you use non-identifying job parameters for that, it is still not the way to do it.

If a batch artefact needs to access a secured resource (like a processor that calls a secured web service for example), it can be configured using the usual config approaches (properties files, environment variables, etc) or using a config/secret management tool like [Spring Cloud Config](https://spring.io/projects/spring-cloud-config), [Vault](https://www.vaultproject.io), [Kubernetes configMaps/Secrets](https://kubernetes.io/docs/concepts/configuration/secret/), or similar tools.

Do you agree?

**Comment by vy** [comment]
@benas Agreed. That said, it might worth to mention this concern along with the recommended work around in the manual. For the records, we have hotfixed the issue by a custom `JobParameters` implementation. You can close this issue if you wish or use it for updating the manual. Thanks for your attention.

**Comment by mminella** [comment]
@vy One other thing to note about using `JobParameters` to pass in secrets.  They are stored as plain text in the `JobRepository` making that a point of attack.  As @benas mentioned, I would not use `JobParameters` to pass in secrets and use other configuration options to handle them.

**Comment by benas** [comment]
> it might worth to mention this concern along with the recommended work around in the manual

There are no workarounds here, the clean way to address this is to *not* pass secrets as job parameters. I believe this is common sense, but if you think it should be explicitly mentioned in the docs, please open a PR and we can consider adding it. Thank you.
