### ISSUE TITLE
`FlatFileItemReaderBuilder` reports error "Only one LineTokenizer option may be configured" when none are.

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-batch#3688]
At line [472](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/file/builder/FlatFileItemReaderBuilder.java#L472) of the `FlatFileItemReaderBuilder` it validates that not multiple `LineTokenizers` implementations have been configured.  However, if the user has not configured one (`validatorValue == 0` on that line), they get the same message implying that multiple have been configured.  This error message should not be thrown if `validatorValue == 0`.  The case of no `LineTokenizer` being configured is already handled at line [487](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/file/builder/FlatFileItemReaderBuilder.java#L487) of that class anyways.

**Comment by santfirax** [comment]
Hello, I'd like to work on this.

**Comment by mminella** [comment]
If anyone is interested in working on this, please checkout the contribution guidelines here: https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md

**Comment by santfirax** [comment]
Hello, can you take a look at this PR? https://github.com/spring-projects/spring-batch/pull/3689

**Comment by mminella** [comment]
Thanks to @santfirax to addressing this in amazingly fast time!  Resolved via https://github.com/spring-projects/spring-batch/pull/3689
