### ISSUE TITLE
Misleading Java code in Spring official docs

### ISSUE THREAD

**Issue by JacksonPhoong** [spring-projects/spring-batch#3692]
In the Spring official docs, [here](https://docs.spring.io/spring-batch/docs/current-SNAPSHOT/reference/html/spring-batch-integration.html#spring-batch-integration-configuration), in the Java configuration code under **Spring Batch Integration Configuration**, there is a typo that is misleading. The `handle()` should be `transform()` in the `integrationFlow` method. 

Artem Bilan asked me to raise this issue when I asked him about it on a [question](https://stackoverflow.com/questions/61100608/why-do-i-get-the-exception-found-ambiguous-parameter-type-spring-batch-integr) in StackOverflow.

**Comment by charvakcpatel007** [comment]
I would like to pick this up
The change will occur in this file https://github.com/spring-projects/spring-batch/blob/master/spring-batch-docs/asciidoc/spring-batch-integration.adoc
on line number on line 326.

**Comment by benas** [comment]
@charvakcpatel007 Thank you for your suggestion to help. If there is no open PR for a ticket, then it is open for contribution. So you are welcome!
