### ISSUE TITLE
spring-batch chuck will create five threads default

### ISSUE THREAD

**Issue by LegendWu** [spring-projects/spring-batch#3706]
Hi all,
When I set chuck's size is 1000, and the reader read total size less then 1000, then the application created five threads to deal with this data, for example:
reader: 800
chunk: 1000

expected:  just one thread to deal with 800 data
         thread-1 : 800
result: they are split to multi threads
         thread-1 : 200
         thread-2 : 200
         thread-3 : 200
         thread-4 : 100
         thread-5 : 100

**Comment by ankurtrapasiya** [comment]
can you please give steps to reproduce this?

**Comment by benas** [comment]
@LegendWu Please ask your question on SO and provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). If we confirm there is a problem in Spring Batch, we can re-open this issue. Thank you.
