### ISSUE TITLE
Missed parameter "connectionAutoCommit" in JdbcCursorItemReaderBuilder

### ISSUE THREAD

**Issue by qwazer** [spring-projects/spring-batch#3717]
**Bug description**
AbstractCursorItemReader has parameter "connectionAutoCommit" that is not configurable with JdbcCursorItemReaderBuilder

**Expected behavior**
"connectionAutoCommit" can be configured with JdbcCursorItemReaderBuilder

**Additional info**
The parameter "connectionAutoCommit"  was added in https://github.com/spring-projects/spring-batch/pull/446

**Comment by ankurtrapasiya** [comment]
@qwazer May I please work on this issue? I have prior experience working with Spring-Batch and I would like to contribute to the project.

**Comment by qwazer** [comment]
> @qwazer May I please work on this issue? I have prior experience working with Spring-Batch and I would like to contribute to the project.

H, @ankurtrapasiya  Yes. Why not.

**Comment by ankurtrapasiya** [comment]
Please review https://github.com/spring-projects/spring-batch/pull/3719/

**Comment by ankurtrapasiya** [comment]
@qwazer @benas  - can you please review my PR?

**Comment by benas** [comment]
@ankurtrapasiya Thank you for your PR, I will let you know once I start looking at it. Thank you.

**Comment by benas** [comment]
Fixed in #3719 .
