### ISSUE TITLE
Spring Boot batch job does not shut down automatically after completion when using JPA

### ISSUE THREAD

**Issue by martinmogusu** [spring-projects/spring-batch#3725]
**Bug description**
I notice that  a spring boot batch application does not shut down automatically after completing a job when using Spring data JPA. The job completes successfully but the spring boot application remains running and has to be stopped manually (e.g. by pressing `Ctrl + C`).

**Environment**
Spring boot version: **2.3.0.RELEASE**
Java version: **1.8**
OS: **Windows**

**Steps to reproduce**
1. Create a new spring boot project from https://start.spring.io/
2. Add the following dependencies:
- `spring-boot-starter-batch`
- `spring-boot-starter-data-jpa`
- `h2`
3. Create a tasklet step
4. Configure a spring batch job referencing the tasklet step

**Expected behavior**
The job should execute successfully, and shut down automatically.

**Minimal Complete Reproducible example**

Dependencies in pom.xml
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-batch</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
	<groupId>com.h2database</groupId>
	<artifactId>h2</artifactId>
	<scope>runtime</scope>
</dependency>
```

Batch configuration class

```java
@Configuration
public class BatchConfiguration {

    @Bean
    public Job sampleJob(JobBuilderFactory jobBuilderFactory, Step step1) {
        return jobBuilderFactory.get("sampleJob").incrementer(new RunIdIncrementer()).flow(step1).end().build();
    }

    @Bean
    public Step step1(StepBuilderFactory stepBuilderFactory, StepTasklet tasklet) {
        return stepBuilderFactory.get("step1").tasklet(tasklet).build();
    }

}
```

Tasklet step class

```java
public class StepTasklet implements Tasklet {

    @Override
    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
        System.out.println("Executing tasklet step...");
        return RepeatStatus.FINISHED;
    }
    
}
```

**Comment by florentbo** [comment]
I have the same problem...

**Comment by florian-serraille** [comment]
Good day,

I do not know if this is the better way to solve your problem but you can wrap your SptingApplication.run() method with SpringApplication.exit():

`	public static void main(String[] args) {
		SpringApplication.exit(SpringApplication.run(DemoApplication.class, args));
	}
`

**Comment by mminella** [comment]
I was able to re-create the issue but I do not believe it's a batch issue. If you remove the JPA starter, the application the application shuts down as expected. Since your job has nothing to do with JPA, I don't see this as a batch issue. Please create an issue in https://github.com/spring-projects/spring-boot and it can be discussed there. We can re-open this issue if it is determined that it is a batch issue.
