### ISSUE TITLE
Setting resource should be optional for JsonItemReaderBuilder

### ISSUE THREAD

**Issue by davemrunal** [spring-projects/spring-batch#3731]
As suggested by @benas, creating this issue.

Detailed description on this [StackOverflow question](https://stackoverflow.com/questions/62437961/how-to-set-delegate-while-using-gsonjsonobjectreader-with-multiresourceitemreade/62448132#62448132)

**Comment by santfirax** [comment]
Hello @davemrunal @benas I would like to work in this issue

**Comment by benas** [comment]
@santfirax Thank you for your suggestion to help! I assigned it to you. Looking forward to your PR.

**Comment by santfirax** [comment]
@benas I'm having some problems running the unit tests in JsonItemReaderBuilderTest class, could it be possible that you show me how to run this tests?

**Comment by santfirax** [comment]
Hello @benas @davemrunal  here's the PR https://github.com/spring-projects/spring-batch/pull/3739
