### ISSUE TITLE
KafkaItemReader & KafkaItemWriter use of multiple generics breaks the model of ItemReader<T> ItemWriter<T>

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-batch#3734]
In cases where a user is expecting a` ItemWriter<T>` or `ItemReader<T>` parameter for a step bean, the  `KafkaItemReader` and `KafkaItemWriter` can't be injected.   For example if we have:
```
	@Bean
	public Step step1(ItemReader<Map<Object,Object>> itemReader, ItemWriter<Map<Object,Object>> writer) {
		return stepBuilderFactory.get("step1")
				.<Map<Object,Object>,Map<Object,Object>>chunk(5)
				.reader(itemReader)
				.writer(writer)
				.build();
	}
	@Bean
	public KafkaItemReader<Object, Map<Object,Object>> kafkaItemReader() {
         ...
        }
```
In this example the `KafkaItemReader` will fail to be injected into the `itemReader` parameter of the `step1` bean.  
We can change the  code to something like:
```
	@Bean
	public Step step1(ItemReaderitemReader, ItemWriter<Map<Object,Object>> writer) {
         ...
        }
````
And it will be injected however we lose the typing restriction of `Map<Object,Object>` that we want to enforce.

**Comment by benas** [comment]
Hi @cppwfs ,

Thank you for opening this issue.

This is not related to Kafka item reader/writer per se as we have other components using multiple generics like the `KeyValueItemWriter<K,V>` and `GemfireItemWriter<K,V>`.

> In this example the KafkaItemReader will fail to be injected into the itemReader parameter of the step1 bean.

I was not able to reproduce this issue. Here is a minimal repo where a `KafkaItemReader<Object, Map<Object,Object>>` is correctly injected in a step:  [gh3734.zip](https://github.com/spring-projects/spring-batch/files/4825706/gh3734.zip) whether the step method signature is like:

```java
public Step step(ItemReader<Map<Object,Object>> reader, ItemWriter<Map<Object,Object>> writer) { .. }
```
or

```java
public Step step(KafkaItemReader<Object, Map<Object,Object>> reader, ItemWriter<Map<Object,Object>> writer) { .. }
```

That said, I do not understand the reasoning behind using `Object` as type for item keys (nor values BTW). Which key deserializer do you use in your consumer properties? I see no `ObjectDeserializer` provided by Kafka for that (I'm not sure if this is a good practice from a security point of view).

**Comment by cppwfs** [comment]
Hello @benas 
Thank you for the detailed writeup on this issue.   It showed me that my code should be working, and I dug deeper and found out I had made a noob mistake.

Thanks for spending time on this.  Now I will crawl back under my rock!
