### ISSUE TITLE
 Can you add a Mybatis function of Sqlsessiontemplate.

### ISSUE THREAD

**Issue by pixy032** [spring-projects/spring-batch#3735]
**Expected Behavior**
    BatchTaskEntityExample selectExample = new BatchTaskEntityExample();
    BatchTaskEntityExample.Criteria selectCriteria = selectExample1.createCriteria();
    selectCriteria.andTaskStatusEqualTo("processing");
    selectCriteria.andStartTimeLessThan(maxTime);
    List<BatchTaskEntity> batchs = batchTaskEntityMapper.selectByExample(selectExample);
**Current Behavior**
    MyBatisCursorItemReader<MstEmployeesEntity> reader = new MyBatisCursorItemReader<MstEmployeesEntity>();
    reader.setSqlSessionFactory(sqlSessionFactory);
    reader.setQueryId("xxx.xxx.xxxx.xxxxxxx.mapper.BatchMstEmployeesEntityMapper.exmapleSelect");
    reader.setParameterValues(map);
    return reader;

Can you run mybatis in the same way as spring boot mybatis.

**Comment by mminella** [comment]
The MyBatis project is who maintains the `MyBatisCursorItemReader` (it's not a Spring class) and related MyBatis support. Please log any issues you have with the MyBatis support there: https://github.com/mybatis/spring/issues
