### ISSUE TITLE
BulkOperations API Implementaion for Remove Operations in MongoItemWriter

### ISSUE THREAD

**Issue by parikshitdutta** [spring-projects/spring-batch#3737]
While reviewing performance incentive in MongoItemWriter post BulkOperations API implementation to handle save operations #3713, we can implement respective BulkOperation API for removal as well.

**Comment by parikshitdutta** [comment]
Hi @benas ,
I can put the together the required changes for this, if you see value in this, Please assign me.

Thank you.

**Comment by parikshitdutta** [comment]
Hi @benas, Please have a look at PR #3746. I will look forward to your feedback.

Thank you.

**Comment by benas** [comment]
Resolved with #3746 .
