### ISSUE TITLE
`SimpleCompletionPolicy` should have `getChunkSize()` method.

### ISSUE THREAD

**Issue by MinJunKweon** [spring-projects/spring-batch#3738]
Currently, `SimpleCompletionPolicy` doesn't have `getChunkSize()`.
But `toString()` method returns a string that include own chunk size by some format.

You can see them on [this](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-infrastructure/src/main/java/org/springframework/batch/repeat/policy/SimpleCompletionPolicy.java#L117).
```java
SimpleCompletionPolicy examplePolicy = new SimpleCompletionPolicy(50);
System.out.println(examplePolicy.toString());
// SimpleCompletionPolicy: chunkSize=50
```

I think it is a **code smell**.
If I want to get its chunk size, I have to parse `toString()` result. It is a very ugly way.

I suggest two options to solve this.
1. Make `toString()` doesn't show own chunk size.
2. **Make `getChunkSize()` public method.**

In my opinion, It should be second option.
If you approve this idea, comment, please. And then, I will make a pull request for this.

Thank you.

**Comment by LOG-INFO** [comment]
I have same problem.

I'm parsing chunkSize using toString(). I know this is a bad way.
I'm worried there will be an error if the toString() format changes even a little.

I think the getChunkSize() should be a public method.

**Comment by SeoungJinKim** [comment]
I agree that problem.

So, I think getChunkSize() is good suggestion.

**Comment by benas** [comment]
There is already a setter for `chunkSize`, I see no harm in adding a getter as well.

> If you approve this idea, comment, please. And then, I will make a pull request for this.

@MinJunKweon Go ahead and open a PR, thank you upfront!
