### ISSUE TITLE
Include thread-safe versions of ListItemReader and ListItemWriter to org.springframework.batch.item.support package

### ISSUE THREAD

**Issue by qwazer** [spring-projects/spring-batch#3741]
Please do a quick search on Github issues first, the feature you are about to request might have already been requested.

**Expected Behavior**

**Current Behavior**

There are no thread-safe version of ListItemReader and ListItemWriter in spring-batch.
It's not possible to use make it thread-safe with SynchronizedItemStreamReader and
SynchronizedItemStreamWriter. because  ListItemReader and  ListItemWriter doesn' implement ItemStream interface 

**Context**

I want to test my job in multi-threaded thread-pool executor.
Delegating of thread-safety with java.util.Collections#synchronizedList(java.util.List<T>, java.lang.Object) doesn't work, because it doesn't prevent from unwanted read and incorrectly increase step read counts.

**Comment by qwazer** [comment]
Another option is to include SynchronizedItemReader, SynchronizedItemWriter to spring-batch

**Comment by fmbenhassine** [comment]
Adding `SynchronizedItemReader` and `SynchronizedItemWriter` to Spring Batch is a better option. I created #4368 for that. Closing this in favor of #4368.
