### ISSUE TITLE
Incorrect SimpleRetryPolicy Documentation

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-batch#3744]
The [documentation](https://docs.spring.io/spring-batch/docs/current/reference/html/retry.html#retryPolicies) talks about `setRetryableExceptions()` and `setFatalExceptions()`.

These methods don't exist; instead retryable exceptions (and not) are provided in a Map via a constructor.

See https://stackoverflow.com/questions/62836985/simpleretrypolicy-spring

**Comment by hpoettker** [comment]
I think this issue can be closed. The outdated part of the documentation has been removed with 9d2e6c6d2a810074eba9b324fa40b4f795c58aa4.

**Comment by fmbenhassine** [comment]
Closing this as outdated.
