### ISSUE TITLE
Incorrect usage of StringBuilder

### ISSUE THREAD

**Issue by pstowski** [spring-projects/spring-batch#3745]
Method `public void write(String str, int off, int len)` of `org.springframework.batch.support.transaction.TransactionAwareBufferedWriter` 
seems to be using `java.lang.StringBuilder` in wrong way:
according to documentation [StringBuilder.append(java.lang.CharSequence,int,int)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/StringBuilder.html#append(java.lang.CharSequence,int,int))
third parameter is not length (as in `append(char[],int,int)`) but the end index of the subsequence.
this causes invalid parts of string are being appended and causes `java.lang.IndexOutOfBoundsException` when `off > len`

Using: spring-batch-infrastructure 4.2.4.RELEASE

**Comment by mrickly** [comment]
We ran into that bug too.

**Comment by mprcptbl** [comment]
Same problem, using `StaxEventItemWriter`.

**Comment by nfjcore** [comment]
I would like to start contributing to this project. This seems like a good issue to work on. Can someone provide steps how to reproduce the problem?

**Comment by benas** [comment]
@nfjcore You are welcome! Please check our [Contributor Guidelines](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md). I did not work on this issue yet to validate the bug report, but the best way to start is by trying to create a failing test that reproduces the problem. I would be happy to review any PR that contains such a test with a corresponding fix. Let me know if you want me to assign this issue to you.

**Comment by niels5789** [comment]
@benas Thank you for the reply. I've read the Contributor Guidelines. And like the issue to be assigned to me.

**Comment by mprcptbl** [comment]
@niels5789 I don't have a simple testcase for this right now but you should be able to reproduce this by generating XML output using `StaxEventItemWriter` with the default `transactional=true` (e.g. create a simple Spring Batch job to do this) when your input data contains any XML special characters like ampersand. less than, etc.

**Comment by benas** [comment]
In order to avoid any confusion about to whom this issue should be assigned, I'm not going to assign it to anyone. Everyone is welcome to contribute to the project. If a PR is opened for this bug, I will link it to this issue.

**Comment by benas** [comment]
Fixed in #3843 .
