### ISSUE TITLE
StaxEventItemReaderBuilder failing to set name for Reader at build

### ISSUE THREAD

**Issue by parikshitdutta** [spring-projects/spring-batch#3753]
```StaxEventItemReaderBuilder``` does not seem to set name for the reader at the build. 

This [block](
https://github.com/spring-projects/spring-batch/blob/4d9e7e55414b9d21014a4b709c967b578327ff10/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/xml/builder/StaxEventItemReaderBuilder.java#L231) doesn't look correct.

**Comment by parikshitdutta** [comment]
Hi @benas, 
If you see my claim correct, Please assign it to me.

Thank you.

**Comment by mminella** [comment]
@parikshitdutta You are correct. Feel free to submit a PR. Thanks for catching this!

**Comment by parikshitdutta** [comment]
Hi @mminella , 
Please have a look at PR #3784, I will look forward to your feedback.

Thank you.

**Comment by benas** [comment]
Resolved with #3784 .
