### ISSUE TITLE
How to handle tasks with less input data and more output data?

### ISSUE THREAD

**Issue by huangxfchn** [spring-projects/spring-batch#3754]
**Expected Behavior**
I have a demand for production data to generate a Cartesian from 3 grouped data, and then write it into the database. The amount of input data is small, but the amount of output data is larger, probably several million data.

**Current Behavior**
Because my data is large, the final data produced is in the order of millions. I hope to use spring-batch to handle this task, but it seems that I have not found a good solution.

**Context**
* For example, there are 3 groups G1, G2, G3, assuming that G1 has x data, G2 has y data, and G3 has z data, then the generated data may be (x * y * z).
* Perhaps, if ItemProcessor#process() method supports returning Iterator iterators, this type of problem may be solved.

**Comment by mminella** [comment]
Questions like this are best asked on StackOverflow. I'm closing this now and we can continue the discussion there.
