### ISSUE TITLE
  After running chunk many times, the infinite loop executes "update Batch_ STEP_ EXECUTION"

### ISSUE THREAD

**Issue by chuwj** [spring-projects/spring-batch#3756]
The jdbccursoritemreader is used. After the chunk is executed many times or the chunk is broken, the wireless loop executes "update batch"_ step_ execution ...”.
spring batch 4.0.1

**Comment by benas** [comment]
Thank you for opening this issue. However, we can't reproduce it with what you described. Please provide a failing test or minimal complete example that reproduces the issue and we will take a look.

> spring batch 4.0.1

Spring Batch v4.0 is not maintained anymore. Please upgrade to the latest v4.3 at your earliest convenience and let us know if you still have the issue.
