### ISSUE TITLE
Using SystemCommandTasklet to split a large file

### ISSUE THREAD

**Issue by nischalmadhava** [spring-projects/spring-batch#3759]
0

I am trying to split a large flat file into multiple files using SystemCommandTasklet in Spring Batch. I am retrieving the large file from scality and storing it in the temp directory. Below is my code.

@Bean
@StepScope
public SystemCommandTasklet fileSplitterSystemCommandTasklet() throws Exception {

    final String fileSeparator = System.getProperty("file.separator");
    String outputDirectory = tempFile.getAbsolutePath().substring(0, tempFile.getAbsolutePath().lastIndexOf(fileSeparator)) + fileSeparator + "out" + fileSeparator;

    File output = new File(outputDirectory);

    if (!output.exists()) {
        output.mkdir();
    }

    System.out.println(tempFile.getName()+" "+tempFile.getAbsolutePath());

    File tmpdir = new File(AccessController
            .doPrivileged(new GetPropertyAction("java.io.tmpdir")));

    final String command = String.format("split -a 5 -l 100 %s %s",tempFile.getAbsolutePath(),outputDirectory);

    System.out.println(command);

    SystemCommandTasklet fileSplitterTasklet = new SystemCommandTasklet();
    fileSplitterTasklet.setCommand(command);
    fileSplitterTasklet.setTimeout(60000L);
    fileSplitterTasklet.setWorkingDirectory(tempFile.getParent());
    fileSplitterTasklet.setTaskExecutor(new SimpleAsyncTaskExecutor());
    fileSplitterTasklet.setSystemProcessExitCodeMapper(new SimpleSystemProcessExitCodeMapper());
    fileSplitterTasklet.afterPropertiesSet();
    fileSplitterTasklet.setInterruptOnCancel(true);
    /*fileSplitterTasklet.setEnvironmentParams(new String[]{
            "JAVA_HOME=/java",
            "BATCH_HOME=/Users/batch"});*/
    fileSplitterTasklet.setEnvironmentParams(null);

    return fileSplitterTasklet;
}
I'm getting the below error: Cannot run program "split" (in directory "C:\Users\nmadk\AppData\Local\Temp"): CreateProcess error=2, The system cannot find the file specified

This is a duplicate of the question Using SystemCommandTasklet to split file. But I'm still unable to implement this.

I also need to know that SystemCommandTasklet class can be used in PCF?

I'm using a windows machine in my local, does split command work in windows with SystemCommandTasklet?

**Comment by nischalmadhava** [comment]
the link to the stackoverflow question is below.
https://stackoverflow.com/questions/63356397/using-systemcommandtasklet-to-split-a-large-file

**Comment by mminella** [comment]
I left a comment on StackOverflow. Closing this and will address there.
