### ISSUE TITLE
KafKaItemReader

### ISSUE THREAD

**Issue by MicrophoneBen** [spring-projects/spring-batch#3760]
**Bug description**
When I use the KafKaItemReader to consumer the KafKa data from kafka cluster, if the offset is not begin from 0,  and the kafkaItem reader can not read data from the kafka cluster 

**Environment**
springbatch-4.2.4.RELEASE, springboot

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**
the offset is not begin from 0,  and the kafkaItem reader can read data from the kafka cluster

**Comment by benas** [comment]
This has been addressed in #737 which will be included in the upcoming v4.3.0-M2.
