### ISSUE TITLE
How to specify a custom MaxValueIncrementer in springbatch ？

### ISSUE THREAD

**Issue by zzq1314zll** [spring-projects/spring-batch#3770]
I wrote a MaxValueIncrementer strategy, how to specify the use of springbatch

**Comment by benas** [comment]
These questions are best asked on [stackoverflow](https://github.com/spring-projects/spring-batch#getting-help) with the `spring-batch` tag, but I will answer here for now and close the issue.

You need to define a [DataFieldMaxValueIncrementerFactory](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/item/database/support/DataFieldMaxValueIncrementerFactory.html) that returns your custom incrementer and set the factory on the [JobRepositoryFactoryBean](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/repository/support/JobRepositoryFactoryBean.html#setIncrementerFactory-org.springframework.batch.item.database.support.DataFieldMaxValueIncrementerFactory-).
