### ISSUE TITLE
Spring Boot JPA Hibernate - Not storing Timestamp with millisecond precision

### ISSUE THREAD

**Issue by alexzh16** [spring-projects/spring-batch#3789]
Hi, i open in stackoverflow the this issue. I think its problem with jpa.

https://stackoverflow.com/questions/64262300/spring-boot-jpa-hibernate-storing-date-with-millisecond-precision

Spring Boot version '2.3.4.RELEASE'
Java 8 or 11

Server DB MariaDB (ver. 10.5.5-MariaDB)
Java MariaDB Connector J:2.6.0[stable]

My entity:

@Entity
@Data
@Table(name = "date_test")
public class DateTestDomain {
    @Id
    @Column(name = "timestamp", columnDefinition = "TIMESTAMP(3)")
    private Timestamp timestamp;

    @Column(name = "calendar", columnDefinition = "TIMESTAMP(3)")
    @org.hibernate.annotations.Type( type = "calendar" )
    private Calendar calendar;

    @Column(name = "calendar_t", columnDefinition = "TIMESTAMP(3)")
    @Temporal(TIMESTAMP)
    private Calendar calendarT;

    @Column(name = "localDateTime_a", columnDefinition = "TIMESTAMP(3)")
    private LocalDateTime localDateTimeA;
}

if i insert with jdbcTemplate to DB
`
long testTime = 1602120218454L;
Timestamp dateTimeStamp = new Timestamp(testTime);      
db.update("INSERT INTO date_test" + " (date) VALUES( \"" + dateTimeStamp + "\")");
`
As result i has 2020-10-08 03:23:38.454 . This good.

But with jpa.save:
`
Calendar calendar = Calendar.getInstance();
Date date = new Date();
calendar.setTimeInMillis(date.getTime());
dateTestDomain.setDateTest(calendar);
dateTestRepo.save(dateTestDomain);
`
result is - truncate millisend  2020-10-08 03:23:38.000.

with native sql the same:
`   
@Query(value = "INSERT INTO date_test (timestamp, calendar, calendar_t, local_date_time_a) VALUES (NOW(3), :startTime, :startTimeT, :startTimeA)", nativeQuery = true) 
void insertToDb(@Param("startTime") Timestamp startTime, @Param("startTimeT") Calendar startTimeT, @Param("startTimeA") Calendar startTimeA);
`
2020-10-10 16:20:47.888 | 2020-10-10 16:20:47.000 | 2020-10-10 16:20:47.000 | 2020-10-10 16:20:47.000 

The same with SELECT query:

Hibernate: select datetestdo0_.timestamp as timestam1_0_ from date_test datetestdo0_ where datetestdo0_.timestamp>?
binding parameter [1] as [TIMESTAMP] - [2020-10-10 16:20:47.893]

2020-10-10 16:20:47.888
2020-10-10 16:20:47.892
2020-10-10 16:20:47.896
2020-10-10 16:20:47.9

jdbcTemplate query:

select timestamp from date_test where timestamp>"2020-10-10 16:20:47.893"
2020-10-10 16:20:47.896
2020-10-10 16:20:47.900

if is save 

Maybe problem in another place as spring-jpa?

**Comment by benas** [comment]
I don't understand why this is opened here. There is no reference to Spring Batch in this issue and the SO question (which is not tagged with `spring-batch`) seems to be already answered.
