### ISSUE TITLE
After restarting a failed job using RunIdIncrementer, all subsequent job launches throw ClassCastException

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-batch#3799]
When using the RunIdIncrementer as an incrementer for a batch job, a user is unable to launch the batch job again with a new runId after restarting a previous job instance.    
The RunIdIncrementer throws a ClassCastException.

**Minimal Complete Reproducible example**
Using this Project https://github.com/cppwfs/runiddemo
1.  `java -jar target/batchdemo-0.0.1-SNAPSHOT.jar`
1. `java -jar target/batchdemo-0.0.1-SNAPSHOT.jar run.id=1`
1. `java -jar target/batchdemo-0.0.1-SNAPSHOT.jar`
Step 3 will exhibit the error.

**Comment by benas** [comment]
Thank you for opening this issue and for providing a minimal complete example.

If the `RunIdIncrementer`  was documented by stating that it expects the `run.id` parameter to be of type `Long` , I would consider step 2 as an incorrect usage (which should be `java -jar target/batchdemo-0.0.1-SNAPSHOT.jar run.id(long)=1`). But this is not the case, the `RunIdIncrementer`  does not specify the expected type of the parameter, so I consider this as a bug (Spring Batch shouldn't crash with a `ClassCastException`).
