### ISSUE TITLE
RetryException: Non-skippable exception in recoverer while processing

### ISSUE THREAD

**Issue by a18792721831** [spring-projects/spring-batch#3806]
**Bug description**

**Environment**
![image](https://user-images.githubusercontent.com/45473764/99872139-9b3a6780-2c1a-11eb-9edb-49d9155ad396.png)

**Steps to reproduce**
[study5-step.zip](https://github.com/spring-projects/spring-batch/files/5577287/study5-step.zip)
you need set your database.
and start main.
if you success,please try again and change job date parameter another value.
zip file is the gradle project.
job config is RetryJobConf.

**Expected behavior**
when i start,have a RetryException for LessZoreException(maybe equal zore).
but is set the step retry when LessZoreException.
![image](https://user-images.githubusercontent.com/45473764/99872213-2ae01600-2c1b-11eb-993d-9927346e7e25.png)

**Minimal Complete Reproducible example**
Please provide a failing unit test or a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
Reports that are reproducible will take priority over reports that are not reproducible.

**Comment by a18792721831** [comment]
spring boot version 2.3.5.RELEASE and 2.4.0 is the same.
LessZoreException is myself exception,and i config step use `.faultTolerant()` and `.retry(LessZoreException.class)` and `.retryLimit(10)`. spring batch will retry 10 times,if process throw excetion very time.

**Comment by a18792721831** [comment]
i get it.
![image](https://user-images.githubusercontent.com/45473764/99950989-56e4ce00-2db8-11eb-831b-cb22613ed038.png)
![image](https://user-images.githubusercontent.com/45473764/99951000-5ba98200-2db8-11eb-8d70-90c3c5a74d23.png)

**Comment by mohit816** [comment]
Any clue how can we resolve this exception
