### ISSUE TITLE
Referenced dependency (jackson-core-2.9.8.jar) is not available for unauthorized users

### ISSUE THREAD

**Issue by access-control-rtfm** [spring-projects/spring-batch#3808]
During the build process using gradle I get an error message:
\* What went wrong:
A problem occurred configuring root project 'spring-batch'.
\> Could not resolve all artifacts for configuration ':classpath'.
   \> Could not download jackson-core-2.9.8.jar (com.fasterxml.jackson.core:jackson-core:2.9.8)
      \> Could not get resource 'https://repo.spring.io/plugins-release/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar'.
        \> Could not GET 'https://repo.spring.io/plugins-release/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar'. Received status code 401 from server: Unauthorized

Using web search interface on https://repo.spring.io I could not find manually this dependency, only with the extension ".pom" (jackson-core-2.9.8.pom). Is something wrong with on the repo.spring.io website? Or the dependency referenced is wrong?

**Comment by access-control-rtfm** [comment]
Solved this issue by prepending mavenCentral() to repositories in the buildscript:

`
buildscript {
	repositories {
	        **mavenCentral()**
		maven { url 'https://repo.spring.io/plugins-release' }
		maven { url 'https://plugins.gradle.org/m2/' }
	}
	dependencies {
		classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.7'
		classpath 'io.spring.gradle:spring-io-plugin:0.0.5.RELEASE'
		classpath "io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE"
		classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.0"
	}
}
`

The rest of the build.gradle is the same as now

**Comment by benas** [comment]
Yes, this has been done in https://github.com/spring-projects/spring-batch/commit/e58ca37e1b4160db68f0186db37184638a04c8c3.

> Is something wrong with on the repo.spring.io website?

No, please refer to this blog post for more details: [Notice of Permissions Changes to repo.spring.io, Fall and Winter, 2020](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020)
