### ISSUE TITLE
Running a specific step in spring batch by passing particular step name in application arguments

### ISSUE THREAD

**Issue by ramsirish** [spring-projects/spring-batch#3817]
Hi Team,

Is there any way in spring batch if we can run a specific step by passing the step name in application arguments.
Our requirement is we have spring batch with11 steps where each of the step has different reader, processor and writer. If any of the step fails we will have to run the whole eleven steps again. Is there any thing in spring batch that we can invoke specific step from application arguments instead of running all the steps again?

**Comment by ramsirish** [comment]
@spring-issuemaster

**Comment by benas** [comment]
We prefer to use the issue tracker only for bug reports and feature requests. As mentioned in the [readme](https://github.com/spring-projects/spring-batch#getting-help), please ask your question on StackOverflow  and we would be happy to help.

**Comment by RitikDua3** [comment]
@ramsirish Did you get the solution regarding it?
