### ISSUE TITLE
Update build process to use Maven

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3820]
- [x] Configure `maven-compiler-plugin` to compile source code
- [x] Configure `maven-surefire-plugin` to run unit tests (`mvn test`)
- [x] Configure `maven-failsafe-plugin` to run integration tests (`mvn verify`)
- [x] Configure `maven-ant-plugin` to run the JSR TCK as part of maven's integration-test phase (no custom profile)
- [x] Configure `maven-javadoc-plugin` to generate javadocs (individual modules and aggregate docs)
- [x] Configure `maven-source-plugin` to generate source jars
- [x] Configure `asciidoctor-maven-plugin` to generate reference documentation in html/pdf
- [x] Configure `maven-assembly-plugin` to generate a single distribution of docs/schemas
- [x] Configure `jacoco-maven-plugin` to run test coverage and generate report (with a `test-coverage` profile)
- [x] Configure `maven-flatten-plugin` to optimize pom files before distribution
- [x] Configure `maven-gpg-plugin` to sign jars before distribution
- [x] Configure `maven-deploy-plugin` to deploy artifacts to artifactory
- [x] Add maven wrapper files
- [x] Update build process documentation

**Comment by benas** [comment]
Resolved with #3821 .

**Comment by maoshuai** [comment]
Why move back from Gradle to maven?

**Comment by benas** [comment]
Spring Batch used maven since its creation. Switching to gradle was an attempt to achieve consistency across the portfolio. Unfortunately, this consistency was not achieved, so we decided to go back to maven.
