### ISSUE TITLE
Remove usage of deprecated APIs

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3838]
The following APIs are deprecated but are still used in production/test code. The usage of these APIs should be updated with the suggested replacements in preparation for v5:

#### Production code

- [ ] `org.springframework.beans.factory.config.PropertyPlaceholderConfigurer`
- [x] `org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter`
- [x] `org.springframework.transaction.interceptor.TransactionInterceptor`
- [x] `org.springframework.transaction.support.TransactionSynchronizationAdapter`
- [x] `org.springframework.core.GenericTypeResolver#resolveParameterType`
- [x] `org.springframework.jdbc.core.JdbcOperations#query(java.lang.String, java.lang.Object[], org.springframework.jdbc.core.RowCallbackHandler)`
- [x] `org.springframework.jdbc.core.JdbcOperations#queryForObject(java.lang.String, java.lang.Object[], org.springframework.jdbc.core.RowMapper<T>)`
- [x] `org.springframework.jdbc.core.JdbcTemplate#query(java.lang.String, java.lang.Object[], org.springframework.jdbc.core.RowMapper<T>)`
- [x] `org.hibernate.Query`
- [x] `org.springframework.jdbc.support.JdbcUtils#extractDatabaseMetaData(javax.sql.DataSource, java.lang.String)`
- [x] `org.springframework.util.StringUtils#isEmpty`

#### Test code

- [x] `org.junit.rules.ExpectedException#none`
- [x] `org.junit.Assert#assertThat(T, org.hamcrest.Matcher<? super T>)`
- [x] `org.mockito.MockitoAnnotations#initMocks`
- [x] `org.mockito.Mockito#verifyZeroInteractions`
- [x] `org.mockito.Matchers`

**Comment by snate** [comment]
Hi @benas , I tried to implement some of the changes for the test code in a PR.
Could you please have a look? Would it be better to have all changes for the test code in that PR?

**Comment by benas** [comment]
Hi @snate , thank you for your PR! I will take a look asap. It's ok to have multiple PRs for this.
