### ISSUE TITLE
Support of spring-security, spring-cloud-sleuth and other frameworks contexts.

### ISSUE THREAD

**Issue by zahidMed** [spring-projects/spring-batch#3841]
Hi,

**Expected Behavior**

I would like to have the ability to run jobs using the same context for security, tracing (sleuth) and may be other frameworks. 
The context information can be passed as a job parameters and restored before the call of Job.execute(). So we need the possibility of injecting those parameters and restore them in a transparent way by:

- Having some kind of ParametersConverter or ParametersInterceptor that are called inside the JobLauncher in order to inject the values we need and if possible also before calling AbstractJob.execute() (two way conversion)
- Using the ParametersConverter just during the Job creation and having the possibility of configuring a global JobExecutionListener that allows to restore the context.

Regards.

**Comment by benas** [comment]
This is a duplicate of #1611 .

**Comment by zahidMed** [comment]
@benas this ticket is not only about spring security but also other frameworks such as sleuth. The ticket #1611 is focused only on the security asepect.

**Comment by benas** [comment]
What, specifically, do you mean by "support" spring-cloud-sleuth? (I will exclude "other frameworks" because I would like the discussion to be specific). Do you have a code example that shows what you are trying to achieve?

> The context information can be passed as a job parameters and restored before the call of Job.execute(). So we need the possibility of injecting those parameters and restore them in a transparent way

The context information is, as its name implies, a good candidate to be passed in the execution context and not passed as job parameters. Job parameters are typically used to identify job instances, not to pass (security/tracing) context information. So I believe the same arguments presented in #1611 apply here. You can use a job listener to populate/clear the context with any (security/tracing) attributes required by the job and use them as needed in your batch artifacts.

**Comment by zahidMed** [comment]
But how to set values inside the job execution Context when calling JobLauncher.run() ?

**Comment by benas** [comment]
For questions like this, please use stackoverflow and tag your question with `spring-batch` (see [Getting Help](https://github.com/spring-projects/spring-batch#getting-help)). But I will answer here with an example.

As mentioned previously, you can set any attribute in the job execution context using a listener and get access to it in your batch artifacts (tasklet, reader/writer, etc). Here is a quick example:

```java
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.core.listener.JobExecutionListenerSupport;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableBatchProcessing
public class MyJobConfig {

	@Bean
	public Job job(JobBuilderFactory jobs, StepBuilderFactory steps) {
		return jobs.get("job")
				.listener(new MyJobExecutionListener())
				.start(steps.get("step")
						.tasklet((contribution, chunkContext) -> {
							String suffix = (String) chunkContext.getStepContext().getJobExecutionContext().get("suffix");
							System.out.println("hello world" + suffix);
							return RepeatStatus.FINISHED;
						})
						.build())
				.build();
	}
	
	static class MyJobExecutionListener extends JobExecutionListenerSupport {
		@Override
		public void beforeJob(JobExecution jobExecution) {
			jobExecution.getExecutionContext().put("suffix", "!");
		}
	}

	public static void main(String[] args) throws Exception {
		ApplicationContext context = new AnnotationConfigApplicationContext(MyJobConfig.class);
		JobLauncher jobLauncher = context.getBean(JobLauncher.class);
		Job job = context.getBean(Job.class);
		jobLauncher.run(job, new JobParameters());
	}

}
```

This prints `hello world!`, which means the suffix (`!`) set in the execution context by the listener has been correctly read from the execution context in the tasklet.

If you need further support on this, please use stackoverflow.

**Comment by zahidMed** [comment]
@benas  Thanks for the example, The problem is that I neet to the security context of the user who called the method:
```java
jobLauncher.run(job, new JobParameters());
```
so if I do for example:
```java
class MyJobExecutionListener extends JobExecutionListenerSupport {
    @Override
    public void beforeJob(JobExecution jobExecution) {
         Authentication auth= SecurityContextHolder.getContext().getAuthentication(); // null value
    }
}
```
the value of auth will be null because the job is runing inside another thread:

```java
public class SimpleJobLauncher implements JobLauncher, InitializingBean {
    ...
    @Override
    public JobExecution run(final Job job, final JobParameters jobParameters){
         ....
	try {
	    taskExecutor.execute(new Runnable() {
                    @Override
                     public void run() {
                           ...
                     }
            }
            ...
```
So I am wandering if there is a way to put the auth value inside the context while calling jobLauncher.run() and before executing the jon in another thread.

**Comment by zahidMed** [comment]
hi @benas,
I have made a project that allows the propagation of security, sleuth, locale and MDC propagation through Spring batch Items. It doesn't cover all the batch aspects but at least it gives a nearby solution for what I need.

https://github.com/zahidMed/spring-batch-context

Regards.

**Comment by benas** [comment]
@zahidMed Thank you for sharing this project with us!

FTR, Spring Cloud Sleuth will add support to trace Spring Batch job executions, see https://github.com/spring-cloud/spring-cloud-sleuth/issues/1904.

**Comment by zahidMed** [comment]
@benas you're welcome. Can I contribute in this issue?

**Comment by benas** [comment]
Sure! There is an open PR here: https://github.com/spring-cloud/spring-cloud-sleuth/pull/1913. So feel free to join the discussion and share your thoughts with the Spring Cloud team.
