### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by jbotuck** [spring-projects/spring-batch#3842]
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/jbotu/IdeaProjects/spring-batch/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/annotation/DefaultBatchConfigurer.java:[18,24] package javax.annotation does not exist
[ERROR] /C:/Users/jbotu/IdeaProjects/spring-batch/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/annotation/DefaultBatchConfigurer.java:[94,10] cannot find symbol
  symbol:   class PostConstruct
  location: class org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spring Batch 5.0.0-SNAPSHOT:
[INFO]
[INFO] Spring Batch ....................................... FAILURE [  8.624 s]
[INFO] Spring Batch Infrastructure ........................ SKIPPED
```
Is it just me that has this issue?

**Comment by cppwfs** [comment]
I just did a build from the command line and it was successful using the instructions from the project README `./mvnw package`.   The CI Build is also showing success.   
This looks like an environment issue.   What java distribution are you using and what version?

**Comment by jbotuck** [comment]
my fault. I was using java 11 instead of 8

**Comment by benas** [comment]
@jbotuck Thank you for reporting this. I noticed this error yesterday on our CI [server](https://build.spring.io/browse/BATCH-JL-313/log) as well. This was due to an incorrect dependency scope when migrating the build to maven. The issue has been fixed and the build is now [successful on Java 11+](https://build.spring.io/browse/BATCH-JL-314).

@cppwfs Thank you for the follow up on this!
