### ISSUE TITLE
Regression in the "Configuring and Running a Job" section of the reference documentation

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3848]
The changes introduced in #620 are present in v4.2 but not in v4.3:

* 4.2.x: https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/job.html#javaConfig
* 4.3.x: https://docs.spring.io/spring-batch/docs/4.3.x/reference/html/job.html#javaConfig

This regression seems to be related to efdce562b0e71695221f6b165ab5979a9b6c3e66. @Buzzardo Could you please confirm that?

**Comment by Buzzardo** [comment]
I confirm. I'll get it fixed.

**Comment by benas** [comment]
Fixed in #3849 .
