### ISSUE TITLE
Intermittent failure in JsrPartitionHandlerTests.testPollingPartitionsCompletion on windows

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3850]
`JsrPartitionHandlerTests.testPollingPartitionsCompletion` fails  intermittently on windows with the following error:

```
java.lang.AssertionError
	at org.springframework.batch.core.jsr.partition.JsrPartitionHandlerTests.testPollingPartitionsCompletion(JsrPartitionHandlerTests.java:156)
```

That's all from the build log, no additional stacktrace from surefire's individual test report neither.

NB: the test fails only on the command line, it runs correctly from the IDE (tested with IntelliJ Idea).

**Comment by hpoettker** [comment]
I think this issue can be closed. The test has been removed in the course of #3894.

**Comment by hpoettker** [comment]
Thanks for quick reaction!

I stumbled upon this one as it was assigned to the upcoming release. I think there are some more issues in the general backlog that can be simply closed: https://github.com/spring-projects/spring-batch/labels/related-to%3A%20jsr-352
