### ISSUE TITLE
Could you please add java.sql.Timestamp to trusted classes in jackson2executioncontextstringserializer

### ISSUE THREAD

**Issue by karthikkesarla** [spring-projects/spring-batch#3855]
Even though you add trustedclassnames to Jackson2ExecutionContextStringSerializer ('java.sql.Timestamp'). It's agin overridden by basicbatchconfigurer.afterPropertieset() which will call initilize(). Which will again override serilizer with jackson2executioncontextstringserilizer (); in spring boot project. Because of which adding java.sql.Timestamp has no effect.

**Comment by benas** [comment]
> Could you please add java.sql.Timestamp to trusted classes in jackson2executioncontextstringserializer

This has been done in 1d23d66e27acc679319327150cffa38b9d3efc1b. FTR, I thought about taking the opportunity to add `java.sql.Time` as well but Jackson seems to be unable to deserialize its own serialized `java.sql.Time` instance with the default configuration. The following test fails:

```java
@Test
public void testJacksonTime() throws JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper();
    Time time = new Time(Instant.now().toEpochMilli());
    String serializedTime = objectMapper.writeValueAsString(time);
    Time deserializedTime = objectMapper.readValue(serializedTime, Time.class);
    Assert.assertEquals(time, deserializedTime);
}
```

while this one passes:

```java
@Test
public void testJacksonTimestamp() throws JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper();
    Timestamp timestamp = new Timestamp(Instant.now().toEpochMilli());
    String serializedTimestamp = objectMapper.writeValueAsString(timestamp);
    Timestamp deserializedTimestamp = objectMapper.readValue(serializedTimestamp, Timestamp.class);
    Assert.assertEquals(timestamp, deserializedTimestamp);
}
```

> Even though you add trustedclassnames to Jackson2ExecutionContextStringSerializer ('java.sql.Timestamp'). It's agin overridden by basicbatchconfigurer.afterPropertieset() which will call initilize(). Which will again override serilizer with jackson2executioncontextstringserilizer (); in spring boot project. Because of which adding java.sql.Timestamp has no effect.

This seems to be a valid point. Please open an issue against Spring Boot and provide a minimal example.
