### ISSUE TITLE
Spring Batch Restartibility not working for a cuncurrent setup

### ISSUE THREAD

**Issue by Jitu-Ranjan** [spring-projects/spring-batch#3882]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
Spring batch restart is not consistent for a concurrent chunk based setup. Where if failure happens for a chunk then the expected write count varies and same as reading count.

**Environment**
I am using the following setup:
1. Spring version: 4.2.5-RELEASE
2. JDK 1.8
3. Spring API used ItemStream implemented by Reader & Writer. Tried using Spring JobOperator.Launch passing last executed JobInstance which is unique given JobParameter passed is tagged to system time in Nano secs. ExecutionContext saved clearly saves read and write count but never starts from the same point. 

_{"@class":"java.util.HashMap","FlatFileItemWriter.current.count":["java.lang.Long",180],"com.asos.batch.step.items.BatchItemStreamReader.read.count":17,"FlatFileItemWriter.written":["java.lang.Long",8],"batch.taskletType":"org.springframework.batch.core.step.item.ChunkOrientedTasklet","batch.stepType":"org.springframework.batch.core.step.tasklet.TaskletStep"}_

**Steps to reproduce**
1. A job fails in mid way and execution context is saved around reading and write count. 
2. Following is the definition of Step and Job being used:

```
 public Step processItems(ItemStreamReader<?> reader, ItemProcessor<Object, Object> processor, ItemStreamWriter<Object> writer) {
        return stepBuilderFactory.get("processItems").<Object, Object>chunk(chunkSize).reader(reader).processor(processor).writer(writer).allowStartIfComplete(true).taskExecutor(taskExecutor()).build();

    }

// Job
jobBuilderFactory.get("job").start(processItems(read(), processor(processors), writer())).build();

// Task Executor
ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
        taskExecutor.setCorePoolSize(threadCount);
```
3. When chunk size is 100 and theadCount is 16.
4. This CSV content is processed and when a chunk brings item with failed field I fail the processor. Fix the processor and restart the app it never bring back the same write and read count. 

name,age,salary
peter,1,50000
failed,20,50000
john,2,50000
dave,3,50000
Martin,4,50000
Arun,5,50000
Raj,6,50000
Jeeva,7,50000
peter,9,50000
failed,20,50000
john,10,50000
dave,11,50000
Martin,12,50000
Arun,13,50000
Raj,14,50000
Jeeva,15,50000
Jai,16,50000
peter,17,50000
failed,20,50000
john,18,50000
dave,19,50000

DB snnipet showing step execution:

2021-04-12 11:35:38 | FAILED | 3 | 18 | 0 | 9
-- | -- | -- | -- | -- | --
2021-04-12 11:37:14 | COMPLETED | 5 | 4 | 0 | 4
2021-04-12 11:38:18 | COMPLETED | 5 | 22 | 0 | 22
2021-04-12 11:39:37 | COMPLETED | 5 | 20 | 0 | 20

**Expected behavior**
Expected behaviour is if the failure count is as follows:

1. Total read and write count is 22
2. Failure happens at read count of 18 and write count of 10, then restart should bring back the number to 22 as read and write.
![single-multithread-failure-pocessing](https://user-images.githubusercontent.com/27674141/114387692-a753a100-9b8a-11eb-924f-c89e1dc75480.PNG)

**Minimal Complete Reproducible example**
Please provide a failing unit test or a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
Reports that are reproducible will take priority over reports that are not reproducible.

**Comment by benas** [comment]
Thank you for opening this issue. Multi-threading is not compatible with restartability. This is because restart data (read count, write count, etc) that is saved in the execution context can be overridden by concurrent threads. The Javadocs of item readers and writers explicitly mention to turn off state management in concurrent steps. Here is an example from the [JdbcPagingItemReader](https://docs.spring.io/spring-batch/docs/4.3.x/api/org/springframework/batch/item/database/JdbcPagingItemReader.html):

```
The implementation is thread-safe in between calls to open(ExecutionContext), but remember
to use saveState=false if used in a multi-threaded client (no restart available).
```

This is explained in more details in the [Multi-threaded Step](https://docs.spring.io/spring-batch/docs/4.3.x/reference/html/scalability.html#multithreadedStep) section of the reference documentation.
