### ISSUE TITLE
Spring data jpa 2.x.x Repository methods not working with spring batch core 4.x.x (not saving/writing data to database)

### ISSUE THREAD

**Issue by alpizano** [spring-projects/spring-batch#3885]
Hi, I recently upgrade my Spring Java project which had spring-batch-core 3.0.10 , with spring-data-jpa 2.2.4 and spring-boot-starter-batch 2.2.4 ( which includes spring-batch-core 4.2.1.RELEASE). This is basically a Spring Boot/Batch/Web project.

I am using JpaRepository classes for my Repositories and I basically have a ArrayList of objects that I was calling the .save() method on. With the new spring-batch-core 4.x.x this threw an exception, so I had to change the method to .saveAll().

The problem is, when my Spring batch code gets to the Repository classes to SAVE this data to a database (using the .saveAll() method), nothing happens. The program continues running but nothing writes to Database. If I use the debugger, it just breaks out of the control flow once it hits any repository .save() method.

Am I doing something wrong here? I don't see any Bean errors, or anything noticeable, and I did find a stackoverflow post of someone facing something similiar:
https://stackoverflow.com/questions/38287298/persist-issue-with-a-spring-batch-itemwriter-using-a-jpa-repository

Please help!

**Comment by alpizano** [comment]
OK, so after debugging and stepping into the .save() calls from the JpaRepository, I can see there is some cyclical loop-infinite recursive method calls going-on in the JdkDynamicAopProxy.class and the SimpleJobLauncher.class

It's a pretty nasty chain and I'm not sure exactly what the hell is going on.... if anyone knows... please help

**Comment by benas** [comment]
> Please help!

We would love to help! However, we want to use the issue tracker only for bug reports and feature requests. For this kind of questions, please use StackOverflow as mentioned in the [README](https://github.com/spring-projects/spring-batch#getting-help). Thank you.
