### ISSUE TITLE
The new API java.time is way better than the old world with java.util.Date and java.util.Calendar

### ISSUE THREAD

**Issue by mohanaraosv** [spring-projects/spring-batch#3886]
In the existing implementation `JobExecution` and `StepExecution` we are still using the old API classes java.util.Date. 

It is preferred to use the new API  java.time, is it possible to switch new API or does it break backward compatibility?

**Comment by benas** [comment]
This has been discussed in #3723 . I'm closing it as duplicate, see Michael's comment [here](https://github.com/spring-projects/spring-batch/issues/3723#issuecomment-691107037).
