### ISSUE TITLE
Full MariaDB support

### ISSUE THREAD

**Issue by kevbrun** [spring-projects/spring-batch#3891]
Dear community

It would be nice if there would be a MariaDB support for Spring Batch. It doesn't seem to work in MySQL mode because of the primary keys. It is also not mentioned on the reference page  https://docs.spring.io/spring-batch/docs/4.3.x/reference/html/index-single.html which databases are supported.

Can you add the support or put specific information on the reference page?

Best regards
KB

**Comment by benas** [comment]
> It would be nice if there would be a MariaDB support for Spring Batch.

MariaDB is treated as MySQL, see 6c5476780e0ec95e5c54dad42fd1e9dfb0efd99f.

> It doesn't seem to work in MySQL mode because of the primary keys.

Can you please elaborate on that? Do you have an example that shows the issue?
