### ISSUE TITLE
Update graceful shutdown sample

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3901]
The sample [that shows graceful shutdown](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-samples/src/test/java/org/springframework/batch/sample/GracefulShutdownFunctionalTests.java) uses `JobExecution#stop` which has been deprecated in #1605 . This sample should be updated to use `JobOperator#stop`.

Related to #3663 .

**Comment by parikshitdutta** [comment]
Hi @benas, Please review PR #3916, I will look forward to your feedback.
