### ISSUE TITLE
Add default methods in interfaces

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3924]
Several core interfaces could benefit from using Java 8's default methods in interfaces feature. This has a couple of advantages:

* It makes client code more readable as it does not require it to implement all methods of a given interface.
* It reduces the code on the framework side since support classes (like `JobExecutionListenerSupport`, `StepExecutionListenerSupport`, `ChunkListenerSupport`, etc) become obsolete in favour of default methods.

This feature is similar to what has been done in other projects ([Here is an example](https://github.com/spring-projects/spring-framework/blob/main/spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationAdapter.java#L32-L33) from Spring Framework) and the goal is to make sure the Spring (Batch) developer has a consistent experience across the portfolio.

**Comment by parikshitdutta** [comment]
Hi @benas, I am on it, Please assign this one and it's dependent #3925 to me.

Thank you.

**Comment by parikshitdutta** [comment]
Hi @benas, please review PR #3934. I will look forward to your feedback.

Thank you.
