### ISSUE TITLE
Deprecate support classes implementing interfaces with default methods

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3925]
Support classes like `JobExecutionListenerSupport`, `StepExecutionListenerSupport`, `ChunkListenerSupport`, etc should be deprecated in favour of using the default methods in the interfaces they implement.

Depends on #3924 .

**Comment by parikshitdutta** [comment]
Hi @benas, please review PR #3935. I will look forward to your feedback.

Thank you.
