### ISSUE TITLE
Make RowMapper implementations of batch domain objects public

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3928]
Currently, as of v4.3.3, `RowMapper` implementations of batch domain objects (`JobInstance`, `JobExecution`, `StepExecution`, and `ExecutionContext`) are [private inner classes](https://github.com/spring-projects/spring-batch/blob/193f82005a373819e5921c7e2255607cf239d14e/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcJobExecutionDao.java#L400) in their respective JDBC DAOs.

These mappers can be made public so they can be (re)used in custom DAOs implementations.

**Comment by parikshitdutta** [comment]
Hi @benas, I am working on it. Please assign it to me.

Thank you.

**Comment by fmbenhassine** [comment]
After deeper look, it turns out that some mappers (step/job execution mappers) are created dynamically based on method parameters, like: https://github.com/spring-projects/spring-batch/blob/2e8d5063f7a68e45f25cd9aaf3e5075a6f250c30/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcStepExecutionDao.java#L325

So even if one provides a custom implementation, it won't be possible to use it unless going one level above and customize the DAO itself.
