### ISSUE TITLE
Add method getJobInstance in JobExplorer/JobRepository

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3930]
As of v4.3.3, there is no way to get a job instance for a given job name + job parameters with a `JobExplorer`/`JobRepository`. This issue is to add a method `getJobInstance(String jobName, JobParameters jobParameters)` in `JobRepository`/`JobExplorer`.

**Comment by parikshitdutta** [comment]
Hi @benas, I am on it, please assign it to me.

Thank you.

**Comment by parikshitdutta** [comment]
Hi @benas, Please review submitted PR #3932. I will look forward to your feedback.

Thank you.
