### ISSUE TITLE
ThrottleLimitResultQueue apparently dead code, could be removed

### ISSUE THREAD

**Issue by farnetto** [spring-projects/spring-batch#3949]
ThrottleLimitResultQueue appears to be an early draft of ResultHolderResultQueue, is apparently completely unused and could be removed to reduce the confusion surrounding multi-threaded step and TaskExecutorRepeatTemplate.

**Comment by benas** [comment]
Hi @farnetto ,

While this is true, it does not apply to all unused classes in the code base. Some classes are unused by production code but are provided as support for users, like `SystemCommandTasklet`, `CommandLineJobRunner`, etc.

That said, `ThrottleLimitResultQueue` is indeed unused and does not add any value compared to `ResultHolderResultQueue`. This class, as well as other unused classes from the `org.springframework.batch.repeat` package, will be revisited and deprecated as part of #2218. BTW, the entire concurrency model will be revisited as part of v5, I will open a separate issue to explain the reasons for that.

I'm closing this issue as superseded by #2218.
