### ISSUE TITLE
Add support for Java Date and Time API types serialization in Jackson2ExecutionContextStringSerializer

### ISSUE THREAD

**Issue by LichKing-lee** [spring-projects/spring-batch#3952]
**Expected Behavior**

Jackson2ExecutionContextStringSerializer should be serialized the java time packages(e.g `LocalDate`)

**Current Behavior**

Currently an exception is thrown

**Context**

cause: https://github.com/FasterXML/jackson-databind/issues/2683

can resolve by create custom object, but I think it's better to be provided by default.

**Comment by azatsh** [comment]
Is there any reason why it's not merged and so the issue is not resolved ?
I face the same error and was thinking just can upgrade Spring batch but I see it's not resolved even though the bug is opened since 2021.

**Comment by jcolladosp** [comment]
Hi,
is there any update on this?
