### ISSUE TITLE
Improve testability of SystemCommandTasklet

### ISSUE THREAD

**Issue by scordio** [spring-projects/spring-batch#3955]
Currently, the `SystemCommandTasklet` is not so test-friendly, mainly due to the usage of `Runtime.getRuntime().exec(...)`:

https://github.com/spring-projects/spring-batch/blob/6b4c91632195dff3a5ac6059c7c69ac1063fad60/spring-batch-core/src/main/java/org/springframework/batch/core/step/tasklet/SystemCommandTasklet.java#L103

For example, testing a job or a step with this tasklet defined does not work properly if the platform running the test does not have the target command available.

Would it make sense to decouple the `Runtime` dependency from this tasklet, so that a test can have more control over it? I would propose a pattern similar to the [SystemExiter](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/main/java/org/springframework/batch/core/launch/support/SystemExiter.java) and [JvmSystemExiter](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/main/java/org/springframework/batch/core/launch/support/JvmSystemExiter.java).

I am happy to submit a proposal in case the idea is accepted.

**Comment by benas** [comment]
Thank you for opening this feature request. This makes sense to me, something like `CommandRunner` and `JvmCommandRunner` could indeed decouple the command execution from the tasklet and make it possible to mock/stub the `CommandRunner` in tests. You are welcome to open a PR for that.

**Comment by scordio** [comment]
Thanks, @benas! I'll work on it.
