### ISSUE TITLE
Add item writer for Redis

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3957]
This issue is to add support to write data to Redis based on Spring Data Redis.

**Comment by santfirax** [comment]
Hello @benas, I would like to work on this. Any chance that you can provide some guidance ?

**Comment by benas** [comment]
@santfirax Thank you for your offer to help! The writer could be based on `KeyValueItemWriter` for consistency with other key/value writers. For the reader, I need some time to reflect on the best way to read data from Redis (ie make the reader use a [RedisTemplate](https://docs.spring.io/spring-data/redis/docs/2.5.2/reference/html/#redis:template) or a [Redis Repository](https://docs.spring.io/spring-data/redis/docs/2.5.2/reference/html/#redis.repositories)). But I'm open to ideas, so you are welcome to open a PR and we can discuss it there.

**Comment by santfirax** [comment]
Hello @benas I've created a PR for the write using RedisTemplate. https://github.com/spring-projects/spring-batch/pull/3961. Any chance that you can take a look at it ?

**Comment by MinJunKweon** [comment]
Hello, @benas. I have an idea about `RedisRepositoryItemReader` / `RedisRepositoryItemWriter`. They are based on [RedisRepository](https://docs.spring.io/spring-data/redis/docs/2.5.2/reference/html/#redis.repositories). So ItemReader can read data that saved by RedisRepository. And ItemWriter can write data through RedisRepository. I would like to open a PR for this. Is there anything I should know?

**Comment by seonwoo960000** [comment]
Hi, @fmbenhassine. I wonder if this issue is handled by anyone. If not, may I try on this issue?

**Comment by fmbenhassine** [comment]
This was resolved in 1bd0e0c. Thanks @santfirax for the PR!

For the item reader, please join the discussion in #4446.

**Comment by seonwoo960000** [comment]
@fmbenhassine Thank you! I'll join above discussion.
