### ISSUE TITLE
Revisit the default behaviour of job parameters conversion

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3960]
The current behaviour of the `DefaultJobParametersConverter` has been confusing in many situations:

* The way to specify parameter types with the `parameter(type)=value` notation is not friendly to command line arguments and environment variables
* The way to specify identifying / non identifying job parameters with `+`/`-` prefixes is not friendly with Spring Boot

While it is possible to provide a custom `JobParametersConverter` and set it on the `CommandLineJobRunner` or `JobOperator`, I believe the default behaviour should be reviewed for a better getting started experience for batch users and a better integration with Spring Boot. Since this could be a breaking change, I see v5 as a good opportunity to revisit this part of the framework.

References:

* https://stackoverflow.com/questions/66302293/spring-batch-job-param-always-show-zsh-no-matches-found
* https://github.com/spring-cloud/spring-cloud-dataflow/issues/4291
* https://github.com/spring-projects/spring-boot/issues/23411

Related issues:

* https://github.com/spring-projects/spring-batch/issues/1983
* https://github.com/spring-projects/spring-batch/issues/2122

**Comment by lcmarvin** [comment]
Any update on this, how to define the default parameter's format?

**Comment by lcmarvin** [comment]
@benas Is it possible to add a command line option like `-parameterFile` to specify the path of job parameters file? This file could be `.json`, `.properties` or `.ymal`. For example,
```json
[
    {
        "job":"fooJob",
        "parameters":[
            {
                "parameterName":"k1",
                "parameterType":"String",
                "paramter":"v1"
            },
            {
                "parameterName":"k2",
                "parameterType":"Long",
                "paramter":123,
                "identifying":true
            }
        ]
    }
]
```
```properties
spring.batch.job.parameters.fooJob[0].parameterName=k1
spring.batch.job.parameters.fooJob[0].parameterType=String
spring.batch.job.parameters.fooJob[0].parameter=v1
spring.batch.job.parameters.fooJob[1].parameterName=k2
spring.batch.job.parameters.fooJob[1].parameterType=Long
spring.batch.job.parameters.fooJob[1].parameter=123
spring.batch.job.parameters.fooJob[1].identifying=true
```
```yml
spring:
  batch:
    job:
      parameters:
        fooJob:
          - parameterName: k1
            parameterType: String
            parameter: v1
          - parameterName: k2
            parameterType: Long
            parameter: 123
            identifying: true
```

I think this format may be more friendly for Spring Boot users, compared with `parameter(type)=value` and `+/-`.

**Comment by fmbenhassine** [comment]
@lcmarvin Thank for your feedback and suggestion.

> Is it possible to add a command line option like -parameterFile to specify the path of job parameters file? This file could be .json, .properties or .ymal.

This could be a feature request for the `CommandLineJobRunner`. This issue is rather about the `DefaultJobParametersConverter`, for which the entry point is a `java.util.Properties` instance. You can open a new issue for your feature request and we can discuss it there.

The new notation has been implemented in #4204, which is explained in the [migration guide](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#default-job-parameter-conversion) and will be documented in `5.0.0-M7`.

**Comment by gulbrain** [comment]
FYI: The ERD at https://docs.spring.io/spring-batch/docs/current/reference/html/schema-appendix.html#metaDataSchema looks like it needs to be updated.

**Comment by fmbenhassine** [comment]
@gulbrain Thanks for reporting this. This will be addressed in #4358, which is planned for the upcoming v5.1.

**Comment by jvdlegaspi** [comment]
Hi, I keep on searching when does these properties was deprecated:
spring.batch.jdbc.initialize-schema
spring.batch.initializer.enabled

Any idea or references that I can check?

**Comment by micheljung** [comment]
@textfile123 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5.0-M2-Configuration-Changelog
