### ISSUE TITLE
NPE in JDBC ItemReaders after changes in spring-jdbc's AbstractFallbackSQLExceptionTranslator

### ISSUE THREAD

**Issue by unintended** [spring-projects/spring-batch#3968]
The spring-jdbc's SQLExceptionTranslator.translate() method is nullable (and was marked as nullable since 2017 https://github.com/spring-projects/spring-framework/commit/87598f48e41d483745aba56cbf4e998c6f6d680c)

However AbstractFallbackSQLExceptionTranslator that is used as base class  for all default spring-batch SQLExceptionTranslators become nullable (dirty move but quite legal) since May 2020 https://github.com/spring-projects/spring-framework/commit/e9cded560d6ecb73aa5bfca57e06b09fa0013294#diff-c6aa1c6a4b11e8a722808e945c4c5b6ef471c42871c7ce830554dde81ad7f2c2R66

However, all spring-batch readers rely on the non-nullability of the translators, e.g.:
https://github.com/spring-projects/spring-batch/blob/a0316379945a813b6516aaa37d110dc425693fed/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/JdbcCursorItemReader.java#L133

The NPE happens if some non-standard sql drivers are used/unexpected SQL code is returned and the default translators are not able to translate such SQLException properly.

**Expected behavior**
The proper way is to check if the translator returned null and throw something like UncategorizedSQLException in that case.

**Comment by benas** [comment]
Thank you for raising this issue and for opening a PR! Indeed, that change in SF could now result in a NPE on the batch side. I planned the fix for the upcoming v4.3.4.
