### ISSUE TITLE
Need to add doctype on second line + indentation

### ISSUE THREAD

**Issue by kimgysen** [spring-projects/spring-batch#3982]
**Expected Behavior**

I need to a custom line below the xml encoding / version header to define a custom doctype using StaxEventItemWriter. 

**Current Behavior**

I have no idea how to do it. When going through the source code, unless I'm missing it, it would appear that no flexibility is offered to add that extra line if needed. 

**Context**
My xml should look as follows: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BePostSubscriptionDistribution SYSTEM "..\BePostSubscriptionDistribution.dtd">
<BePostSubscriptionDistribution Identification="manualAddSubscription8.xml" TimeDateStamp="2021-06-14 22:00:01.320">
   <Editor Code="VSI"/>
   <AddMagazineSubscription>
      ...
   </AddMagazineSubscription>
</BePostSubscriptionDistribution>
```
The reason I need this is not in my hand, but at the request of the counterparty. 
If there is a workaround, please advise. 

The jaxb2marshaller allows to set properties, for example: 

	@Bean
	@Scope(SCOPE_PROTOTYPE)
	public Jaxb2Marshaller jaxb2Marshaller() {
		Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
		marshaller.setMarshallerProperties(getMarshallerProps());
		marshaller.setClassesToBeBound(AddSubscriptionXml.class, ModSubscriptionXml.class, DelSubscriptionXml.class);
		return marshaller;
	}

	private Map<String, Object> getMarshallerProps() {
		return new HashMap<>(){{
			put(Marshaller.JAXB_ENCODING, UTF_8.toString());
			put(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
			put("com.sun.xml.bind.xmlHeaders", "<!DOCTYPE BePostSubscriptionDistribution SYSTEM \"..\\BePostSubscriptionDistribution.dtd\">");
		}};
	}

But unless I missed it in the source code again, the marshaller only gets used to write the items, and ignores all the rest. 

![image](https://user-images.githubusercontent.com/4547364/131048307-1c1481b4-40fe-460c-89f2-b6913f999f33.png)

Also I noticed that in 2021, there still isn't a good solution for indentation, aside from following github issues like advised here: https://stackoverflow.com/questions/41566545/the-xml-output-from-the-spring-batch-jaxb2marshaller-marshaller-jaxb-formatted
I personally think that it is a bit weird that you have to follow github issues, download a library from an unknown source and write your custom implementation on top just to get your formatting. That's just imo.

**Comment by benas** [comment]
> Regarding the DocType definition, I can fix this by overriding startDocument and endDocument methods.

That's the way to go (see comments on the SO question linked above).
