### ISSUE TITLE
JdbcExecutionContextDao serializes as ISO-8859-1

### ISSUE THREAD

**Issue by marschall** [spring-projects/spring-batch#3983]
`JdbcExecutionContextDao` serializes as [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1)

https://github.com/spring-projects/spring-batch/blob/d0ab497312c0f08e096739dcb005a9487b4f1efc/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcExecutionContextDao.java#L77

This limits us to the ISO-8859-1 repertoire, even simple things like the Euro sign € are not supported. Honestly it is quite confusing that we convert through a binary encoding at all given that `JdbcExecutionContextDao` stores as `String`/`VARCHAR`/`CLOB`/....

This would be breaking change for anybody currently using non-ASCII ISO-8859-1 characters.

**Comment by benas** [comment]
This is a good candidate for v5. UTF-8 seems a reasonable default to me (similar to [JEP 400: UTF-8 by default](https://openjdk.java.net/jeps/400), even if this is for a different purpose). What do you think?

This might require increasing the current default value of `maxVarCharLength` in JobRepositoryFactoryBean and DDL scripts.

**Comment by marschall** [comment]
> This is a good candidate for v5. UTF-8 seems a reasonable default to me (similar to [JEP 400: UTF-8 by default](https://openjdk.java.net/jeps/400), even if this is for a different purpose). What do you think?

Yes, assuming we want to keep `ExecutionContextSerializer` `byte`-based (`InputStream`/`OutputStream`) and not switch it to `char`-based (`Reader`/`Writer`). If we switch them to be `char`-based we can get rid of the entire encoding.

Switching to UTF-8 likely will break code that uses `DefaultExecutionContextSerializer` as it is unlikely to produce valid UTF-8. We would have to change `DefaultExecutionContextSerializer` to produce Base64.

> This might require increasing the current default value of `maxVarCharLength` in JobRepositoryFactoryBean and DDL scripts.

We specify the length correctly in `char` and not `byte` therefore there should be no change needed.

**Comment by benas** [comment]
Switching to UTF-8 should also fix issues like https://github.com/spring-projects/spring-batch/issues/764.
