### ISSUE TITLE
Sorting in JdbcJobExecutionDao.GET_RUNNING_EXECUTIONS makes no sense

### ISSUE THREAD

**Issue by marschall** [spring-projects/spring-batch#3987]
`JdbcJobExecutionDao#GET_RUNNING_EXECUTIONS` currently has `order by E.JOB_EXECUTION_ID desc` however `JdbcJobExecutionDao#findRunningJobExecutions(String)` returns a `HashSet` therefore the iteration order is undefined. We should either

* remove the `order by`
* return a `TreeSet`

**Comment by benas** [comment]
Thank you for raising this. The contract of `JobExecutionDao#findRunningJobExecutions` does not specify the order in which running executions are returned (hence the `Set` return type). So clients should not be expecting any order or any sorted data structure. I think the `order by` clause is irrelevant here and could be removed.
