### ISSUE TITLE
One reader, multiple processors and writers

### ISSUE THREAD

**Issue by mcherb** [spring-projects/spring-batch#3992]
**Expected Behavior**

The idea is to allow one reader to be processed by one or multiple processors/writers like the following : 

```java
@Bean
public Step step() throws Exception {
    return stepBuilderFactory.get("step")
            .<A>chunk(1000)
            .reader(reader())
            .<A, B>unit()
              .processor(bProcessor())
              .writer(bWriter())
            .<A, A>unit()
              .writer(aWriter())
            .build();
}
```

**Context**

I'm facing almost the same issue like the one described in this [SO](https://stackoverflow.com/questions/18999724/spring-batch-one-reader-multiple-processors-and-writers) post. 

<pre>
                        item
                        +--->  ItemWriter#1
                        |
ItemReader --->  
                        |
                        +---> ItemProcessor#2 ---> ItemWriter#2
                        item
</pre>

I want to read from a database (using `JdbcPagingItemReader`) and use the same chunk to write first in another database table, and then transform the readed model to another POJO to fit an xml format and then use a `StaxEventItemWriter` to generate a xml file.

**Comment by javaHelper** [comment]
I think this is much needed functionality, any plan to make this available?

**Comment by mdanish98** [comment]
Any update on this?

**Comment by fmbenhassine** [comment]
Thank you for opening this issue.

This can be achieved with a combination of `ClassifierCompositeItemProcessor` and `ClassifierCompositeItemWriter` where items are transformed to either formats (DB or XML) before being written where appropriate based on their type/class.

You can also do that with a composite writer where the XML delegate does the needed transformation before writing items. A third way to address this (which I personally would opt for to keep things simple) is to create a custom writer which writes to the DB and XML with a transformation in between.

Ultimately you can achieve that by providing a custom `ChunkProcessor` and supplying it to a `ChunkOrientedTasklet`.   

There is no plan to change the DSL as suggested for that specific use case.

**Comment by legna-github** [comment]
A clasifier works as a XOR switch, you will either do thus or that but not both. 
My understanding of the question is one common reader, but two independent parallel process-writer paths

**Comment by fmbenhassine** [comment]
@legna-github 

> A clasifier works as a XOR switch, you will either do this or that but not both.

My bad, you are right. I seem to have misunderstood the question. In my previous comment, I gave multiple options. If it were up to me, I would keep things simple and implement a custom writer. Otherwise, a composite chunk processor with two chunk processors (ie processor + writer) is the way to go.

That said, there is no plan to change the DSL as suggested.
