### ISSUE TITLE
Is there any idea to support r2dbc in the future?

### ISSUE THREAD

**Issue by andochiwa** [spring-projects/spring-batch#3998]
Spring batch uses jdbc by default for logging. But when I use webflux and r2dbc it seems to be unable to perform database persistence. Is there a solution to support r2dbc in the future?

**Comment by javaHelper** [comment]
Is there any plan to take it forward?

**Comment by benas** [comment]
This is being discussed as part of #1008. The scope of reactive support is larger than jdbc vs r2dbc. Please share your thoughts in #1008 and follow the updates there.
