### ISSUE TITLE
Create table BATCH_JOB_EXECUTION throws SqlSyntaxErrorException with db2 v9

### ISSUE THREAD

**Issue by omheni** [spring-projects/spring-batch#4001]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
An exception thrown when running the **schema-db2.sql**  script, while creating BATCH_JOB_EXECUTION table ...

SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=,;N VARCHAR(2500) null;<references_spec>....

In fact JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL, cause a problem.
**Environment**
Please provide as many details as possible: Spring Batch version, Java version, which database you use if any, etc
java 11 
Spring Batch v4.3.1
DB2 v9.5.0.8

**Steps to reproduce**
Start a spring batch application that points the data source to a db2 database ...

**Expected behavior**
6 tables should be created : 

1. BATCH_STEP_EXECUTION_CONTEXT 
2. BATCH_JOB_EXECUTION_CONTEXT 
3. BATCH_STEP_EXECUTION
4. BATCH_JOB_EXECUTION_PARAMS
5.  BATCH_JOB_EXECUTION
6. BATCH_JOB_INSTANCE

**Minimal Complete Reproducible example**
Please provide a failing unit test or a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
Reports that are reproducible will take priority over reports that are not reproducible.

**Comment by benas** [comment]
Thank you for reporting this issue. There seems to be a difference in behaviour between DB2 versions with regard to nullable columns declaration. The [Db2JobRepositoryIntegrationTests](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/test/java/org/springframework/batch/core/test/repository/Db2JobRepositoryIntegrationTests.java) , which executes the `schema-db2.sql` script at startup, passes without the mentioned error against DB2 v11. Are you aware of such a difference or in which version this has changed?

I could not test the case against DB2 v9 as there is no public docker image for that, but a quick test that adds `DEFAULT NULL` to `JOB_CONFIGURATION_LOCATION` passes with v11. So I think there is no harm in updating the script as needed to make it work with v9.

**Comment by benas** [comment]
Resolved in 758372b025ddcad877b693b9193cd81a368b8ddd.
