### ISSUE TITLE
Exception message incorrect in arguments check

### ISSUE THREAD

**Issue by wokier** [spring-projects/spring-batch#4025]
The exception is thrown with a message containing `jobParameters` , which is not what is used in the if to do the check.

https://github.com/spring-projects/spring-batch/blob/d24eb6a6eda857c9a6123795c76b11264622894e/spring-batch-core/src/main/java/org/springframework/batch/core/repository/support/SimpleJobRepository.java#L140

Exists since 3.0.10.RELEASE at least.

**Comment by fmbenhassine** [comment]
Thank you for raising this. While this is valid from a "coding" point of view, the job parameters passed as a parameter to the `createJobExecution` method and those retrieved from the job execution should be same (modulo non-identifying parameters), unless we don't trust the implementation of `jobInstanceDao.getJobInstance(jobName, jobParameters);` and `execution.getJobParameters().getParameters()`.

So I would consider this as an improvement to make the exception's message more accurate (in case of a bug in the parameters retrieval).

**Comment by morenomjc** [comment]
Hi, is this open for contribution? And if just aligning the exception message with the if condition is enough.

**Comment by fmbenhassine** [comment]
@morenomjc Sure! Thank you for your offer to help.

Every issue without an already open PR or tagged with `status: for-internal-team` is open for contribution.

So you are welcome to contribute if you want.

**Comment by morenomjc** [comment]
Hi @fmbenhassine submitted a PR for this.
