### ISSUE TITLE
No pom.xml for published artifacts for 5.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-batch#4028]
I upgrade my Spring Batch dependencies to 5.0.0-SNAPSHOT however apparently there is no `pom.xml` published for these versions, leading to Gradle not being able to resolve them from the snapshot Spring repository. 

See: https://repo.spring.io/ui/native/snapshot/org/springframework/batch/spring-batch-core/5.0.0-SNAPSHOT for the published artifacts.

**Comment by benas** [comment]
Thank you for raising this. Looking into it.

**Comment by mdeinum** [comment]
Apparently the poms now get published (at least I do have some downloads and looking in the repositories shows for the last version that there is a .pom file available).

**Comment by benas** [comment]
Yes, an issue has been fixed in the deployment process. Thank you for raising this issue!
