### ISSUE TITLE
Add setter with a strongly typed parameter for the transaction isolation level

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#4032]
The `JobRepositoryFactoryBean` should provide a setter for the transaction isolation level with a strongly typed parameter like `org.springframework.transaction.annotation.Isolation`.

Related to https://github.com/spring-projects/spring-boot/issues/28802.

**Comment by wilkinsona** [comment]
I see you've removed the backport label, @benas. Sorry, I'm not familiar with your process here. Does that mean the change has now been backported or that you have changed your mind and it's now going to be a 5.0-only change?

**Comment by benas** [comment]
@wilkinsona The change seems incompatible with 4.3.x, so it's in 5.0 only for now.
