### ISSUE TITLE
Remove JUnit4 dependency from spring-batch-test

### ISSUE THREAD

**Issue by murdos** [spring-projects/spring-batch#4033]
**Expected Behavior**

spring-batch-test should not have dependency to JUnit4, or should have an optional dependency to JUnit4.

**Current Behavior**

spring-batch-test has a compile dependency to JUnit4.

**Context**

In a project using only JUnit5, JUnit4 is in the test classpath when using spring-batch-test.

**Comment by danilopiazza** [comment]
Hi, I opened pull request #4054 to address this issue.
