### ISSUE TITLE
Add Inbuilt reader to read response of REST API?

### ISSUE THREAD

**Issue by javaHelper** [spring-projects/spring-batch#4041]
I feel Spring Batch should provide in-built reader to read the REST API response - pagination if record count is huge and without pagination if record count is less. Spring Batch has many types of Item Readers and ItemWriters, so can we consider this as feature request?

**Comment by cppwfs** [comment]
Certainly.   We welcome all contributions from the community.

**Comment by benas** [comment]
This has been discussed in #896 . Please check Michael's comments about the rationale of why we did not include such a reader in the core framework.
