### ISSUE TITLE
Jobs fail when setting datasource auto-commit: false

### ISSUE THREAD

**Issue by tr325** [spring-projects/spring-batch#4051]
**Bug description**

Setting `spring.datasource.auto-commit: false` and `jpa.properties.hibernate.provider_disables_autocommit: true` results in the exception:

```
Exception in thread "pool-1-thread-1" org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
    at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:97)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:880)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:906)
    at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.synchronizeStatus(JdbcJobExecutionDao.java:307)
```

during batch job execution. This occurs when attempting to run any job during execution (the job starts correctly).

**Context**

We are attempting to configure our application to use multiple datasources as outlined in https://vladmihalcea.com/read-write-read-only-transaction-routing-spring/, to support separation of reader and writer databases for scaling purposes. To do this we need to disable auto-commit, as routing to the correct data source is achieved by the following code by extending `AbstractRoutingDataSource`:

```java
        if (TransactionSynchronizationManager.isCurrentTransactionReadOnly())
        {
            return DataSourceType.READ_ONLY;
        }
        return DataSourceType.READ_WRITE;
```
Setting `auto-commit: true` results in all transactions being read-write, and so only one datasource being used, thus we must change that.

However, the issue is reproducible using a single datasource - I include this context only to describe why we require the `auto-commit: false` setting.

**Environment**

Spring Boot v2.6.3, with Spring Batch and Spring Data
PostgreSQL v14.1

**Steps to reproduce**

Set `spring.datasource.auto-commit: false` and `jpa.properties.hibernate.provider_disables_autocommit: true` and run any Spring Batch job

**Expected behavior**

The job should complete correctly and not rely on auto-commit.

**Comment by cppwfs** [comment]
Hello @tr325 
Are you using the same data source for both reader, writer, and batch implementation?

**Comment by tr325** [comment]
Hi @cppwfs, thanks for the fast response!

The writer and batch implementation are using the same datasource, the reader is separate.

In this environment both datasources are pointing at the same underlying database, but connecting via separate postgres users. The user for the reader connection has no write access at the db level. In production they will point to separate instances.

**Comment by xamino** [comment]
I would like to add that we can reproduce the issue on the one "default" data source, so the multiple datasources are not necessarily required for this, they just highlight why we hit this issue. Any help much appreciated, maybe we missed configuring something easy?

**Comment by xamino** [comment]
@cppwfs Could we answer your question? :-)

**Comment by tr325** [comment]
Hi - just to say this was an issue at our end, apologies for the erroneous bug report! 

For anyone interested, the issue was that we had implemented a configuration class for Batch configuration, to ensure our transaction manager was compatible with Hibernate (the default is not). This looked like this:

```
/**
 * Spring Batch configuration to launch jobs asynchronously (default is synchronous).
 * Also configures the application-wide transaction manager.
 */
@Configuration
public class AsyncBatchConfiguration extends BasicBatchConfigurer
{

...

	/**
	 * Create a {@link JpaTransactionManager}, otherwise we would get a
	 * {@link org.springframework.jdbc.datasource.DataSourceTransactionManager} which is
	 * incompatible with Hibernate (e.g. it does not open transactions: we would never hit
	 * {@link org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor#begin()}).
	 */
	@Override
	protected PlatformTransactionManager createTransactionManager()
	{
		JpaTransactionManager transactionManager = new JpaTransactionManager();
		transactionManager.setJpaDialect(new HibernateJpaDialect());
		transactionManager.setEntityManagerFactory(entityManagerFactory);
		return transactionManager;
	}
}
```

This custom transaction manager we were providing relied on default values for the datasource, which wasn't picking up the `auto-commit: false` value from our `application.yaml`.  The fix was to inject the datasource into this class, and add

```
		transactionManager.setDataSource(dataSource);
```
