### ISSUE TITLE
[doc] Wrong size for BATCH_JOB_INSTANCE.JOB_KEY in Appendix A

### ISSUE THREAD

**Issue by rod2j** [spring-projects/spring-batch#4071]
It looks like the documented schema for table BATCH_JOB_INSTANCE in Appendix A - Meta-Data Schema doesn't match the actual schema for this table:

- Actual size of the JOB_KEY column is 32 (cf. [actual schema](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/main/resources/org/springframework/batch/core/schema-postgresql.sql)) but is documented as 2500

**Comment by benas** [comment]
Thank you for raising this issue and for opening a PR! Indeed there is a mismatch between the size in the actual schema and the docs. I will plan the fix for the next release.
