### ISSUE TITLE
Add Support for Azure Datalake ItemReader and ItemWriter into Spring Batch?

### ISSUE THREAD

**Issue by test512** [spring-projects/spring-batch#4074]

**Comment by javaHelper** [comment]
@benas - Is this plan in the next milestone? When can we expect it to be available? Actually looking same for the Azure DataBricks and CosmosDB.

**Comment by benas** [comment]
The is no plan to implement such a reader as Azure Datalake is not covered by [VMware Spring Runtime](https://spring.io/support). That said, you are welcome to contribute such a reader in the [spring-batch-extensions](https://github.com/spring-projects/spring-batch-extensions) repository.
