### ISSUE TITLE
Spring Batch JdbcBatchItemWriter afterPropertiesSet always call twice

### ISSUE THREAD

**Issue by owen6846** [spring-projects/spring-batch#4080]
Spring Batch JdbcBatchItemWriter afterPropertiesSet always call twice.

` @Autowired 
TestWriter write; 
  public Step startStep(StepBuilderFactory stepBuilders) {
          return stepBuilders.get("step")                
                  .listener(new StepResultListener())
                  .<Map, Map>chunk(chunkSize)
                  .reader(....)
                  .processor(....)
                  .writer(write)
                  .faultTolerant()
                  .build();
      }
`   
and TestWriter.java code is

`@Bean(name = "write") @StepScope  public JdbcBatchItemWriter<Map> write() {      .....
        JdbcBatchItemWriter<Map> itemWriter = new JdbcBatchItemWriter<>();        itemWriter.setDataSource(dataSource);
        itemWriter.setSql("insert into student (id,name) values (?,?) ");                ItemPreparedStatementSetter setter = new ItemPreparedStatementSetter() {            @Override            public void setValues(Object o, PreparedStatement preparedStatement) throws SQLException {                ......            }        };        itemWriter.setItemPreparedStatementSetter(setter);
        itemWriter.afterPropertiesSet();        return itemWriter;    }`

**Comment by benas** [comment]
This question has been answered on SO: https://stackoverflow.com/questions/71567176/spring-batch-jdbcbatchitemwriter-afterpropertiesset-repeat-trigger-twice. If you need further support, please add a comment on SO. Thank you.
