### ISSUE TITLE
Add FunctionalInterface annotation where appropriate

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4107]
Several interfaces (like `ItemReader`, `ItemProcessor`, etc) do qualify as functional interfaces. This issue is to add the `java.lang.FunctionalInterface` annotation where appropriate.

**Comment by amit-github-personal** [comment]
Hello @benas, can I submit a PR for this?

**Comment by benas** [comment]
Hi @amit-github-personal , thank you for your offer to help! There is already a PR for this issue: #4108 . If you want to help, you can for example review it and share your feedback if any. Thanks again.
