### ISSUE TITLE
Consider to add java.util.UUID as recognized class in Jackson2ExecutionContextStringSerializer

### ISSUE THREAD

**Issue by tombyong** [spring-projects/spring-batch#4110]
https://github.com/spring-projects/spring-batch/blob/5bce15288a0bd06a0d69c02ec3eaf1d432baddaa/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/Jackson2ExecutionContextStringSerializer.java#L259

Btw, it is quite painful to add the custom serializer into `JobRepositoryFactoryBean` and `JobExplorerFactoryBean`.
is there a better way just to make `Jackson2ExecutionContextStringSerializer`as a `@Bean`

**Comment by benas** [comment]
> Btw, it is quite painful to add the custom serializer into JobRepositoryFactoryBean and JobExplorerFactoryBean.
is there a better way just to make Jackson2ExecutionContextStringSerializeras a @Bean

This will be addressed in #3942 in which we have some options to simplify this. Please upvote the issue or add a comment if you have another suggestion. We are open to any improvement ideas.
