### ISSUE TITLE
Provide a callback after all chunks which could effect StepExecution's status if it fails

### ISSUE THREAD

**Issue by lcmarvin** [spring-projects/spring-batch#4116]
SpringBatch have many listeners we can use to do some callback, these listeners almost cover all the lifecycle of `JobExecution` and `StepExecution`. But I have a scenario like this: I have something to do after all chunks completed, and I hope that if it fails, the status of `StepExecution` could be FAILED, so I can re-run it later. I found `StepExecutionListener#afterStep` would be called after all chunks, but currently if it fails, we only log some messages, the status of `StepExecution` wouldn't be changed. 

So, would we provide a way to execute such callback? It is called after all chunks completed, and the `StepExecution` would fail if the callback fails.

Would this be an idea we can consider?

**Comment by fmbenhassine** [comment]
> I have a scenario like this: I have something to do after all chunks completed, and I hope that if it fails, the status of StepExecution could be FAILED, so I can re-run it later. I found StepExecutionListener#afterStep would be called after all chunks, but currently if it fails, we only log some messages, the status of StepExecution wouldn't be changed.

This can be done in `StepExecutionListener#afterStep`. as mentioned in the [Javadoc](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/StepExecutionListener.html#afterStep(org.springframework.batch.core.StepExecution)),  that method is not designed to throw exceptions, so it is up to you to handle exceptions and change the step exit status accordingly. That method is designed to give you a chance to change the step's status.

So I see no need to add new callback for this case. Do you agree?

**Comment by lcmarvin** [comment]
Yeah, I agree, 😄 thanks~
