### ISSUE TITLE
Rename SimpleJobLauncher to TaskExecutorJobLauncher 

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4123]
`SimpleJobLauncher` is not explicit about the infrastructure used to launch jobs. `TaskExecutorJobLauncher` is more explicit about that and is consistent with the naming used for other utilities like `TaskExecutorPartitionHandler` and `TaskExecutorRepeatTemplate`.

**Comment by lcmarvin** [comment]
Please refer to PR #4131
