### ISSUE TITLE
Add support for bulk inserts in MongoItemWriter

### ISSUE THREAD

**Issue by cgrings** [spring-projects/spring-batch#4149]
Currently there is support for the upsert and remove operations, I would like to suggest to add support for insert operation.

It would be nice to define an enum based set of operations (INSERT, UPSERT, REMOVE).

UPSERT will be the default operation (same behaviour as it is now) and the 'setDelete' method can be modified to set the REMOVE operation.

I am happy to submit a proposal in case the idea is accepted.

**Comment by fmbenhassine** [comment]
This is interesting! I guess it would improve the performance for use cases where we are sure we are inserting new documents. This will also be consistent with what we have in the `JpaItemWriter`: `merge` and `persist`.

You are welcome to open a PR! Thank you upfront.

**Comment by kgromov** [comment]
Hi, @fmbenhassine
I'm interested in this enhancement, when it supposed to be released?
