### ISSUE TITLE
Asciidoctor errors

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-batch#4168]
When the documentation generation process runs, it throws some errors: headings out of order in a few places and a few invalid references. The fix is to go through each of those files to correct the heading levels and track down the invalid references (and either correct them or remove them).

**Comment by Buzzardo** [comment]
You can assign this one to me.

**Comment by fmbenhassine** [comment]
@Buzzardo I think one of these errors is causing a regression on the code style toggle: 

* [4.3.8](https://docs.spring.io/spring-batch/docs/4.3.8/reference/html/job.html#configureJob): the toggle is present
* [5.0.1](https://docs.spring.io/spring-batch/docs/5.0.1/reference/html/job.html#configureJob): the toggle is absent

It seems the regression has been introduced in 5.0.0.

It would be great if we have an error/warning free build for the docs.

**Comment by fmbenhassine** [comment]
There are still a couple issues to resolve this issue:

- [x] Fix toggle (done, #4355)
- [ ] Fix invalid references
- [ ] Fix [build failure](https://github.com/spring-projects/spring-batch/blob/851bf706d84780e4cce9e034bd7cd0cc3c63d216/pom.xml#L134) with `asciidoctorj-pdf` 2.3.3
