### ISSUE TITLE
Incorrect reference to AbstractJobTests in documentation

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4182]
The [Testing Individual Steps](https://docs.spring.io/spring-batch/docs/current/reference/html/testing.html#testingIndividualSteps) section of the reference documentation refers to a non existent class `AbstractJobTests`:

```
[...]
The AbstractJobTests class contains a method called launchStep, which takes a step name and runs just that particular Step.
[...]
```

`AbstractJobTests` should be replaced with `JobLauncherTestUtils`.

**Comment by lixiangbetter** [comment]
If no one is in charge, i'd like to do it! This will be my first contribution for this project.
