### ISSUE TITLE
Spring Batch Test doesn't make migration by default

### ISSUE THREAD

**Issue by stillya** [spring-projects/spring-batch#4184]
**Bug description**
_I'm not sure if this bug or not implemented yet_
I have simple test for _job_ with _TestContainers_ and it's failed because _Spring Batch Test_ doesn't make migration by default. Workaround is to load `BatchAutoConfiguration` which have `datasourceInitializer`, _Spring Batch Test_ also have [`datasourceInitializer`](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-test/src/main/java/org/springframework/batch/test/DataSourceInitializer.java), as far as I understand, but it's weird, it's work only with _HSQLDB_ and I have to run it by hand.

**Environment**

- Java 17
- Spring Batch Test 4.3.6
- TestContainers 1.16.3
- PostgreSQL
 
**Expected behavior**
Spring Batch Test have to make migration by default no matter what base and make it on the start of the test.

**Minimal Complete Reproducible example**
I made [repository](https://github.com/stillya/spring-batch-test-migration-bug) with reproducible example, where you can find `ParquetToCsvJobBatchTest`. To make it green just uncomment one line with import configuration.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue.

> because Spring Batch Test doesn't make migration by default. 

What do you mean by that? Can you elaborate please?

> Spring Batch Test also have [datasourceInitializer](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-test/src/main/java/org/springframework/batch/test/DataSourceInitializer.java), as far as I understand, but it's weird, it's work only with HSQLDB and I have to run it by hand.

`DataSourceInitializer` is deprecated for removal, see https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#deprecated-apis. Please use similar utilities from `spring-jdbc`.

**Comment by stillya** [comment]
Thank you for response.
I mean that common `spring-batch` has [DatasourceInitializer](https://github.com/spring-projects/spring-boot/blob/b0b2818f0b03bc972fa91f91c1b8290987881811/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchAutoConfiguration.java#L151), but `spring-batch-test` doesn't(since he's deprecated) and because of that when you trying to run _job_ in test with `spring-batch-test` and `TestContainers` it's failed. You can check it by yourself in this [repository with reproducible example](https://github.com/stillya/spring-batch-test-migration-bug), just run test and you get error:
`PreparedStatementCallback; bad SQL grammar [SELECT JOB_INSTANCE_ID, JOB_NAME from BATCH_JOB_INSTANCE where JOB_NAME = ? and JOB_KEY = ?]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "batch_job_instance" does not exist`
But if you uncomment this [line](https://github.com/stillya/spring-batch-test-migration-bug/blob/cf7b89c147d7d03f31e16d8ed31cc0fb022cef98/src/test/java/dataflow/dataconverter/batch/ParquetToCsvJobBatchTest.java#L31) and load `DataSourceInitializer` from `BatchAutoConfiguration` it will pass

**Comment by fmbenhassine** [comment]
Thank you for your feedback. However, the code you are referring to is from Spring Boot, not Spring Batch. It seems that by "migration" you mean database migration (ie running the sql script to create batch tables at test initialization). Please note that Spring Batch does not create the tables, this is a feature from Spring Boot, not Spring Batch.

So please open this issue in Spring Boot if you want to suggest a feature or an improvement WRT TestContainers.

That said, we have some TestContainers based tests in Spring Batch, see example [here](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/test/java/org/springframework/batch/core/test/repository/PostgreSQLJobRepositoryIntegrationTests.java). I just wanted to share that with you in case it can help you in setting up your test.
