### ISSUE TITLE
Cosmos db support

### ISSUE THREAD

**Issue by nitin737** [spring-projects/spring-batch#4194]
Please do a quick search on Github issues first, the feature you are about to request might have already been requested.

**Expected Behavior**
Should connect to Cosmos db and fetch records for processing.

**Current Behavior**
Currently no support for Cosmos db

**Comment by fmbenhassine** [comment]
Are you looking for an item reader/writer for CosmosDB or for using CosmosDB as a job repository for meta-data?

**Comment by nitin737** [comment]
> Are you looking for an item reader/writer for CosmosDB or for using CosmosDB as a job repository for meta-data?

@fmbenhassine looking for reader/writer for CosmosDB

**Comment by fmbenhassine** [comment]
Thank you for your reply. CosmosDB is not officially supported by VMware (see [spring.io/support](https://spring.io/support)), so there is no plan to introduce official support for ComosDB in Spring Batch's main repository.

Please open this issue in https://github.com/spring-projects/spring-batch-extensions and we will consider accepting contributions from the community. You are welcome to do it if you want! Thank you.

**Comment by mhdali53** [comment]
spring batch reader for cosmos db. is it possible now?
