### ISSUE TITLE
graceful shutdown transaction error

### ISSUE THREAD

**Issue by be-93** [spring-projects/spring-batch#4198]
hello

I think the batch should be guaranteed to perform in case the server goes down, so I applied this server.graceful option.

But I am getting the transaction error intermittently.

![스크린샷 2022-09-25 오후 4 42 36](https://user-images.githubusercontent.com/36910795/192134181-3ef834c5-a447-40cb-a6c2-cf38d8c84956.png)

What is the best practice to deal with a server shutdown?? 😅

**Comment by fmbenhassine** [comment]
Thank you for raising this issue. Please post the full stack trace of the error to be sure that the code that tries to open a JPA entityManager after the graceful shutdown has been complete is from Spring Batch.

For this kind of issues, we expect a minimal complete example that we can unzip and run to reproduce the issue.

---

Related/Similar to:

* https://github.com/spring-projects/spring-batch/issues/1530
* https://github.com/spring-projects/spring-batch/issues/4023

References:

* https://stackoverflow.com/questions/68006888/spring-batch-doesnt-update-job-repository-after-force-termination/70182718#70182718
* https://stackoverflow.com/questions/66110545/stop-all-spring-batch-jobs-at-shutdown-ctrl-c

**Comment by fmbenhassine** [comment]
I am closing this issue for now. We will re-open it for further investigation if more details are provided.
