### ISSUE TITLE
A new job instance is always created after a failed run when using RunIdIncrementer and the same job parameters

### ISSUE THREAD

**Issue by ops841** [spring-projects/spring-batch#4212]
**Bug description**
A new job instance is always created after a failed run when using RunIdIncrementer and the same job parameters. 

**Environment**
Java 8
Spring Boot 2.7.4
Spring Batch 4.3.7

**Steps to reproduce**
Execute the main method provided in the program.
The log output shows:
Job execution starting: JobExecution: id=0
job=[JobInstance: id=0, version=0, Job=[job1]], jobParameters=[{run.id=1}]
Job execution starting: JobExecution: id=1
job=[JobInstance: id=1, version=0, Job=[job1]], jobParameters=[{run.id=2}]

**Expected behavior**
An old version of Spring Boot 1.3.3.RELEASE (Spring Batch 3.0.6.RELEASE) functions correctly.
The log output shows:
Job execution starting: JobExecution: id=0
job=[JobInstance: id=0, version=0, Job=[job1]], jobParameters=[{run.id=1, -spring.output.ansi.enabled=always}]
Job execution starting: JobExecution: id=1
job=[JobInstance: id=0, version=0, Job=[job1]], jobParameters=[{run.id=1, -spring.output.ansi.enabled=always}]

**Minimal Complete Reproducible example**
[code.txt](https://github.com/spring-projects/spring-batch/files/9805086/code.txt)

**Comment by ops841** [comment]
The issue is in JobLauncherApplicationRunner. In method getNextJobParameters the job repository is searched for an existing job instance having the same job parameters that were passed in the command line. However, when using "incrementer(new RunIdIncrementer())", an additional "run.id" parameter has been appended to the job parameters stored in the job respository. Therefore searching with command line arguments alone will not return a match. By manually adding "run.id=1" to the arguments for the second run in the submitted code, the last job instance is found. The JobLauncherApplicationRunner must be fixed to account for "run.id" parameter appended to the job parameters in the job repository.

[hack-to-show-desired outcome.txt](https://github.com/spring-projects/spring-batch/files/9812679/hack-to-show-desired.outcome.txt)

**Comment by fmbenhassine** [comment]
> The JobLauncherApplicationRunner must be fixed

Thank you for opening this issue. However, `JobLauncherApplicationRunner ` is a class from Spring Boot, not Spring Batch. Please open an issue in Spring Boot.
