### ISSUE TITLE
Use sequences of MariaDB, don't treat it as MySQL

### ISSUE THREAD

**Issue by JD-CSTx** [spring-projects/spring-batch#4217]
**Expected Behavior**
For MariaDB its, now for 4 years existing, native sequences get used, not the simulated sequences like MySQL needs them. This is a performance advantage of MariaDB against MySQL, since the code to simulate sequences isn't that simple. It would also be easier to maintain.
Link: https://mariadb.com/kb/en/sequence-overview/
Command to get next value: `NEXTVAL(sequence_name)`.

**Current Behavior**
Spring Batch uses MySQLs sequence simulation of the `MySQLMaxValueIncrementer`, whose core method is 80 lines long and all but simple. But it seems it could use something like the far slimmer `OracleSequenceMaxValueIncrementer`, whose core method is a primitive one-liner.

**Context**
Ignoring this feature of MariaDB is inefficient.

**Comment by fmbenhassine** [comment]
We had a discussion about this in https://github.com/spring-projects/spring-batch/issues/3891, which depends on https://github.com/spring-projects/spring-framework/issues/29306.

The addition of a dedicated incrementer for MariaDB in Spring Framework does not seem to be planned for SF 6, so I suggest we create one in Spring Batch (like we did for [SQLServer](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/support/SqlServerSequenceMaxValueIncrementer.java)) to implement this feature in SB 5, and then replace it with the one from SF when it is ready.

I will plan this for the upcoming 5.0 RC2.

**Comment by fmbenhassine** [comment]
@jhoeller That's a great news! Thank you. I will open a PR for it.
