### ISSUE TITLE
`JobRepository#getJobNames()` always returns empty list

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-batch#4229]
**Bug description**
`JobRepository#getJobNames()` is not implemented by the only implementation of the interface, `SimpleJobRepository`. The default method simply returns an empty list.
As of Spring Batch 5, this method is used by `JobRepositoryTestUtils.removeJobExecutions()`, which became a no-op method, never removing _any_ executions due to `getJobNames()` never returning any job names.

**Environment**
Spring Batch 5.0.0-RC2

**Steps to reproduce**
1. Run Job.
1. Call `JobRepository.getJobNames()`.

**Expected behavior**
Names of jobs are returned.

**Minimal Complete Reproducible example**
[demo1.zip](https://github.com/spring-projects/spring-batch/files/9993642/demo1.zip)
1. Unzip
1. Run `mvnw spring-boot:run`
1. The app runs a job named `job` and then queries both the `batch_job_instance` table and the `JobRepository` for all job names. The query returns `job` as expected, the `JobRepository` returns nothing.

**Comment by kzander91** [comment]
In fact, two other methods return empty lists as well due to not being implemented in `SimpleJobRepository`:
https://github.com/spring-projects/spring-batch/blob/420a7baa7511bcfeeefff95bf2be8c8ee692ee29/spring-batch-core/src/main/java/org/springframework/batch/core/repository/JobRepository.java#L72-L74
https://github.com/spring-projects/spring-batch/blob/420a7baa7511bcfeeefff95bf2be8c8ee692ee29/spring-batch-core/src/main/java/org/springframework/batch/core/repository/JobRepository.java#L83-L85

**Comment by fmbenhassine** [comment]
Good catch! I will plan the fix for 5.0 GA. Thank you for raising this 👍
