### ISSUE TITLE
Indent of Javadoc codes are mixed

### ISSUE THREAD

**Issue by acktsap** [spring-projects/spring-batch#4234]
![Screen Shot 2022-11-17 at 2 01 57](https://user-images.githubusercontent.com/24649991/202245419-ab65f7cd-7efb-4b7e-91da-2a871abe1a97.png)

![Screen Shot 2022-11-17 at 2 01 03](https://user-images.githubusercontent.com/24649991/202245249-6a99487a-a863-4d98-9a68-1134539f572d.png)

tab, 3-space, 4-space are mixed.

**Comment by fmbenhassine** [comment]
Resolved in #4235 .
