### ISSUE TITLE
#aot build crashes on 2nd job run

### ISSUE THREAD

**Issue by goafabric** [spring-projects/spring-batch#4239]
While Spring Batch AOT in Spring Boot 3.0 already works mostly fine,
there seems to be a small problem when a job is run for the 2nd time.
The deserialisation of the executioncontext crashes.
I already tried to set hints for java.util.hashmap .. but i guess the root cause is somewhere else.

Attached are the error and an example project that works in normal mode but crahses in AOT.

Could be that this is already fixed, but at least for me latest Spring Boot 3.0 RC2 + SNAPSHOT caused the error

[error.txt](https://github.com/spring-projects/spring-batch/files/10041995/error.txt)
[Archiv.zip](https://github.com/spring-projects/spring-batch/files/10041997/Archiv.zip)

**Comment by fmbenhassine** [comment]
Thank you for reporting this issue! Indeed, the second run fails when trying to deserialize the execution context.

I don't see what could be done on Spring Batch's side other than adding a serializtion hint for `HashMap` and other basic types that are required for the serialization/deserialization of the execution context to work out-of-the box.

FTR, I had to add a serilazation hint for `java.lang.Integer`, `java.lang.Number` and `java.lang.String` for the attached sample to work. I think basic Java types should be provided by default to avoid asking users to add them manually.

For custom user types however, I believe it is reasonable for now to ask users to hint them if necessary (unless there is a way to make Spring Batch infer them somehow and add hints for them on the fly, but I'm not sure if this is even possible).

#4239 partially resolves the issue. It will be merged and completed with other basic types as mentioned previously.
