### ISSUE TITLE
Headline in Spring Batch 5.0 Migration Guide contains typo

### ISSUE THREAD

**Issue by backpaper0** [spring-projects/spring-batch#4240]
**Bug description**

[Headline in Spring Batch 5.0 Migration Guide](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#infrastructure-beans-configuration-with-enablebatchbatchprocessing) contains typo.

- wrong: `@EnableBatchBatchProcessing`
- right: `@EnableBatchProcessing`

**Environment**
...

**Steps to reproduce**
...

**Expected behavior**
...

**Minimal Complete Reproducible example**
...

**Comment by fmbenhassine** [comment]
Fixed. Thank you for reporting this!
