### ISSUE TITLE
Request adding hint for ChunkOrientedTasklet

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-batch#4243]
User submitted a PR to Spring Cloud Task to add hint for `ChunkOrientedTasklet`.   However this hint is best implemented in the Spring Batch project.

**Comment by hpoettker** [comment]
@cppwfs Sorry for creating problems!

The hint is only needed for the `TaskBatchEventListenerBeanPostProcessor`. And I now realize that it is actually conditionally exposed by `BatchEventAutoConfiguration` only if `Job` is on the classpath as `spring-batch-core` is an optional dependency. Is that the source of the problem?

I think the right way to do it is to not use `aot.factories` as in https://github.com/spring-cloud/spring-cloud-task/pull/876 but to annotate `TaskBatchEventListenerBeanPostProcessor` with `@ImportRuntimeHints`. What do you think?

**Comment by cppwfs** [comment]
Thanks @hpoettker for digging in on this a bit more.   I agree with your solution, so we'll close this issue.
