### ISSUE TITLE
SimpleJobExplorer getJobExecutions returns job parameters of first job execution

### ISSUE THREAD

**Issue by hannosgit** [spring-projects/spring-batch#4246]
**Bug description**
The following method `List<JobExecution> getJobExecutions(JobInstance jobInstance)` in the `SimpleJobExplorer` class returns the wrong job parameters when a job instance is started multiple times with different job parameters (identifying job parameters are the same but the non-identifying parameters were  changed)

**Environment**
Versions:
* Spring Batch: 4.3.7
* Java: 17.0.3
* Database: Postgres

**Steps to reproduce**
* Define a job with identifying parameters and non-identifying parameters
* Launch a job and stop it
* Restart the job with the same identifying parameters but changed non-identifying parameters
* Fetch the job executions with `List<JobExecution> getJobExecutions(JobInstance jobInstance)`
* Returned job executions will have the same job parameters even though the second execution has changed non-identifying parameters

**Expected behavior**
Either document this behavior or change the implementation to fetch the job parameters of each job execution.

**Implementation hint**

I think this behavior is because the `JdbcJobExecutionDao` only fetches the job parameters once for a job instance and then reuses them for each job execution.
`JdbcJobExecutionDao`
```java
public List<JobExecution> findJobExecutions(final JobInstance job) {

Assert.notNull(job, "Job cannot be null.");
Assert.notNull(job.getId(), "Job Id cannot be null.");

return getJdbcTemplate().query(getQuery(FIND_JOB_EXECUTIONS), new JobExecutionRowMapper(job), job.getId());
}
```

A fixed version would fetch the job parameters for each execution because each job execution has its own job parameters, see `batch_job_execution_params` table.
This would impact the performance of the method, because more data would need to be fetched.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. We do not exclude that this could be a bug in Spring Batch. However, we would like to validate that with a minimal complete verifiable example.

Could you please take some time to create a minimal example that reproduces the problem? To help you in reporting your issue, we have prepared a project template that you can use as a starting point. Please check the [Issue Reporting Guidelines](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) for more details about this.

Thank you for your collaboration.

**Comment by hannosgit** [comment]
Hi,
you can find a minimal complete verifiable example here:
https://github.com/hannosgit/spring-batch-issue-4246
or
you can download the attached ZIP file.
[spring-batch-issue-4246.zip](https://github.com/spring-projects/spring-batch/files/11145407/spring-batch-issue-4246.zip)

Feel free to reach out to me, if you need more information!
Thank you!

**Comment by CNJingo** [comment]
Hi @fmbenhassine, I think I've found the cause. Is it okay if I try to contribute?

**Comment by fmbenhassine** [comment]
@CNJingo Sure! Thank you for your offer to help.

Any issue without an already open PR or tagged with `status: for-internal-team` is open for contribution. So you are welcome to contribute if you want.

FYI, we are planning to include this in v5.0.2 coming out on May 17th. Let me know if you need help on the fix.

**Comment by CNJingo** [comment]
@fmbenhassine Thank you so much for explaining the guidelines so well.

In fact, I've already created a PR. I would really appreciate it if you could review the PR.
