### ISSUE TITLE
Get Parameter from  JobSynchronizationManager  in partition step failed

### ISSUE THREAD

**Issue by domson-tech** [spring-projects/spring-batch#4247]
I want to get parameter from JobSynchronizationManager  in partition step,  but failed. Is it a bug?

**Comment by fmbenhassine** [comment]
Can you please elaborate on what you mean by "failed"? Do you fail to get the parameter (meaning a missing feature) or do you have an error? I'm not sure `JobSynchronizationManager` was designed to be used by end users and I fail to see a valid use case for its usage outside of the framework. What are you trying to achieve?

Please share an example of what you are trying to achieve and how it fails. It would be great if you follow the issue reporting template: https://github.com/spring-projects/spring-batch/blob/main/.github/ISSUE_TEMPLATE/bug_report.md. This will help us correctly debug the issue and validate it is a bug in Spring Batch.

Thank you upfront.

**Comment by fmbenhassine** [comment]
Closing this issue. We will re-open it for further investigation if more details are provided.
