### ISSUE TITLE
Job is not running automatically in v5

### ISSUE THREAD

**Issue by giuliana-bezerra** [spring-projects/spring-batch#4251]
**Bug description**
When running the Spring Boot project with a job configuration, the job is not executed as used to be in the previous version.

**Environment**
Spring Batch: 5.0
Java: OpenJDK Runtime Environment Temurin-17.0.4+8
Database: h2
SO: MacOS Ventura 13.0

**Steps to reproduce**

Run a Spring Boot Project with a job config file.

**Expected behavior**
In the previous version, Spring detects a job bean and execute it automatically. In this version it should be the same, I didn't found anything different in the migration instructions.

**Minimal Complete Reproducible example**
pom.xml:
```xml
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>3.0.0</version>
  <relativePath /> <!-- lookup parent from repository -->
</parent>
<properties>
  <java.version>17</java.version>
</properties>

<dependencies>
  <dependency>
	  <groupId>org.springframework.boot</groupId>
	  <artifactId>spring-boot-starter-batch</artifactId>
  </dependency>
  <dependency>
	  <groupId>org.springframework.boot</groupId>
	  <artifactId>spring-boot-starter-test</artifactId>
	  <scope>test</scope>
  </dependency>
  <dependency>
	  <groupId>org.springframework.batch</groupId>
	  <artifactId>spring-batch-test</artifactId>
	  <scope>test</scope>
  </dependency>
  
  <dependency>
	  <groupId>com.h2database</groupId>
	  <artifactId>h2</artifactId>
	  <scope>runtime</scope>
  </dependency>
 </dependencies>
```

Batch config:
```java
package br.com.giulianabezerra.springbatchv5;

import javax.sql.DataSource;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.jdbc.support.JdbcTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
@EnableBatchProcessing(dataSourceRef = "batchDataSource", transactionManagerRef = "batchTransactionManager")
public class BatchConfig {

  @Bean
  public DataSource batchDataSource() {
    return new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2)
        .addScript("/org/springframework/batch/core/schema-h2.sql")
        .generateUniqueName(true).build();
  }

  @Bean
  public JdbcTransactionManager batchTransactionManager(DataSource dataSource) {
    return new JdbcTransactionManager(dataSource);
  }

  @Bean
  public Job job(JobRepository jobRepository, JdbcTransactionManager transactionManager) {
    return new JobBuilder("job", jobRepository)
        .start(step(jobRepository, transactionManager))
        .build();
  }

  @Bean
  public Step step(JobRepository jobRepository, PlatformTransactionManager transactionManager) {
    return new StepBuilder("step", jobRepository)
        .tasklet((StepContribution contribution, ChunkContext chunkContext) -> {
          System.out.println("Hello, world!");
          return RepeatStatus.FINISHED;
        }, transactionManager)
        .build();
  }
}
```

Application:
```java
package br.com.giulianabezerra.springbatchv5;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringBatchV5Application {

	public static void main(String[] args) {
		SpringApplication.run(SpringBatchV5Application.class, args);
	}

}
```

Message printed in console:
```
2022-11-26T19:24:39.417-03:00  INFO 58403 --- [           main] b.c.g.s.SpringBatchV5Application         : Starting SpringBatchV5Application using Java 17.0.4 with PID 58403 (/Users/giulianabezerra/Downloads/spring-batch-v5/target/classes started by giulianabezerra in /Users/giulianabezerra/Downloads/spring-batch-v5)
2022-11-26T19:24:39.419-03:00  INFO 58403 --- [           main] b.c.g.s.SpringBatchV5Application         : No active profile set, falling back to 1 default profile: "default"
2022-11-26T19:24:39.637-03:00  INFO 58403 --- [           main] o.s.b.c.c.annotation.BatchRegistrar      : Finished Spring Batch infrastructure beans configuration in 3 ms.
2022-11-26T19:24:39.876-03:00  INFO 58403 --- [           main] o.s.j.d.e.EmbeddedDatabaseFactory        : Starting embedded database: url='jdbc:h2:mem:1a37c325-7c2e-4154-97d4-22499234978b;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false', username='sa'
2022-11-26T19:24:40.034-03:00  INFO 58403 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: H2
2022-11-26T19:24:40.063-03:00  INFO 58403 --- [           main] .c.a.BatchObservabilityBeanPostProcessor : No Micrometer observation registry found, defaulting to ObservationRegistry.NOOP
2022-11-26T19:24:40.066-03:00  INFO 58403 --- [           main] .c.a.BatchObservabilityBeanPostProcessor : No Micrometer observation registry found, defaulting to ObservationRegistry.NOOP
2022-11-26T19:24:40.069-03:00  INFO 58403 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2022-11-26T19:24:40.152-03:00  INFO 58403 --- [           main] b.c.g.s.SpringBatchV5Application         : Started SpringBatchV5Application in 0.973 seconds (process running for 1.248)
2022-11-26T19:24:40.158-03:00  INFO 58403 --- [ionShutdownHook] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:1a37c325-7c2e-4154-97d4-22499234978b;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
```

**Comment by hpoettker** [comment]
The automatic start of a job is a Spring Boot feature, not a Spring Batch feature. Please have a look at the [Spring Boot migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide) and also this comment: https://github.com/spring-projects/spring-batch/issues/4232#issuecomment-1315045542

Having said that, please note in particular that the effect of `@EnableBatchProcessing` in a Spring Boot app has changed with 3.0.0. It now disables the Spring Batch auto-configuration and the job starting behavior you're looking for.

You can also omit the explicit exposure of the `DataSource` and the `JdbcTransactionManager`. Spring Boot will take care of that for you.

**Comment by fmbenhassine** [comment]
@giuliana-bezerra  Thank you for opening this issue and for providing a minimal example.

As @hpoettker mentioned in the previous comment, the behaviour of `@EnableBatchProcessing` in Spring Boot has changed in v3, so please check the Boot's migration guide for how to upgrade your application to Spring Batch v5.

You should see your job running if your remove `@EnableBatchProcessing`. I'm closing this issue for now, but if you still need help to migrate your app to v5, please do not hesitate to add a comment here or open a new issue. Thank you.

@hpoettker Thank you for the follow up!

**Comment by atmel21** [comment]
Could you provide a sample if we would like to use @EnableBatchProcessing. How would the BatchConfig class in this example?

Context: I tried following the example in https://docs.spring.io/spring-batch/reference/job/running.html and I see all your examples are using @EnableBatchProcessing annotation. Thanks for your feedBack! Here is an example what I've done and couldn't figure out why the jobs won't start automatically ?


@Configuration
@EnableBatchProcessing(dataSourceRef = "batchDataSource", transactionManagerRef = "batchTransactionManager")
public class BatchConfig {

    @Bean
    public DataSource batchDataSource() {
        return new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2)
                .addScript("/org/springframework/batch/core/schema-h2.sql")
                .generateUniqueName(true).build();
    }

    @Bean
    public JdbcTransactionManager batchTransactionManager(DataSource dataSource) {
        return new JdbcTransactionManager(dataSource);
    }

    @Bean
    public Job job(JobRepository jobRepository, JdbcTransactionManager transactionManager) {
        return new JobBuilder("job", jobRepository)
                .start(step(jobRepository, transactionManager))
                .build();
    }

    @Bean
    public Step step(JobRepository jobRepository, PlatformTransactionManager transactionManager) {
        return new StepBuilder("step", jobRepository)
                .tasklet((StepContribution contribution, ChunkContext chunkContext) -> {
                    System.out.println("Hello, world!");
                    return RepeatStatus.FINISHED;
                }, transactionManager)
                .build();
    }
    @Bean
    public JobLauncher jobLauncher(JobRepository jobRepository) throws Exception {
        TaskExecutorJobLauncher jobLauncher = new TaskExecutorJobLauncher();
        jobLauncher.setJobRepository(jobRepository);
        jobLauncher.afterPropertiesSet();
        return jobLauncher;
    }
}

**Comment by clebemachado** [comment]
@atmel21 
Did your JobLauncher finish after completing the steps? Even though mine was "finished", the spring boot application continued to run.

**Comment by clebemachado** [comment]
```
I ended up managing to finish the JOB. I made the following adaptations:


My TaskExecutor change to ThreadPoolTaskExecutor 

@Bean(value = "threadPoolTaskExecutor")
  public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
      ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
      taskExecutor.setCorePoolSize(8);
      taskExecutor.setMaxPoolSize(16);
      taskExecutor.setQueueCapacity(8);
      taskExecutor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
      taskExecutor.setThreadNamePrefix("Async-");
      return taskExecutor;
  }

@Component
public class JobListener implements JobExecutionListener {

    @Autowired
    ThreadPoolTaskExecutor taskExecutor;

    @Override
    public void beforeJob(JobExecution jobExecution) {
        // Impedir que outros jobs rodem quando há instâncias com status STARTED
    }

    @Override
    public void afterJob(JobExecution jobExecution) {

        if(jobExecution.getStatus() == BatchStatus.COMPLETED) {
            System.out.println("!!! JOB FINISHED! Time to verify the results");
        }

        taskExecutor.shutdown();
    }
}

and add Listener in JobBuilder

@Bean
public Job createJob(
        JobRepository jobRepository,
        Step firstStep,
        JobListener jobListener
) {
    return new JobBuilder("sampleJob", jobRepository)
            .start(firstStep)
            .listener(jobListener)
            .build();
}

```
