### ISSUE TITLE
ArrayIndexOutOfBoundsException when invoke SimpleJobOperator.start in spring batch 5.0

### ISSUE THREAD

**Issue by leonchen83** [spring-projects/spring-batch#4253]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
ArrayIndexOutOfBoundsException when invoke SimpleJobOperator.start

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.springframework.batch.core.launch.support.SimpleJobOperator.start(SimpleJobOperator.java:327)
	at cn.nextop.gadget.batch.trigger.AbstractTrigger.fire(AbstractTrigger.java:119)
	at cn.nextop.gadget.batch.trigger.OnceTrigger.fire(OnceTrigger.java:22)
	at cn.nextop.gadget.batch.impl.DefaultTriggerScheduler$Task.run(DefaultTriggerScheduler.java:102)
	at cn.nextop.gadget.core.support.scheduler.impl.AbstractScheduler$RunnableJob.run(AbstractScheduler.java:204)
	at cn.nextop.gadget.timer.quartz.QuartzJobDetail$MethodInvokingStatefulJob.execute(QuartzJobDetail.java:79)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

```

**Environment**
spring batch 5.0
spring framework 6.0

**Steps to reproduce**
job parameters: `DATETIME=2022-11-30 11:47:20.909`

following code occur above error

SimpleJobOperator#L324
```
		if (!parameters.isEmpty()) {
			String[] keyValuePairs = parameters.split(" ");
			for (String string : keyValuePairs) {
				String[] keyValuePair = string.split("=");
				properties.setProperty(keyValuePair[0], keyValuePair[1]);
			}
		}
```

**Expected behavior**
No Exception

**Minimal Complete Reproducible example**
Please provide a failing unit test or a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by fmbenhassine** [comment]
This is a valid issue. Thank you for reporting it!

I planned the fix for the upcoming v5.0.1.

---

Related to #4301

**Comment by leonchen83** [comment]
@fmbenhassine 
We must consider how to decode escape character. why not use url way to decode parameter
for example
```
key=value&key1=value1
```

if above contains escape character. we can decode it like following

`k%3Dy=value&k%25y=value2` can parse to `["k=y", "value"]` and `["k%y", "value2"]`

**Comment by fmbenhassine** [comment]
I am not sure I fully understand why we need to do that. The goal here is to parse a set of key=value pairs separated with a new line character. Keys and values themselves are not parsed, they are passed verbatim to the list of job parameters.

Moreover, I see no point in passing a key like `k=y` (in `["k=y", "value"]`) or like `k%y` (in `["k%y", "value2"]`). If the default converter does not support those, the user can provide a custom converter.

**Comment by leonchen83** [comment]
User only can customize `JobParametersConverter ` but not `PropertiesConverter`

see `SimpleJobOperator #start`
```
Line318		Properties properties = PropertiesConverter.stringToProperties(parameters);
Line319		JobParameters jobParameters = jobParametersConverter.getJobParameters(properties);
```

I mean if we have a parameter like `["key", "val=ue"]`, the job parameter string should be `key=val=ue\n`, but `PropertiesConverter` can not parse it correctly. because we can't customize `PropertiesConverter`

**Comment by fmbenhassine** [comment]
Spring Batch is not and should not be concerned with string to properties conversion.
