### ISSUE TITLE
Invalid Postgresql migration script in 5.0

### ISSUE THREAD

**Issue by AMartel-fifteen** [spring-projects/spring-batch#4260]
**Bug description**
The Postgresql migration script to 5.0 contains invalid SQL. 

**Environment**
I faced a postgresql migration bug between spring batch 4.3.7 and 5.0.0. I needed to use liquibase to populate my database, only the liquibase user being able to alter the schema.

**Steps to reproduce**
- With spring-batch 4.3.7, make liquibase create the spring batch tables by referencing the postgresql sql file provided by spring-batch-core 4.3.7
- Update to spring-batch 5.0.0, make liquibase update the spring batch tables by referencing the postgresql 5.0 migration script.

**Expected behavior**
The schema migration is done without errors.

**Minimal Complete Reproducible example**
An explanation of the bug, an integration test, and a fix proposition are provided in this repository:
https://github.com/AlbericMartel/spring-batch-migration-4-to-5

**Comment by fmbenhassine** [comment]
Thank you for raising this! I will plan the fix for v5.0.1.

If you want to contribute the fix you suggest [here](https://github.com/AlbericMartel/spring-batch-migration-4-to-5/blob/main/src%2Ftest%2Fresources%2Fmigration-postgresql-4-to-5.sql), you are welcome to open a PR!

**Comment by AlbericMartel** [comment]
Here is the PR: https://github.com/spring-projects/spring-batch/pull/4279
