### ISSUE TITLE
Incorrect code samples in reference documentation

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4262]
For v5.0.0, most code samples were updated correctly in 219fee3bad403684485d60a1f4ae59e68bff5865, but some of them were updated incorrectly, like the following snippet:

```java
@Bean
public Step step1(JobRepository jobRepository, PlatformTransactionManager transactionManager) {
	return tnew StepBuilder("step1", jobRepository)
				.<String, String>chunk(10, transactionManager)
				.reader(itemReader())
				.writer(itemWriter())
				.build();
}
```

The fix consists in changing `tnew` with `new`. There are some occurrences in `job.adoc`, `common-patterns.adoc`, `processor.adoc` and `step.adoc`.

**Comment by Saravana-PS** [comment]
Hi @fmbenhassine, I would like to work on this issue. Could you please assign this to me?

**Comment by fmbenhassine** [comment]
@Saravana-PS Thank you for your offer to help! However, there is already a PR for this issue: https://github.com/spring-projects/spring-batch/pull/4283.

**Comment by Saravana-PS** [comment]
@fmbenhassine  Thanks for the details. Also, please let me know if you have any other good-first-issues that I can work on.
