### ISSUE TITLE
Not working batch.jdbc.initialize-schema: always with spring boot 3.0.0

### ISSUE THREAD

**Issue by vasilykabanov** [spring-projects/spring-batch#4273]
**Bug description**
When I set the parameter "batch:jdbc:initialize-schema:" to always, I expect the creation of meta tables with a description of the work of spring batch, but when switching to spring boot 3.0.0, the tables are not created, and the settings have not changed.

**Environment**
Spring Boot 3.0.0
Spring Batch 5.0.0
Postgres Database 42.3.4
jdk-18.0.1.1.jdk
macOS 13.0.1

**Steps to reproduce**
1. Clone project
2. Run docker compose file
3. Go to tree "spring-boot-v3"
4. Run application
5. Connect to DB and check 

**Expected behavior**
Waiting to create meta tables in my database

**Minimal Complete Reproducible example**
not working example - https://github.com/vasilykabanov/spring-batch-bug-reproducer/tree/spring-boot-v3
working example - https://github.com/vasilykabanov/spring-batch-bug-reproducer/tree/spring-boot-v2

**Comment by hpoettker** [comment]
Please try removing the annotation `@EnableBatchProcessing`. The issue #4252 contains more information on this.

**Comment by vasilykabanov** [comment]
@hpoettker Thanks for the tip! I close the issue
