### ISSUE TITLE
InMemory DB not initializing when using multiple data sources

### ISSUE THREAD

**Issue by jewolz** [spring-projects/spring-batch#4288]
**Bug description**
We were migrating our application to Spring Batch 5 and Spring Boot 3.0.1. However the table for the Batch metadata was not initialized.
We are using two separate data sources, one for business logic and an additonal in memory H2 datasource for the Spring Batch metadata. According to documentation @BatchDataSource annotation can be used, when the other datasource is marked as primary.
Additionally we were using @EnableBatchConfiguration to customize the JDBC-based Batch infrastrucuture beans. For initialization of the database the property `spring.batchjdbc.initialize-schema: embedded` is used. However when running an actual job the following error happens: 
`org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BATCH_JOB_INSTANCE" not found (this database is empty)
Table "BATCH_JOB_INSTANCE" not found (this database is empty); SQL statement:`
Only after implemention Bean BatchDataSourceScriptDatabaseInitializer did the initialization work.

**Environment**
Spring Batch 5
Spring Boot 3.0.1

**Expected behavior**
According to the documentation using @BatchDataSource and @EnableBatchConfiguration are the way to go with multiple datasources. Nowhere it is mentioned, that BatchDataSourceScriptDatabaseInitializer must be configured and in older versions before the migration @BatchDataSource and @EnableBatchConfiguration was sufficient. 
Is this a bug? If not it could be added to the migration guide as this is an unexpected behaviour.

**Minimal Complete Reproducible example**

```
@Configuration
@EnableBatchProcessing(
        dataSourceRef = "batchmetadata",
        transactionManagerRef = "batchmetadataTransactionManager",
        taskExecutorRef = "batchExecutor")
public class BatchConfiguration {

    @Bean
    public BatchDataSourceScriptDatabaseInitializer batchDataSourceScriptDatabaseInitializer(@Qualifier("batchmetadata") DataSource batchmetadata) {
        return new BatchDataSourceScriptDatabaseInitializer(batchmetadata, new BatchProperties.Jdbc());
    }
}
```
```
@Configuration
public class DatabaseConfiguration {

    @Bean(name = "ifxDataSourceProperties")
    @ConfigurationProperties(prefix = "spring.datasource.hikari")
    public DataSourceProperties ifxDataSourceProperties(){
        return new DataSourceProperties();
    }
    
    @Primary
    @Bean(name = {"dataSource", "ifxDataSource"})
    public DataSource dataSource() {
        return ifxDataSourceProperties()
                .initializeDataSourceBuilder()
                .type(HikariDataSource.class)
                .build();
    }

    @Bean
    @Primary
    public DataSourceTransactionManager dataSourceTransactionManager() {
        return new DataSourceTransactionManager(dataSource());
    }

    @Bean
    public TransactionTemplate transactionTemplate() {
        return new TransactionTemplate(dataSourceTransactionManager());
    }

    @Bean(name = "batchDataSourceProperties")
    @ConfigurationProperties(prefix = "spring.datasource.batchmetadata")
    public DataSourceProperties batchDataSourceProperties(){
        return new DataSourceProperties();
    }

    @BatchDataSource
    @Bean(name = {"batchmetadata"})
    public HikariDataSource batchmetadata() {
        return batchDataSourceProperties()
                .initializeDataSourceBuilder()
                .type(HikariDataSource.class)
                .build();
    }

    @Bean(name = {"batchmetadataTransactionManager"})
    public DataSourceTransactionManager batchmetadataTransactionManager() {
        return new DataSourceTransactionManager(batchmetadata());
    }
}
```

**Comment by fmbenhassine** [comment]
With Spring Boot 3, there is no need for `@EnableBatchProcessing`. If you add it, the auto-configuration of Spring Batch (meta-data tables creation, launching of jobs at startup, etc) will back off. This is mentioned in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-batch-changes) of Spring Boot 3.

Now if you want to use `EnableBatchProcessing`, you take full control of how Spring Batch is configured, and it is up to you initialize the datasource with batch tables. This is not related to the number of datasources defined in the application context.

If you remove `EnableBatchProcessing` and your batch datasource (the one annotated with `@BatchDataSource`) is still not initialized  even when you set `spring.batchjdbc.initialize-schema: embedded`, then please open an issue on the Boot side.

I am closing this issue for now, but if you need more support on the Spring Batch side, I would be happy to help.
