### ISSUE TITLE
Incorrect handling of default parameter type in JsonJobParametersConverter

### ISSUE THREAD

**Issue by miki1029** [spring-projects/spring-batch#4299]
**Bug description**
I am reporting a bug in the JsonJobParametersConverter class in the spring batch framework.

According to the [source code comments](https://github.com/spring-projects/spring-batch/blob/v5.0.0/spring-batch-core/src/main/java/org/springframework/batch/core/converter/JsonJobParametersConverter.java#L40), the type parameter in the extended notation of job parameters is optional. However, the [decode method](https://github.com/spring-projects/spring-batch/blob/v5.0.0/spring-batch-core/src/main/java/org/springframework/batch/core/converter/JsonJobParametersConverter.java#L99) in the JsonJobParametersConverter class throws a NullPointerException if the type parameter is not provided. This behavior goes against the documentation, as the default value of the type parameter should be String.

I would appreciate it if this issue could be addressed in a future release of spring batch.

Thank you for your attention to this matter.

**Environment**
* Spring Batch version : 5.0.0
* Java version : 17

**Steps to reproduce**
1. Use the JsonJobParametersConverter in a Spring Batch application.
2. Provide a value for the job parameter using the Extended notation without specifying a type.
3. Run the application and observe the NullPointerException that is thrown in the decode method.

**Expected behavior**
According to the documentation, the type variable is optional and should default to String if it is not provided. The application should run without encountering any errors.

**Minimal Complete Reproducible example**
```
param1='{"value":"value1"}'
```

**Comment by fmbenhassine** [comment]
This is a valid issue. Thank you for reporting it!

I will plan the fix for the upcoming patch release.

**Comment by guswns3371** [comment]
I had same issue with JsonJobParametersConverter when send parameters by `cli argument` or `SCDF`.
But i found a way through a lot of trial and error...

## cli argument

```
param1="{\"value\":\"value1\"}"
```
There should be no blank spaces between "key" and "value" like `param1="{\"value\": \"value1\"}"`.

## SCDF (task -> launch -> freetext)

```
param1={"value":"value1"}
```
There must be no single quotation marks `'`.
