### ISSUE TITLE
Implement equals and hashCode in Chunk class

### ISSUE THREAD

**Issue by jpraet** [spring-projects/spring-batch#4314]
See https://github.com/spring-projects/spring-batch/issues/4296. There is a problem with the PR https://github.com/spring-projects/spring-batch/pull/4300 that made it into 5.0.1:
it adds equals and hashCode to the ChunkIterator class instead of to the Chunk class.

**Comment by fmbenhassine** [comment]
Thank you for raising this! The PR was off-by-one brace and I missed that when reviewing it. My bad 🤦..

I will fix this in 5.0.2.

**Comment by CNJingo** [comment]
Sorry for my mistake.. I'll make sure to fix it.

**Comment by fmbenhassine** [comment]
This was resolved with #4317, but has exposed a seemingly old hidden bug as explained here: https://github.com/spring-projects/spring-batch/pull/4317#issuecomment-1543855211.

I created #4370 for that.
