### ISSUE TITLE
Add Teradata as DatabaseType

### ISSUE THREAD

**Issue by Garolla** [spring-projects/spring-batch#4315]
Please do a quick search on Github issues first, the feature you are about to request might have already been requested.

**Expected Behavior**
Teradata should be added in the enum of DatabaseType, as evidence that spring batch support it.

**Current Behavior**

At the time of writing Teradata is not in the DatabaseType enum

**Context**
I am trying to use spring batch to load a lot of data into a Teradata database

**Comment by fmbenhassine** [comment]
There is a difference between supporting a database as a repository for batch metadata and to read/write data from/to it.

You seem to be looking for an item reader/writer for Teradata. Is that correct? If that is the case, there is no need to modify the `DatabaseType` enum, you need to point your item reader/writer the Teradata datasource.

**Comment by Garolla** [comment]
It's correct, i need to read / write to teradata.
So you would say that spring batch supports Teradata, as per reading / writing data to it, but it doesn't support Teradata as a repository of batch metadata writing in it?

**Comment by fmbenhassine** [comment]
Yes. That's correct. You can define a JDBC datasource for your Teradata instance and point the item reader/writer to it.

I'm closing this issue for now, but if you still need help, you can add a comment here. Thank you.
