### ISSUE TITLE
Documentation should have correct classes for dates for all cases.

### ISSUE THREAD

**Issue by swapy** [spring-projects/spring-batch#4324]
I found small issue in documentation where we mention datetime with `java.util.Date` but in reality spring batch has moved to new java classes `java.time.LocalDateTime`. So this needs to be fixed in docs.

Places to change:
1. https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#jobexecution
- startTime
- endTime
- createTime
- lastUpdated

2. https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#stepexecution
- startTime
- endTime

**Comment by fmbenhassine** [comment]
Good catch! Thank you for raising this. Contributions are welcome.

**Comment by swapy** [comment]
Have created a pull request 
https://github.com/spring-projects/spring-batch/issues/4324
