### ISSUE TITLE
Improve the getting started experience with Spring Batch

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4329]
This is an epic issue that aims at improving the getting started experience with Spring Batch. Based on users feedback, the goal of this issue is to implement the following items:

- [x] Add a "Hello world" tutorial to the README
- [x] Update and improve the [getting started guide](https://spring.io/guides/gs/batch-processing/)
- [x] Update and improve the samples (#3663)
- [x] Improve the issue reporting process
- [x] Update the FAQ page (#3878)
- [x] Enable Github Discussions for Q/A and general discussions

**Comment by giuliana-bezerra** [comment]
The hello world tutorial is going to be with Spring Batch + Spring Boot? I think it would be useful because most people use Spring Boot + Spring Batch, and it would be good having an explanation about the new use of @EnableBatchProcessing.

**Comment by fmbenhassine** [comment]
@giuliana-bezerra 

> The hello world tutorial is going to have Spring Batch + Spring Boot?

No, the "Hello World" tutorial in the README is part of Spring Batch's documentation and will not be based on Spring Boot. 

> I think it would be useful because most people use Spring Boot + Spring Batch, and it would be good having an explanation about the new use of @EnableBatchProcessing.

The getting started guide is already based on Spring Boot (for consistency with other guides of the portfolio). We will add a mention about the new behaviour of `@EnableBatchProcessing` once we update it.
