### ISSUE TITLE
Doc issue: ambiguous description of Configuring a JobRepository

### ISSUE THREAD

**Issue by LiuYi98** [spring-projects/spring-batch#4333]
**Bug description**

The description of required configuration options of Configuring a JobRepository [in this chapter](https://docs.spring.io/spring-batch/docs/current/reference/html/job.html#configuringJobRepository) is ambiguous. We don't know whether `id` is required or `dataSource` and `transactionManager` are required.

![image](https://user-images.githubusercontent.com/26665428/227237118-333993cb-51ed-4ab8-86ca-71af2fba7c90.png)

**Comment by fmbenhassine** [comment]
Thank you for reporting this issue. It seems you have selected "Both" in the toggle of Java/XML configuration styles at the top of the page. When "Both" is selected, the text is indeed confusing (in this section and in other sections as well).

For this reason, the option "Both" was removed in the new documentation: https://docs.spring.io/spring-batch/reference/job/configuring-repository.html .The toggle is now next to each example, and the confusing "Both" option was removed. That said, the content of the Java sample needs to be updated to be equivalent to the XML one.

**Comment by LiuYi98** [comment]
It's not ambiguous now, thanks for your work.
