### ISSUE TITLE
[Question] Any way to set decider first?

### ISSUE THREAD

**Issue by acktsap** [spring-projects/spring-batch#4350]
In xml based job configuration, we can set decider first like this.

```xml
<job id="decisionJob1" >
    <decision id="decider1" decider="stepFlowDecider">
        <end on="EXIT" exit-code="COMPLETED"/>
        <next on="*" to="job1Step1" />
    </decision>

    <step id="job1Step1">
        <tasklet ref="createFileTasklet"/>
    </step>
</job>
```

But when using code based job configuration, no way to start with decider. `JobBuilder` only provides start methods taking `Step`, `Flow` only.

https://github.com/spring-projects/spring-batch/blob/972951a40af03c9c0553fb4c438f9aaeb1c9f1b5/spring-batch-core/src/main/java/org/springframework/batch/core/job/builder/JobBuilder.java#L53-L78

It there any way to set decider first on code based job configuration?

**Comment by CNJingo** [comment]
If you use SimpleJobBuilder instead of JobBuilder, you can create a JobFlowBuilder that starts with a decider.

This is an example.

```
		JobExecutionDecider decider = new JobExecutionDecider() {
			private int count = 0;

			@Override
			public FlowExecutionStatus decide(JobExecution jobExecution, @Nullable StepExecution stepExecution) {
				count++;
				return count < 2 ? new FlowExecutionStatus("ONGOING") : FlowExecutionStatus.COMPLETED;
			}
		};
		JobFlowBuilder builder = new SimpleJobBuilder(new JobBuilder("flow", jobRepository)).start(decider);
```

I hope this example works for you.

**Comment by fmbenhassine** [comment]
For questions and support requests, we started using GitHub discussions, see [Getting Help](https://github.com/spring-projects/spring-batch#getting-help). Therefore, I am moving this to a discussion. We will change it to an issue if we validate a bug or a missing feature.
