### ISSUE TITLE
Property 'table_prefix' does not working when initializing database  for batch meta-data tables

### ISSUE THREAD

**Issue by LamTong** [spring-projects/spring-batch#4354]
**Bug description**
> Property `spring.batch.jdbc.table_prefix` of **Spring Batch** does not working when initializing database for batch meta-data tables.

**Environment**
| Environment |  |
| --- | --- |
| JDK | 1.8 |
| MySQL | 8 |
| Docker | true |
| Spring Boot version | 2.7.10 |
| Spring Batch version | 2.7.10 |
| OS | Ubuntu 22.04 LTS |

**Steps to reproduce**
> 1. Initializes a **Spring Boot** project.
> 2. Adds dependencies. For example, `spring-boot-starter-web`, `spring-boot-starter-batch` and `mysql-connector-java`.
> 3. Configures a batch job. For example, extracts data from a `.csv` file, located in folder `resources`, into database.
> 4. Configures **Spring Boot** project's properties, and customs `spring.batch.jdbc.table_prefix` like `BATCH_SAMPLE_`.
> 5. Starts **Spring Boot** application to execute configured batch job.

**Expected behavior**
**Spring Batch** will execute batch job, extracting data from `.csv` file into database, while reporting exception like
> Caused by: java.sql.SQLSyntaxErrorException: Table 'batch.BATCH_SAMPLE_JOB_INSTANCE' doesn't exist
>	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
>	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
>	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.30.jar:8.0.30]
>	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[mysql-connector-java-8.0.30.jar:8.0.30]
>	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-4.0.3.jar:na]
>	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
>	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722) ~[spring-jdbc-5.3.26.jar:5.3.26]
>	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.26.jar:5.3.26]
>	... 42 common frames omitted

It seems that `table_prefix` property works when querying meta-data tables. 
However, batch meta-data tables initialized by `/org/springframework/batch/core/schema-mysql.sql` does not take place the prefiex of each table respectively with default prefiex `BATCH_` rather custom table prefix `BATCH_SAMPLE_`.

**Comment by fmbenhassine** [comment]
Spring Batch does not initialize tables, this is a feature of Spring Boot. Please open this issue against Spring Boot's issue tracker. Do not hesitate to cc me if you need help on the Batch side. Thank you.

**Comment by rjtmahinay** [comment]
@fmbenhassine @LamTong As per my understanding this behavior can now be override using

`@EnableBatchProcessing(tablePrefix = "...")`

Can you confirm?

**Comment by fmbenhassine** [comment]
@rjtmahinay Yes, but remember, using `@EnableBatchProcessing` with Spring Boot 3.0+ does not trigger the auto-configuration of Spring Batch.
