### ISSUE TITLE
Disable Docker-based tests when Docker is not available

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4360]
Currently, a full build runs Docker-based (TestContainers) integration tests no matter if Docker is available on the platform or not. This leads to a build failure when Docker is not available. This behaviour can be improved by disabling Docker-based tests when Docker is not available.

The TestContainers library provides the attribute `@TestContainers(disabledWithoutDocker = true)` for that case. The goal of this issue is to add that attribute to all tests annotated with `@TestContainers`.

Contributions are welcome!

**Comment by CNJingo** [comment]
I'd like to try it.

**Comment by sukanth** [comment]
@fmbenhassine  can you assign this to me ? i can take this one

**Comment by sukanth** [comment]
@fmbenhassine  Thank you for assigning it to me . here is the PR https://github.com/spring-projects/spring-batch/pull/4367
