### ISSUE TITLE
Add synchronized decorators for non-stream item readers/writers

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4368]
Currently, Spring Batch provides two decorators (`SynchronizedItemStreamReader` and `SynchronizedItemStreamWriter`) to synchronize thread access to `ItemStreamReader#read` and `ItemStreamWriter#write`.

While those decorators work with `ItemStream`s, they are not usable with non item streams as they respectively accept `ItemStreamReader` and `ItemStreamWriter` as delegates. For example, those decorators cannot be used to synchronize access to `ListItemReader#read` (#3741) or`KafkaItemWriter#write` (#3970).

The goal of this issue is to add two decorators that accept `ItemReader` and `ItemWriter` as delegates and synchronize access to the `read` and `write` operations.

**Comment by hpoettker** [comment]
Are there already plans for the API to instantiate `SynchronizedItemReader` or `SynchronizedItemWriter`?

It should be consistent with the corresponding decorators for `ItemStream`, which can be instantiated with a no-args-constructor and a setter for the delegate, or a builder with a more fluent API. But in my opinion, both options feel a bit clunky today. Are there plans to allow more concise instanstiations like `SynchronizedItemReader.of(delegate)` or `new SynchronizedItemReader(delegate)`?

**Comment by fmbenhassine** [comment]
@hpoettker 

> Are there plans to allow more concise instanstiations like SynchronizedItemReader.of(delegate) or new SynchronizedItemReader(delegate)?

Yes, there will be a constructor that accepts the delegate.
