### ISSUE TITLE
Consistent Support Period across Spring, Spring Batch and Spring Boot

### ISSUE THREAD

**Issue by DhavalShewale** [spring-projects/spring-batch#4375]
Hi Team,

Can we pls have a consistent support period across Spring, Spring Batch and Spring Boot libraries.

Currently, spring libraries are marked EOL roughly after 24 months, spring batch is marked EOL roughly after 18 months and spring boot is marked EOL after 12 months.

As all libraries are dependent on each other, plus as there can be applications using different flavors of the library its difficult to plan periodic updates.

Can we pls have a uniform EOL support policy for all flavors of spring - Spring, Spring Batch, Spring Boot, Spring Cloud, etc. The support policy should align to the baseline framework i.e. Spring and we should support all flavors for upto 24 months.

Regards,
Dhaval

**Comment by fmbenhassine** [comment]
Thank you for raising your concern. A Spring Batch release is supported as long as the _last_ Spring Boot version that brings it is supported. This is mentioned in the [Support Policy](https://github.com/spring-projects/spring-batch/wiki/Support-Policy) page.

Currently, Spring Batch 4.3.x is brought by Spring Boot 2.7.x. Both lines have the same OSS/Commercial EOL dates [1][2]:

* OSS EOL: `2023-11-18`
* Commercial EOL: `2025-02-18`

Spring Batch 5.0.x is currently supported through Spring Boot 3.0.x and will also be brought by Spring Boot 3.1.x. Therefore, it will be supported as long as Spring Boot 3.1.x is supported. EOL dates also align for these lines as well [1][2].

Support periods may vary between projects, but the policy for Spring Batch is as mentioned above (which is basically the same as Spring Boot). Does this clarify your concern?

---

1. https://spring.io/projects/spring-batch#support
2. https://spring.io/projects/spring-boot#support

**Comment by snicoll** [comment]
@fmbenhassine the OP has asked the same question in three different locations already.

**Comment by fmbenhassine** [comment]
Thank you @snicoll . I am closing this issue.
