### ISSUE TITLE
Disabling metadata tables in Spring Batch 5

### ISSUE THREAD

**Issue by alexanderpkelly** [spring-projects/spring-batch#4383]
In previous versions of Spring Batch my team disabled metadata database creation by specifying an empty DataSource (via a no-op override of [DefaultBatchConfigurer](https://docs.spring.io/spring-batch/docs/5.0.0-M3/api/org/springframework/batch/core/configuration/annotation/DefaultBatchConfigurer.html#setDataSource(javax.sql.DataSource))'s setDataSource method). This forced the job to use a Map-based JobRepository and prevented Spring Batch from trying to create metadata tables on the Db2 database my job interacts with for it's business purposes.

This approach was deprecated and has been completely removed in Spring Batch 5. This is a conundrum for us, because Spring Batch cannot actually create these metadata tables on our Db2 data source (nor do we want it to). I can't seem to find a way to disable this functionality, which seems like it really ought to have a straightforward means of opting out of ( `spring.batch.jdbc.initialize-schema=never` is seemingly not respected when a "compatible" data source is available to Spring).

Is there something fundamentally wrong with my approach? Why is the metadata model creation now being forced on Spring Batch users? Should it be?

I appreciate any insight/recommendations you have. Thank you!

**Comment by alexanderpkelly** [comment]
I was able to bypass this issue by overriding DefaultBatchConfiguration's getDataSource method to return an H2 embedded database, but bringing in an embedded database for metadata purposes only seems a little suspect (compared to simply disabling the metadata functionality).

E.g.
```java
public class BatchConfiguration extends DefaultBatchConfiguration {
    @Override
    protected DataSource getDataSource() {
        return new EmbeddedDatabaseBuilder()
            .addScript("classpath:org/springframework/batch/core/schema-drop-h2.sql")
            .addScript("classpath:org/springframework/batch/core/schema-h2.sql")
            .setType(EmbeddedDatabaseType.H2) //.H2 or .DERBY
            .build();
    }
```

**Comment by fmbenhassine** [comment]
Thank you for opening this issue.

It was never possible to "disable" meta-data. A Spring Batch job requires a `JobRepository` to report its meta-data to. In v5, you can use the JDBC-based job repository with an in-memory database like h2, hsqldb, etc as you did. That is the way to replace the Map-based job repository if you don't want to create tables in the main database. This is mentioned in the migration guide [here](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#job-repositoryexplorer-configuration-updates).

> but bringing in an embedded database for metadata purposes only seems a little suspect (compared to simply disabling the metadata functionality).

In that case, you can implement `JobRepository` as you wish and use it with your jobs and steps. Spring Batch is designed to work against the `JobRepository` interface, so any repository implementation can be used as long as it adheres to the specified contract.

I am closing this issue for now, but feel free to add a comment here if you need more support on this.

**Comment by fmbenhassine** [comment]
@alexanderpkelly  I just wanted to mention that we introduced a resourceless job repository implementation in 5.2.0-M2: https://github.com/spring-projects/spring-batch/issues/4679. Any feedback is welcome to improve things for the RC and then the GA in November.
