### ISSUE TITLE
Missing information about error handling in ChunkListeners

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4384]
Chunk listeners are not designed to throw exceptions. Exceptions must be handled in the implementation or the step will terminate. This is mentioned in the [javadoc](https://github.com/spring-projects/spring-batch/blob/d280556d0202124df6c8f4a8fcbddee2b123dd73/spring-batch-core/src/main/java/org/springframework/batch/core/step/builder/FaultTolerantStepBuilder.java#L699-L700) of `TerminateOnExceptionChunkListenerDelegate`, but this class is private.

The section about `ChunkListener`s in the [reference documentation]((https://docs.spring.io/spring-batch/docs/current/reference/html/step.html#chunkListener)) should be updated with this important detail.

---

References:

* https://stackoverflow.com/questions/76319818/is-it-possible-to-catch-and-retry-exceptions-thrown-by-a-chunklistener-in-spring

**Comment by injae-kim** [comment]
Hi @fmbenhassine ! to resolve this issue, I made PR #4490 with proper unit test.
Can you simply check my PR? thanks! 🙇
