### ISSUE TITLE
ItemReaderBuilder<> targetType requirement not enforced

### ISSUE THREAD

**Issue by casimk** [spring-projects/spring-batch#4388]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
ItemReaderBuilder<Type> does not set targetType and also there is no error if targetType is not set explicitly leading to an exception being thrown in reading the line but no error at the ItemReaderBuilder.  

```
    @Bean(name = "itemReader")
    public ItemReader<Establishment> itemReader() {
        return new FlatFileItemReaderBuilder<Establishment>()
                .name("itemReader")
                .linesToSkip(1)
//                .targetType(Establishment.class)
                .resource(new ClassPathResource(FILE_NAME))
                .delimited()
                .names(FIELD_NAMES)
                .fieldSetMapper(new BeanWrapperFieldSetMapper<Establishment>() {
                    {
                        setDistanceLimit(0);
                        setStrict(false);
                    }
                }).build();
    }
```

**Environment**
Spring Batch Core 5.02
Java 17

**Steps to reproduce**
Commented line in snippet

**Expected behavior**
The builder should validate and/or enforce the setting of the target type as required. 

**Minimal Complete Reproducible example**

**Comment by woniper** [comment]
Hello @casimk .
I think it should work like the code below.

```
    @Bean(name = "itemReader")
    public ItemReader<Establishment> itemReader() {
        return new FlatFileItemReaderBuilder<Establishment>()
                .name("itemReader")
                .linesToSkip(1)
                .resource(new ClassPathResource(FILE_NAME))
                .delimited()
                .names(FIELD_NAMES)
                .fieldSetMapper(new BeanWrapperFieldSetMapper<Establishment>() {
                    {
                        setTargetType(Establishment.class);
                        setDistanceLimit(0);
                        setStrict(false);
                    }
                }).build();
    }
```
setting targetType

OR

```
        @Bean(name = "itemReader")
	public ItemReader<Establishment> itemReader() {
		BeanWrapperFieldSetMapper<Establishment> mapper = new BeanWrapperFieldSetMapper<Establishment>() {
			{
				setTargetType(Establishment.class);
				setDistanceLimit(0);
				setStrict(false);
			}
		};
                // validate target type class
		mapper.afterPropertiesSet();

		return new FlatFileItemReaderBuilder<Establishment>()
				.name("itemReader")
				.linesToSkip(1)
				.resource(new ClassPathResource(FILE_NAME))
				.delimited()
				.names(FIELD_NAMES)
				.fieldSetMapper(mapper)
				.build();
	}

```
Before calling the Builder.build method, afterPropertiesSet must be called first to validate the settings.
If the targetType class has not been set with setTargetType, an error will be thrown when the afterPropertiesSet method is called.

I also wrote a PR to change the logic to validate that setting in the builder without explicitly calling afterPropertiesSet. (https://github.com/spring-projects/spring-batch/pull/4393)
