### ISSUE TITLE
Spying beans does not work for '@StepScope' beans within batch tests

### ISSUE THREAD

**Issue by kockas** [spring-projects/spring-batch#4394]
**Bug description**
Spying beans does not work for '@StepScope' beans within batch tests. Spied bean is not considered "mock" during Mockito.verify.

**Environment**
Spring boot 3.1.0
Spring batch 5.0.2

**Steps to reproduce**
Define steps-scoped bean. Try to inject it into batch test as @SpyMock property.

**Expected behavior**
Bean should behave like regular spied bean. Code is execuded, however verify from Mockito does work either.

**Minimal Complete Reproducible example**
run ./gradlew clean test
[demo.tar.gz](https://github.com/spring-projects/spring-batch/files/11684599/demo.tar.gz)

**Comment by woniper** [comment]
Hello. @kockas 
You can't use @StepScope without a Job in a Spring Batch. Also, a Job will never run alone; it must always be run by a JobLauncher.
Your configuration class was only set up by the Spring Context, not by the lifecycle of a Spring Batch.

<img width="1772" alt="image" src="https://github.com/spring-projects/spring-batch/assets/3378752/f582d25d-64e0-4335-99f5-32c188a58a5f">
ScopeNotActiveException is thrown when getting the HelloService class set to @StepScope internally in Mockito.

And just out of curiosity, why did you try to use @StepScope without Spring Batch?

**Comment by kockas** [comment]
Hello @woniper .
Thank you for fast response. Well, I'm fully aware of points you mentioned. In real I'm using a job and running it within JobLauncher using spring batch.
I just tried to create smallest example, where issue can be show. As you can see, when auto-wiring the bean, it works just fine. Also full mock works as expected. Only issue is, when I want just spy the bean. Then the bean is not wrapped by mockito proxy. Test is rather simple but behaves the same as my test where I use following JobLauncher:
```java
  private JobLauncherTestUtils initializeJobLauncher(Job job) {
    JobLauncherTestUtils jobLauncherTestUtils = new JobLauncherTestUtils();
    jobLauncherTestUtils.setJobRepository(jobRepository);
    jobLauncherTestUtils.setJobLauncher(jobLauncher);
    jobLauncherTestUtils.setJob(job);
    return jobLauncherTestUtils;
  }
```

**Comment by fmbenhassine** [comment]
@kockas Thank you for opening this issue and for providing a minimal sample.

The `HelloService` you are spying in your test is a Spring Batch proxy (a step-scoped proxy), hence the spy should be the proxy itself, and not the target of the AOP advised bean. In fact, in real world, the step will get a step-scoped proxy, not the target bean.

Now in order to spy the proxy itself and not the target bean, you can use `@SpyBean(proxyTargetAware = false)`. Adding that to `HelloServiceSpyTest` fixes the issue:

```diff
@SpringBootTest
@SpringBatchTest
public class HelloServiceSpyTest {

--@SpyBean
++@SpyBean(proxyTargetAware = false)
  HelloService helloService;

  @Test
  public void testHello() {
    assertEquals("Hello world", helloService.sayHello());
    Mockito.verify(helloService, Mockito.times(1)).sayHello();
  }
}
```
Looking forward to your feedback.

**Comment by kockas** [comment]
Yes, that actually solves the problem! Thank you.
