### ISSUE TITLE
Incorrect Javadoc in SimpleStepBuilder

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4402]
The Javadoc on `SimpleStepBuilder` is incorrect here:

```
Step builder for simple item processing (chunk oriented) steps. Items are read and cached in chunks,
and then processed (transformed) and written (optionally either the processor or the writer can be omitted)
all in the same transaction.
```

The item writer is mandatory in a chunk-oriented step, only the item processor is optional. The goal of this issue is to change the Javadoc as follows:

```diff
--optionally either the processor or the writer can be omitted
++optionally the processor can be omitted
```

**Comment by seonwoo960000** [comment]
Hi @fmbenhassine, thank you for the "first-timers-only" issue. May be I can start my contribution to spring batch from here 😄 . I've created a PR.

**Comment by seonwoo960000** [comment]
@fmbenhassine It's a pleasure. Hope to contribute more to greate spring batch project.
