### ISSUE TITLE
Add java.util.concurrent.ConcurrentHashMap to the trusted classes list in Jackson2ExecutionContextStringSerializer

### ISSUE THREAD

**Issue by fmarguet** [spring-projects/spring-batch#4407]
Hi @fmbenhassine, would it be possible to add java.util.concurrent.ConcurrentHashMap to the trusted classes list in Jackson2ExecutionContextStringSerializer ?
Thanks

**Comment by fmbenhassine** [comment]
Yes, `ConcurrentHashMap` is in Jackson's [trusted classes](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/tools/jackson/databind/jsontype/impl/SubTypeValidator.java) list, so I think we can safely add it to the Jackson serializer provided by Spring Batch. I will plan that for v5.1.

Please note that you can add the list of trusted classes in the constructor of `Jackson2ExecutionContextStringSerializer`.

**Comment by fmarguet** [comment]
Hi, thanks a lot for your answer and for the add in v5.1
We have the same message for java.sql.Date

We use spring/Jackson2 versions through Maven.
What would be the best way for adding classes list of trusted classes in the constructor of Jackson2ExecutionContextStringSerializer.
Does that mean we have to patch spring/Jackson2 modules ?

**Comment by fmbenhassine** [comment]
> What would be the best way for adding classes list of trusted classes in the constructor of Jackson2ExecutionContextStringSerializer.

You can add the list of additional types as parameters to the [constructor of Jackson2ExecutionContextStringSerializer](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/repository/dao/Jackson2ExecutionContextStringSerializer.html#%3Cinit%3E(java.lang.String...)).
