### ISSUE TITLE
Add ability to start a job flow definition with a decider

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4411]
### Discussed in https://github.com/spring-projects/spring-batch/discussions/4359

<div type='discussions-op-text'>

<sup>Originally posted by **acktsap** April 12, 2023</sup>
In xml based job configuration, we can set decider first like this.

```xml
<job id="decisionJob1" >
    <decision id="decider1" decider="stepFlowDecider">
        <end on="EXIT" exit-code="COMPLETED"/>
        <next on="*" to="job1Step1" />
    </decision>

    <step id="job1Step1">
        <tasklet ref="createFileTasklet"/>
    </step>
</job>
```

But when using code based job configuration, no way to start with decider. `JobBuilder` only provides start methods taking `Step`, `Flow` only.

https://github.com/spring-projects/spring-batch/blob/972951a40af03c9c0553fb4c438f9aaeb1c9f1b5/spring-batch-core/src/main/java/org/springframework/batch/core/job/builder/JobBuilder.java#L53-L78

It there any way to set decider first on code based job configuration?</div>

**Comment by seonwoo960000** [comment]
Hi! @fmbenhassine. I've created a draft PR about this issue. Please feel free to check it anytime.
