### ISSUE TITLE
JdbcJobInstanceDao.getLastJobInstance() and cached sequences 

### ISSUE THREAD

**Issue by anthochristen** [spring-projects/spring-batch#4436]
**Bug description**
`JdbcJobInstanceDao.getLastJobInstance()` uses a max query based on `JOB_INSTANCE_ID` which is a based on the `JOB_SEQ` sequence. Since sequences aren't always guaranteed to be in-order this causes and incorrect last job instance to be fetched. 
Which in turn affects other features such as `JobParametersIncrementer` which require order guarantee. 

**Environment**
 Spring Batch version: 4.x, 5.x

**Expected behavior**
getLastJobInstance always returns the last executed job instance for the particular job

**Comment by fmbenhassine** [comment]
Which database do you use?

This is similar to #2000 and #1422. Sequences should be defined as ordered and not cached. If this is not mentioned in the docs, then the docs should be updated accordingly.

**Comment by anthochristen** [comment]
We use oracle, thanks for linking #2000, I think while the sequence was created the `ORDERED` wasn't present in the default schema file. We made it as `NOCACHE` to circumvent it now.
