### ISSUE TITLE
Refactor Synchronized ItemReaders/ItemWriters for virtual threads

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-batch#4449]
Currently the `ItemReader` / `ItemWriter` implementations that are `synchronized` do actually use the `synchronized` keyword on the `read` or `write` method. (The same on the stream versions of those). 

As reading/writing could be a longer blocking operation this has the potential of thread pinning when using virtual threads. It might be better to use a lock or semaphore instead of the `synchronized` keyword.

**Comment by fmbenhassine** [comment]
Which implementations are you referring to?

For streams, this was modified in https://github.com/spring-projects/spring-batch/commit/5bccfed523b0c9afaf9c528d83ef8501f4c22f3d. For non-streams (newly added in 5.1), care was taken to use locks as well, see https://github.com/spring-projects/spring-batch/commit/f245593726f386092fb72d7063795306ad82c18d.

**Comment by mdeinum** [comment]
I was looking at Spring Batch 5.0, didn't compare with 5.1. I think this can be considered a duplicate of https://github.com/spring-projects/spring-batch/issues/4399 (or at least part of that issue).
