### ISSUE TITLE
Update documentation about serializable keys in the execution context

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4457]
The documentation [section](https://docs.spring.io/spring-batch/docs/current/reference/html/domain.html#executioncontext) about the execution context should mention that non transient keys should be `Serializable` (otherwise a custom serializer should be used).

---

Related-to: https://github.com/spring-projects/spring-framework/issues/28432

**Comment by hwan33** [comment]
@fmbenhassine Can I work on this issue?

**Comment by fmbenhassine** [comment]
@hwan33 This was planned for the internal team but sure! Thank you for your offer to help!
