### ISSUE TITLE
SEQ query fails in MariaDB version 10.3

### ISSUE THREAD

**Issue by bjlee81** [spring-projects/spring-batch#4461]
**Bug description**
In MariaDB version 10.3, the SQL of the SEQ related part is processed as MySQL SQL.
If you do the same source in MariaDB 10.4, it will be treated as MariaDB SQL.

**Environment**

- spring-batch 5.0.2
- spring-boot 3.1.1
- jdk 17
- mariadb 10.3, 10.4

**Steps to reproduce**

spring.batch.jdbc.platform=mariadb
spring.datasource.url=jdbc:mariadb://~~~
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

Table and sequence generated through 'schema-mariadb.sql' are normally seq checked and processed in the 10.4 version of DB.
If you change db to version 10.3, seq-related queries fail.
MariaDB 10.3 also supports 'Create Sequence' SQL.

The seq-generation part of mariadb(schema-mariadb.sql).
```
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=InnoDB;
```

seq-table creation part of mysql(schema-mysql.sql)
```
CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_STEP_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_SEQ);
```

**Expected behavior**

In the error message in version 10.3, MariaDB found an 'ID' field that does not exist.
```
2023-10-05 11:29:59,061 DEBUG [reactor-http-epoll-2] o.s.c.l.CompositeLog[127]: [31325984-1] Resolved 
[DataAccessResourceFailureException: Could not increment ID for BATCH_JOB_SEQ sequence table] for HTTP POST /job/run/~~~
org.springframework.dao.DataAccessResourceFailureException: Could not increment ID for BATCH_JOB_SEQ sequence table
Caused by: java.sql.SQLSyntaxErrorException: (conn=65466) Unknown column 'ID' in 'field list'
```
The log appears to have used a mysql query rather than processing for mariadb.
The mariadb schema does not have BATCH_JOB_SEQ.ID.

**Minimal Complete Reproducible example**
Just change the db version and it happens immediately when you run a simple job.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. 

> If you change db to version 10.3, seq-related queries fail.
> Just change the db version and it happens immediately when you run a simple job.

The integration test [MariaDBJobRepositoryIntegrationTests](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/test/java/org/springframework/batch/core/test/repository/MariaDBJobRepositoryIntegrationTests.java) passes with both MariaDB 10.3 and 10.4. 

Are you sure you have executed the `schema-mariadb.sql` that comes with Spring Batch 5? 

> The log appears to have used a mysql query rather than processing for mariadb.

In Spring Batch 5, MariaDB is treated as a separate database product.

**Comment by bjlee81** [comment]
Thank you for answer.
I will provide test code separately when I have time.
If there's something missing in your environment, it's ms azure mariadb.

**Comment by fmbenhassine** [comment]
OK thank you.

When you manage to create a minimal example that reproduces the issue, please add a comment here and we will re-open this issue for further investigation.
