### ISSUE TITLE
Add clear method to ExecutionContext

### ISSUE THREAD

**Issue by doljae** [spring-projects/spring-batch#4464]
## **Expected Behavior**

I want to clear the information of [ExecutionContext](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/ExecutionContext.java) after Job or Step execution.

## **Current Behavior**

However, there is currently no method to empty the entire [ExecutionContext](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/ExecutionContext.java).

## **Context**

An [ExecutionContext](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/ExecutionContext.java) can be used to address information that is common to tasks between the Steps that make up a Job, or within a Step.

Currently, the information contained in an `ExecutionContext` is stored in the `BATCH_JOB_EXECUTION_CONTEXT` table or the `BATCH_STEP_EXECUTION_CONTEXT` table when the Job ends.
Sometimes, this information may no longer be needed after the job runs. For example, if you use it for caching purposes.

However, there is currently no method to empty the entire `ExecutionContext`.

So if we had a public method to empty the entire `ExecutionContext`, we could prevent unnecessary data from being stored in the DB table after the batch job execution.

Since we are actually using `ConcurrentHashMap` under the hood, I think we can use [Map.clear()](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/util/Map.java#L336C18-L336C18) method.

**Comment by fmbenhassine** [comment]
Thank you for opening this feature request. There is no `clear` method in `ExecutionContext` because this could accidentally remove Spring Batch keys as well.

Users can remove their own keys using the `remove` method. While it is also possible to remove Spring Batch keys with the `remove` method, this would be intentional and a wrong usage of the framework. However calling `clear` could inadvertently remove the framework's keys without the intention to do so. Do you see?

**Comment by doljae** [comment]
Thanks for your detailed explanation, @fmbenhassine .
I fully understand what you say and agree with the original intention of it.

But can you explain or give me some references for saving Spring Batch keys in `ExecutionContext` please?
My question is if the spring batch keys you are referring to are the keys that are automatically added by the logic of the spring batch.

**Comment by doljae** [comment]
Nevertheless, I think it's inefficient to store information that the user manually puts in the `ExecutionContext` in the DB as it is. Users usually store small identifiers, **but sometimes they serialize the object itself, and this takes up a lot of space.**

As I explained in my previous comment, I think that in general we should avoid storing data in DB tables that the user added for a specific purpose, i.e., data that is no longer referenced after the batch job is executed.

My concern is that, as you say, the `clear()` method can also delete Spring Batch keys, so what do you think about **managing the data generated by the Spring Batch's logic and the data added by the user as separate maps?**

For example, managing user-added data as a separate map, and supporting the `clear()` method only for this map. The user could use `ExecutionContext` to share data between Jobs and Steps as before, and call `clear()` directly when these are terminated. Alternatively, I think logic that automatically calls `clear()` even if I don't call it would be fine (while giving me the option to enable/disable it).

I think this would allow the `ExecutionContext` to behave the same as it does now and avoid storing unnecessary data in the DB table after the batch job execution that was manually added by the user. I'm curious to know your thoughts on this.

**Comment by fmbenhassine** [comment]
> But can you explain or give me some references for saving Spring Batch keys in ExecutionContext please?
> My question is if the spring batch keys you are referring to are the keys that are automatically added by the logic of the spring batch.

Yes, I am referring to the keys added by Spring Batch like the step type, the flag that indicates if the current execution is a restart or a new one, etc. Here are some examples: 

https://github.com/spring-projects/spring-batch/blob/c4ad90b9b191b94cb4d21f90e5759bda9857e341/spring-batch-core/src/main/java/org/springframework/batch/core/job/SimpleStepHandler.java#L154

https://github.com/spring-projects/spring-batch/blob/2edd4006d2858fb5055c251c85bab2980a5e2192/spring-batch-core/src/main/java/org/springframework/batch/core/job/flow/JobFlowExecutor.java#L80

https://github.com/spring-projects/spring-batch/blob/52064c0541a5845aaf5640de69f601267cfa8317/spring-batch-core/src/main/java/org/springframework/batch/core/step/tasklet/TaskletStep.java#L230

> I think it's inefficient to store information that the user manually puts in the ExecutionContext in the DB as it is. Users usually store small identifiers, but sometimes they serialize the object itself, and this takes up a lot of space.

I agree, anything that does not need to be persisted should be cleared from the context. We even recommend to be careful about the size of objects stored in the context ([here](https://stackoverflow.com/a/67634234/5019386) is an example). The question is more about who is responsible for clearing out the user's keys, is it the user or the framework? And how to do that?

> what do you think about managing the data generated by the Spring Batch's logic and the data added by the user as separate maps? For example, managing user-added data as a separate map, and supporting the clear() method only for this map

I think that is too much to just be able to call clear on the user's context. One could really just filter the framework keys (those starting with `batch.`) when clearing the context or just keep a reference of the keys that were added in the context and remove those keys when appropriate. Managing two separate maps will introduce a complexity for no real added value.

Another option for you if you really want a single call to `clear` is to put all your entries in a map and add that map to the execution context under a given key, like `user.data`. With that in place, you could clear that data in the `JobExecutionListener#afterJob` with a single call like `executionContext.get("user.data", HashMap.class).clear();`. This would clear all and only user's keys without impacting the framework.

**Comment by doljae** [comment]
Thanks for your clear and detailed comment, @fmbenhassine 🙂 

I fully understand your intention and agree with your opinion.

As you explained, seems there's a way to clear custom data in context if I want. I'll try that way.
