### ISSUE TITLE
JobRegistry is empty on serverrestart due to which  jobOperator.restart(failedBatchExecutionId) API fails.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [spring-projects/spring-batch#4470]
We have a scenario where whenever a Job is executing STARTED Status the server might crash. In this case to restart the batch I understood from here [Spring Batch resume after server's failure](https://stackoverflow.com/questions/15224959/spring-batch-resume-after-servers-failure), that status and end_time column values needs to be updated in batch_job_execution and batch_step_execution from STARTED to FAILED for JobOperator.restart(jobExecutionId) API to work.

But calling this its gives "NoSuchJobException: No job configuration with the name [] was registered" because the jobRegistry map inside JobOperator is empty.

Now how to repopulate JobRegistry with these job informations on server restart, so that we can call JobOperator.restart(jobExecutionId).

Below is my code

/** The Test properties. */
  @Autowired
  private TestProperties TestProperties;

  @Primary
  @Bean(name = "TestDataSource")

  public DataSource batchDataSource() {
    DataSource TestDBSrc = DataSourceBuilder.create().username(getUsername()).password(getPassword()).url(getUrl()).build();
    if (TestDBSrc != null && TestDBSrc instanceof HikariDataSource) {
      @SuppressWarnings("resource")
      HikariDataSource hikariDatsource = (HikariDataSource) TestDBSrc;
      hikariDatsource.setSchema(getSchema());
    }
    return TestDBSrc;
  }

  private String getSchema() {
    return TestProperties.getValue("spring.datasource.hikari.schema", "");
  }

  private String getUsername() {
    return TestProperties.getValue("spring.datasource.username", "");
  }

  private String getPassword() {
    return TestProperties.getValue("spring.datasource.password", "");
  }

  private String getUrl() {
    return TestProperties.getValue("spring.datasource.jdbc-url", "");
  }

  @Bean(name = "transactionManager")
  public JdbcTransactionManager batchTransactionManager(@Qualifier("TestDataSource") DataSource dataSource) {
    return new JdbcTransactionManager(dataSource);
  }

  @Bean(name = "TestBatchJobRepository")
  public JobRepository jobRepository(@Qualifier("TestDataSource") DataSource batchDataSource,
      @Qualifier("transactionManager") JdbcTransactionManager batchTransactionManager) throws Exception {
    JobRepositoryFactoryBean factory = new JobRepositoryFactoryBean();
    factory.setDataSource(batchDataSource);
    factory.setTransactionManager(batchTransactionManager);
    factory.afterPropertiesSet();
    return factory.getObject();
  }

  @Bean(name = "TestBatchJobLauncher")
  public JobLauncher jobLauncher(@Qualifier("TestBatchJobRepository") JobRepository jobRepository) throws Exception {
    TaskExecutorJobLauncher jobLauncher = new TaskExecutorJobLauncher();
    jobLauncher.setJobRepository(jobRepository);
    jobLauncher.afterPropertiesSet();
    return jobLauncher;
  }

  @Bean (name = "TestBatchJobExplorer")
  public JobExplorer jobExplorer(@Qualifier("TestDataSource") DataSource dataSource,@Qualifier("transactionManager")JdbcTransactionManager batchTransactionManager) throws Exception {
      final JobExplorerFactoryBean bean = new JobExplorerFactoryBean();
      bean.setDataSource(dataSource);
      bean.setTransactionManager(batchTransactionManager);
      bean.setTablePrefix("BATCH_");
      bean.setJdbcOperations(new JdbcTemplate(dataSource));
      bean.afterPropertiesSet();
      return bean.getObject();
  }
  
  @Bean (name ="TestBatchJobRegistry")
  public JobRegistry jobRegistry() throws Exception {
    return new MapJobRegistry();
  }
  
  @Bean
  public JobRegistryBeanPostProcessor jobRegistryBeanPostProcessor(@Qualifier("TestBatchJobRegistry") JobRegistry jobRegistry) {
      JobRegistryBeanPostProcessor postProcessor = new JobRegistryBeanPostProcessor();
      postProcessor.setJobRegistry(jobRegistry);
      return postProcessor;
  }
  
  @Bean (name = "TestBatchJobOperator")
  public JobOperator jobOperator(@Qualifier("TestBatchJobLauncher") JobLauncher jobLauncher, @Qualifier("TestBatchJobRepository") JobRepository jobRepository,
          @Qualifier("TestBatchJobRegistry") JobRegistry jobRegistry, @Qualifier("TestBatchJobExplorer") JobExplorer jobExplorer) {
      final SimpleJobOperator jobOperator = new SimpleJobOperator();
      jobOperator.setJobLauncher(jobLauncher);
      jobOperator.setJobRepository(jobRepository);
      jobOperator.setJobRegistry(jobRegistry);
      jobOperator.setJobExplorer(jobExplorer);
      return jobOperator;
  }
}
After calling job,
Job febpTaxCalculationJob = new JobBuilder("FEBP_EMP_TAX_CALCULATION", jobRepository).incrementer(new RunIdIncrementer()).start(step).build();
     ReferenceJobFactory referenceJobFactory = new ReferenceJobFactory(febpTaxCalculationJob);
    **if (!jobRegistry.getJobNames().contains(febpTaxCalculationJob.getName())) {
        jobRegistry.register(referenceJobFactory);
      }**
We are updating the registry, but once the server restarts,
 I am using the default in-memory map

@Bean (name ="TestBatchJobRegistry")
  public JobRegistry jobRegistry() throws Exception {
    return new MapJobRegistry();
  }
Its getting cleared on server restart. So what to use so that spring batch updates nob registry on server startup. When I debug this @Bean
  public JobRegistryBeanPostProcessor jobRegistryBeanPostProcessor(@Qualifier("TestBatchJobRegistry") JobRegistry jobRegistry) {
      JobRegistryBeanPostProcessor postProcessor = new JobRegistryBeanPostProcessor();
      postProcessor.setJobRegistry(jobRegistry);
      return postProcessor;
  }  Registry is empty

**Comment by fmbenhassine** [comment]
Answered on StackOverflow: https://stackoverflow.com/a/77325676/5019386.

**Comment by PSHREYASHOLLA** [comment]
Is the code shared here https://stackoverflow.com/a/77325676/5019386. correct as I am getting empty jobRegistry everytime on server restart.
