### ISSUE TITLE
Add `fetchSize` to `JpaCursorItemReaderBuilder`

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-batch#4479]
**Expected Behavior**

`JpaCursorItemReaderBuilder` should have an option to set `fetchSize`, similar to `HibernateCursorItemReader` (which is deprecated) and `JdbcCursorItemReaderBuilder`.

**Current Behavior**

There is no option to fetch size for query executed by `JpaCursorItemReader`. As a workaround I created `FetchSizeAwareJpaQueryProvider`. Pasting here in case someone would like to use it:

```java
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import org.hibernate.jpa.AvailableHints;
import org.springframework.batch.item.database.orm.JpaQueryProvider;

/**
 * {@link JpaQueryProvider} implementation that enables setting "FETCH_SIZE" query hint on the JPA query.
 *
 * <a href="https://jdbc.postgresql.org/documentation/query/#getting-results-based-on-a-cursor">Getting results based on a cursor</a>
 * 
 * @author Maciej Walkowiak
 */
public class FetchSizeAwareJpaQueryProvider implements JpaQueryProvider {
    private final String queryString;
    private final int fetchSize;
    private EntityManager entityManager;

    public FetchSizeAwareJpaQueryProvider(String queryString, int fetchSize) {
        this.fetchSize = fetchSize;
        this.queryString = queryString;
    }

    @Override
    public Query createQuery() {
        Query query = this.entityManager.createQuery(queryString);
        query.setHint(AvailableHints.HINT_FETCH_SIZE, fetchSize);
        return query;
    }

    @Override
    public void setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }
}
```

.. and use it like this:

```java
new JpaCursorItemReaderBuilder<...>()
        .name("...")
        .entityManagerFactory(..)
        .queryProvider(new FetchSizeAwareJpaQueryProvider("<jpql query>", 100))
        .build();
```

If it makes sense I can see if I find time to contribute it.

**Comment by fmbenhassine** [comment]
Thank you for raising this, @maciejwalkowiak ! Support for query hints is indeed missing in `JpaCursorItemReader` and `JpaPagingItemReader` as well. Query hints should be set on the query just like [query parameters](https://github.com/spring-projects/spring-batch/blob/f82c16b8259e65ffd6a577b526619987b51afa7a/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/JpaCursorItemReader.java#L123-L125). Respective builders should be updated as well.

I will plan this for v5.2 (the upcoming v5.1 is in feature freeze at this point). Contributions are welcome!

**Comment by CNJingo** [comment]
Hi @fmbenhassine, I want to contribute to this issue. I'll create PR soon.
