### ISSUE TITLE
SystemCommandTasklet does not propagate errors

### ISSUE THREAD

**Issue by cachescrubber** [spring-projects/spring-batch#4483]
### `SystemCommandTasklet` does not propagate errors

If a command executed by `SystemCommandTasklet` returns a non zero exit code, the system exit code is mapped to  **ExitStatus.FAILED**.  However, the overall step execution status is **BatchStatus.COMPLETED**, meaning the step (and the job) is completed successfully.

**Environment**
spring-batch 5.0.3

**Steps to reproduce**
Create a Job with a `SystemCommandTasklet` where the system command executed will return a non zero exit code.

**Expected behavior**
The error should be propagated to the Step, and ultimately to the overall Job execution status.

**Comment by hyosyung** [comment]
Hi team, I want to work for this issue. Can I?

**Comment by fmbenhassine** [comment]
@hyosyung Sure! Thank you for your offer to help. Contributions are welcome!

**Comment by fmbenhassine** [comment]
@hyosyung Have you managed to work on this issue?

I think the way to address this is to throw an exception if the exit code mapper maps the exit code to a failed status, something like:

```diff
	if (systemCommandTask.isDone()) {
-		contribution.setExitStatus(systemProcessExitCodeMapper.getExitStatus(systemCommandTask.get()));
-		return RepeatStatus.FINISHED;
+		Integer exitCode = systemCommandTask.get();
+		ExitStatus exitStatus = systemProcessExitCodeMapper.getExitStatus(exitCode);
+		if (ExitStatus.FAILED.equals(exitStatus)) {
+			throw new SystemCommandException("Execution of system command failed with exit code " + exitCode);
+		}
+		else {
+			contribution.setExitStatus(exitStatus);
+			return RepeatStatus.FINISHED;
+		}
	}
```

This way, the step will be marked as failed correctly. Wdyt? Please let me know if you can contribute a PR along these lines, otherwise I will take care of the fix. Thank you upfront.

**Comment by injae-kim** [comment]
Hi @fmbenhassine , based on your suggestion I create fix PR https://github.com/spring-projects/spring-batch/pull/4566 PTAL :)

Thank you for detailed guide!
