### ISSUE TITLE
 ERROR: relation "batch_job_instance" does not exist 

### ISSUE THREAD

**Issue by Gyuchool** [spring-projects/spring-batch#4485]
Bug Description:
Create a new project with 3.1.4 with embedded h2 db and create chunk batch program
Run the jar file and Spring batch will throw out the error:
PreparedStatementCallback; bad SQL grammar [SELECT JOB_INSTANCE_ID, JOB_NAME from BATCH_JOB_INSTANCE where JOB_NAME = ? and JOB_KEY = ?]

ERROR: relation "batch_job_instance" does not exist

The same project (while using jobBuilderFactory and stepBuilderFactory) on 2.7.7 will work fine.
Note: If you create the schema using org/springframework/batch/core/schema-h2.sql then the jar file will work.

I have this issue with similar [issue](https://github.com/spring-projects/spring-batch/issues/4336). Was it resolved?

**Environment**
Java: 17
spring boot: 3.1.4
batch version: 5.0.3
gradle

**Steps to reproduce**
Steps to reproduce the issue.

Expected behavior
Expected that spring batch will create the tables on the fly when running the job (same behaviour as Spring 2.7.7.
Since I have put on:
application.properties
spring.batch.jdbc.initialize-schema=always

I didn't use `@EnableBatchProcessing`, Spring Batch 5 does not automatically create a schema, do I have to create it manually through schema-*.sql?

**Comment by fmbenhassine** [comment]
> I didn't use @EnableBatchProcessing, Spring Batch 5 does not automatically create a schema, do I have to create it manually through schema-*.sql?

Yes, Spring Batch does not create tables. You need to create them manually, or if you use Spring Boot, instruct Spring Boot to do it if you want.

Without `@EnableBatchProcessing`, Spring Boot v3+ should create the tables in H2. You can find an example in the [getting started guide](https://spring.io/guides/gs/batch-processing/). If you still have issues, please attach a [minimal complete example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) that reproduces the issue and we will investigate further.
