### ISSUE TITLE
Broken link to Spring Batch docs

### ISSUE THREAD

**Issue by hungwanyee** [spring-projects/spring-batch#4498]
The following url to the Spring Batch docs produces a 404 error as of November 22, 2023 1:31pm PST:

https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html

It was working fine yesterday.

**Comment by fmbenhassine** [comment]
Thank you for reporting this.

The new documentation is available here: https://docs.spring.io/spring-batch/reference/index.html, accessible from the project's home page: https://spring.io/projects/spring-batch#learn.

We will set a HTTP redirection for old URLs.

**Comment by fmbenhassine** [comment]
The URL redirection is now in place.
