### ISSUE TITLE
springbatch 4.3.5 on jboss 2.7.2

### ISSUE THREAD

**Issue by michelespinella** [spring-projects/spring-batch#4510]
Good day,
  I am trying to install a spring-batch job in jboss 2.7.2 but I am facing this issue

`ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "istruttoriaPacJob.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"istruttoriaPacJob.war\".undertow-deployment" => "java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ricevibilitaController': Unsatisfied dependency expressed through field 'myJobLauncher'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBatchConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES
    Caused by: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'xxxController': Unsatisfied dependency expressed through field 'myJobLauncher'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBatchConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES
    Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ricevibilitaController': Unsatisfied dependency expressed through field 'myJobLauncher'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBatchConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBatchConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES
    Caused by: java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES"}}
`
My spring-batch is 4.3.5, boot 2.6.6 and jackson 2.13.2.2 below my pom.xml (this pom is child of another pom that I report below)
Thanks a lot 
Best regards

POM SPRING-BATCH
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>it.tndigitale.a4g</groupId>
		<artifactId>a4g-server</artifactId>
		<version>1.0.0</version>
		<relativePath>../pom-server.xml</relativePath>
	</parent>

	<artifactId>istruttoriaPacJob</artifactId>
	<name>istruttoriaPacJob</name>
	<packaging>${project.packaging}</packaging>

	<properties>
		
		<framework.version>2.5.4</framework.version>
		<ojdbc7.version>12.1.0</ojdbc7.version>
		<client-sdk-domandepac.version>2.9.11</client-sdk-domandepac.version>
		<h2.version>1.4.200</h2.version>
		<liquibase-maven-plugin.version>3.6.2</liquibase-maven-plugin.version>
		<a4g.openapi.version>1.4.8</a4g.openapi.version>
		<hibernate-jpamodelgen.version>5.6.7.Final</hibernate-jpamodelgen.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>${a4g.openapi.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webmvc-core</artifactId>
			<version>${a4g.openapi.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>framework</artifactId>
			<version>${framework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>${ojdbc7.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>client-sdk-domandepac</artifactId>
			<version>${client-sdk-domandepac.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-ext</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-simple</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openapitools</groupId>
					<artifactId>openapi-generator</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-jpamodelgen</artifactId>
			<version>${hibernate-jpamodelgen.version}</version>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>mediator-client-java</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-csv</artifactId>
			<version>2.9.6</version>
		</dependency>
		
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>datalib</artifactId>
			<version>1.0.0</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.hibernate</groupId>
							<artifactId>hibernate-jpamodelgen</artifactId>
							<version>${hibernate-jpamodelgen.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
`
POM PARENT
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>it.tndigitale.a4g</groupId>
        <artifactId>a4g</artifactId>
        <version>1.0.0</version>
        <relativePath>./pom.xml</relativePath>
    </parent>
    
    <artifactId>a4g-server</artifactId>
    <version>1.0.0</version>
    <name>a4g</name>
    <packaging>pom</packaging>
    
    <modules>
        <module>domandepac/pom.xml</module>
        <module>mediator/pom.xml</module>
        <module>richiestamodificasuolo/pom.xml</module>
        <module>zootecnia/pom.xml</module>
        <module>ams/pom.xml</module>
        <module>datalib/pom.xml</module>
        <module>istruttoriapac/pom.xml</module>
        <module>istruttoriaPacJob/pom.xml</module>
    </modules>

    <properties>
        
        <a4g.server.output>${project.build.directory}/generated-sources/openapi</a4g.server.output>
        <a4g.server.generatorName>spring</a4g.server.generatorName>
        <a4g.server.library>spring-boot</a4g.server.library>
        <a4g.server.modelNameSuffix>Dto</a4g.server.modelNameSuffix>
        <a4g.server.templateDirectory>${a4g.openapiDirectory}/server/templates</a4g.server.templateDirectory>
        <a4g.server.basePackage>it.tndigitale.a4g.${project.name}</a4g.server.basePackage>
        <a4g.server.invokerPackage>it.tndigitale.a4g.${project.name}</a4g.server.invokerPackage>
        <a4g.server.apiPackage>it.tndigitale.a4g.${project.name}.api</a4g.server.apiPackage>
        <a4g.server.modelPackage>it.tndigitale.a4g.${project.name}.model</a4g.server.modelPackage>
        <a4g.server.configPackage>it.tndigitale.a4g.${project.name}.configuration</a4g.server.configPackage>
        
        
        <project.packaging>jar</project.packaging>
        <activatedProperties>dev</activatedProperties>

        
        <springdoc-openapi.version>1.4.8</springdoc-openapi.version>
        <jackson-databind-nullable.version>0.2.3</jackson-databind-nullable.version>
        <framework.version>2.5.10</framework.version>
        <lombok.version>1.18.24</lombok.version>
        <mapstruct.version>1.5.1.Final</mapstruct.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>${springdoc-openapi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webmvc-core</artifactId>
            <version>${springdoc-openapi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>${jackson-databind-nullable.version}</version>
        </dependency>

        
        <dependency>
            <groupId>it.tndigitale.a4g</groupId>
            <artifactId>framework</artifactId>
            <version>${framework.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>io.gsonfire</groupId>
            <artifactId>gson-fire</artifactId>
            <version>1.8.5</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>server</id>
            <activation>
                <file>
                    <exists>openapi.yaml</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>lombok-config</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <propertyfile file="lombok.config">
                                            <entry key="config.stopBubbling" value="true"/>
                                            <entry key="lombok.addLombokGeneratedAnnotation" value="true"/>
                                            <entry key="lombok.accessors.chain" value="true"/>
                                            <entry key="lombok.copyableAnnotations+" value="org.springframework.beans.factory.annotation.Value"/>
                                        </propertyfile>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy .openapi-generator-ignore</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${a4g.server.output}</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${a4g.openapiDirectory}/server</directory>
                                            <includes>
                                                <include>.openapi-generator-ignore</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>copy openapi.yaml</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/classes/static/swagger</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}</directory>
                                            <includes>
                                                <include>openapi.yaml</include>
                                            </includes>
                                            <filtering>true</filtering>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>copy schemas.yaml</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/classes/static</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}/..</directory>
                                            <includes>
                                                <include>schemas.yaml</include>
                                            </includes>
                                            <filtering>true</filtering>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.openapitools</groupId>
                        <artifactId>openapi-generator-maven-plugin</artifactId>
                        <version>${openapi-generator-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>generate spring server</id>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <output>${a4g.server.output}</output>
                                    <inputSpec>${project.basedir}/openapi.yaml</inputSpec>
                                    <generatorName>${a4g.server.generatorName}</generatorName>
                                    <library>${a4g.server.library}</library>
                                    <modelNameSuffix>${a4g.server.modelNameSuffix}</modelNameSuffix>
                                    <templateDirectory>${a4g.server.templateDirectory}</templateDirectory>
                                    <configOptions>
                                        <sourceFolder>/</sourceFolder>
                                        <basePackage>${a4g.server.basePackage}</basePackage>
                                        <invokerPackage>${a4g.server.invokerPackage}</invokerPackage>
                                        <apiPackage>${a4g.server.apiPackage}</apiPackage>
                                        <modelPackage>${a4g.server.modelPackage}</modelPackage>
                                        <configPackage>${a4g.server.configPackage}</configPackage>
                                        <dateLibrary>java8-localdatetime</dateLibrary>
                                        <useOptional>true</useOptional>
                                        <useTags>true</useTags>
                                        <interfaceOnly>true</interfaceOnly>
                                        <returnSuccessCode>true</returnSuccessCode>
                                    </configOptions>
                                    <schemaMappings>
                                        <schemaMapping>pageable=it.tndigitale.a4g.framework.pageable.PageableDto</schemaMapping>
                                    </schemaMappings>
                                    <importMappings>
                                        <importMapping>PageableDto=it.tndigitale.a4g.framework.pageable.PageableDto</importMapping>
                                    </importMappings>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <annotationProcessorPaths combine.children="append">
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                    <version>${lombok.version}</version>
                                </path>
                                <path>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${mapstruct.version}</version>
                                </path>
                            </annotationProcessorPaths>
                            <compilerArgs combine.children="append">
                                <arg>-Amapstruct.defaultComponentModel=spring</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>

        
		<profile>
			<id>dev</id>
			<properties>
				<project.packaging>jar</project.packaging>
				<activatedProperties>dev</activatedProperties>
			</properties>
		</profile>
		<profile>
			<id>test</id>
			<properties>
				<project.packaging>war</project.packaging>
				<activatedProperties>test</activatedProperties>
			</properties>
		</profile>
		<profile>
			<id>quality</id>
			<properties>
				<project.packaging>war</project.packaging>
				<activatedProperties>quality</activatedProperties>
			</properties>
		</profile>
		<profile>
			<id>produzione</id>
			<properties>
				<project.packaging>war</project.packaging>
				<activatedProperties>produzione</activatedProperties>
			</properties>
		</profile>
    </profiles>

    <build>
        <finalName>${project.name}</finalName>
        <defaultGoal>clean package</defaultGoal>
    </build>
</project>
`

**Comment by michelespinella** [comment]
good day,
    I have resolved the issue changing the version of spring batch starter and spring batch core as follow:

<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-batch</artifactId>
		<version>2.2.5.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.batch</groupId>
		<artifactId>spring-batch-core</artifactId>
		<version>4.2.1.RELEASE</version>
	</dependency>
Here the entire pom.xml


`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>it.tndigitale.a4g</groupId>
		<artifactId>a4g-server</artifactId>
		<version>1.0.0</version>
		<relativePath>../pom-server.xml</relativePath>
	</parent>

	<artifactId>istruttoriaPacJob</artifactId>
	<name>istruttoriaPacJob</name>
	<packaging>${project.packaging}</packaging>

	<properties>
		
		<framework.version>2.5.4</framework.version>
		<ojdbc7.version>12.1.0</ojdbc7.version>
		<client-sdk-domandepac.version>2.9.11</client-sdk-domandepac.version>
		<h2.version>1.4.200</h2.version>
		<liquibase-maven-plugin.version>3.6.2</liquibase-maven-plugin.version>
		<a4g.openapi.version>1.4.8</a4g.openapi.version>
		<hibernate-jpamodelgen.version>5.6.7.Final</hibernate-jpamodelgen.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
			<version>2.2.5.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-core</artifactId>
			<version>4.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-test</artifactId>
			<version>4.2.1.RELEASE</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>${a4g.openapi.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webmvc-core</artifactId>
			<version>${a4g.openapi.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>framework</artifactId>
			<version>${framework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>${ojdbc7.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>client-sdk-domandepac</artifactId>
			<version>${client-sdk-domandepac.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-ext</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-simple</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openapitools</groupId>
					<artifactId>openapi-generator</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-jpamodelgen</artifactId>
			<version>${hibernate-jpamodelgen.version}</version>
		</dependency>
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>mediator-client-java</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-csv</artifactId>
			<version>2.9.6</version>
		</dependency>
		
		<dependency>
			<groupId>it.tndigitale.a4g</groupId>
			<artifactId>datalib</artifactId>
			<version>1.0.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.hibernate</groupId>
							<artifactId>hibernate-jpamodelgen</artifactId>
							<version>${hibernate-jpamodelgen.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
`
Thanks and regards
Michele Spinella

**Comment by fmbenhassine** [comment]
> I have resolved the issue changing the version of spring batch starter and spring batch core

Thank you for sharing with us how you resolved the issue.
