### ISSUE TITLE
UI Aligment Issue - Spring Batch Version Number in Docs

### ISSUE THREAD

**Issue by Suresh-Kumar-A** [spring-projects/spring-batch#4534]
**Bug description**
The version number specified in the Spring Batch documentation page is miss aligned & Overlapping with the sidebar title. 

**Environment**
**Docs URL**: https://docs.spring.io/spring-batch/reference/
**Occurring Browsers**: Google Chrome, Brave
**Operating Systems**: Windows 10, Ubuntu 23.10

**Steps to reproduce**
Steps to reproduce the issue.
1.  Open Google Chrome (or) Brave browser.
2.  Navigate to the following URL "https://docs.spring.io/spring-batch/reference/" (or) any of the spring batch documentation URL.
3.  In the left sidebar menu you will notice the version number Overlapping with the "Spring Batch Documentation" text.

**Actual behavior**
![image](https://github.com/spring-projects/spring-batch/assets/25260283/d37a17ed-a0f4-4feb-b3c8-9fe459c17a31)

**Expected behavior**
![image](https://github.com/spring-projects/spring-batch/assets/25260283/c6e550e5-484b-4aaf-8064-e9a4c2241b68)

**Minimal Complete Reproducible example**
Reproducing steps mentioned above is the minimal one. Kindly check above steps to reproduce

**Comment by Suresh-Kumar-A** [comment]
**Recommended Fix**: Remove "height:24px;" (or) replace it with "max-height:48px" in the "span class="title""

![image](https://github.com/spring-projects/spring-batch/assets/25260283/be74ecd0-6406-4281-894d-466fc703eab4)

**Comment by fmbenhassine** [comment]
Thank you for reporting this. It should have been fixed in the latest snapshots: https://docs.spring.io/spring-batch/reference/5.2-SNAPSHOT/index.html

Can you please check?

**Comment by Suresh-Kumar-A** [comment]
@fmbenhassine the issue is resolved in the above url. I'm closing this issue.
