### ISSUE TITLE
Reference Documentation Uses Deprecated Class StepExecutionListenerSupport

### ISSUE THREAD

**Issue by robertmcnees** [spring-projects/spring-batch#4538]
In the [reference documentation for controlling flow](https://docs.spring.io/spring-batch/reference/step/controlling-flow.html#batchStatusVsExitStatus), the deprecated class [StepExectuionListenerSupport](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/listener/StepExecutionListenerSupport.html) is used in the Java code sample.

The doc can be found [here](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-docs/modules/ROOT/pages/step/controlling-flow.adoc#batch-status-versus-exit-status).  Specifically this code:

```java
public class SkipCheckingListener extends StepExecutionListenerSupport {
    public ExitStatus afterStep(StepExecution stepExecution) {
        String exitCode = stepExecution.getExitStatus().getExitCode();
        if (!exitCode.equals(ExitStatus.FAILED.getExitCode()) &&
              stepExecution.getSkipCount() > 0) {
            return new ExitStatus("COMPLETED WITH SKIPS");
        }
        else {
            return null;
        }
    }
}
```

**Comment by petrovskimario** [comment]
Hello @robertmcnees 
I can take this one if it is still available.

**Comment by petrovskimario** [comment]
@fmbenhassine @robertmcnees 

I have submitted a pull request. Please review and if you have any suggestions let me know.

Thanks!
