### ISSUE TITLE
StepExecution.getEndTime() is retun null 

### ISSUE THREAD

**Issue by harishdalm** [spring-projects/spring-batch#4539]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
StepExecution.getEndTime() invoked inside StepExecutionListener.afterStep() returns null.(StepExecutionListener.afterStep() is) Called after execution of step's processing logic (both successful or failed).

I already found a similar issue, [https://github.com/spring-projects/spring-batch/issues/2710  but wanted to check if the changes will be working with JAVA 17. Can you please share the delivery date?

**Environment**
JDK 17
- org.springframework.boot:spring-boot-starter-batch:jar:3.1.0:compile
 \- org.springframework.batch:spring-batch-core:jar:5.0.2:compile

**Steps to reproduce**
Steps to reproduce the issue.
The console result is like below:

[  SpringBootApplication] i.h.s.s.s.SpringBatchSampleApplication   : Started SpringBatchSampleApplication in 0.712 seconds (JVM running for 1.259)
[  SpringBootApplication] o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: []
[  SpringBootApplication] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=Sample Job]] launched with the following parameters: [{}]
[  SpringBootApplication] o.s.batch.core.job.SimpleStepHandler     : Executing step: [Sample Step]
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : Sample TaskLet executed
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : stepName: Sample Step
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : stepStartedAt: Mon Feb 08 11:36:12 KST 2021
**[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : stepEndedAt: null  ===============> SHOULD BE A VALID TIME**
[  SpringBootApplication] o.s.batch.core.step.AbstractStep         : Step: [Sample Step] executed in 10ms
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : jobName: Sample Job
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : jobStartedAt: Mon Feb 08 11:36:12 KST 2021
[  SpringBootApplication] i.h.s.springbatch.sample.BatchConfig     : jobEndedAt: Mon Feb 08 11:36:12 KST 2021
[  SpringBootApplication] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=Sample Job]] completed with the following parameters: [{}] and the following status: [COMPLETED] in 21ms

**Expected behavior**
StepExecution.getEndTime() invoked inside StepExecutionListener.afterStep() should return a valid time instead of null.

**Minimal Complete Reproducible example**
Please provide a failing test or a [minimal complete verifiable example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by harishdalm** [comment]
@fmbenhassine and team, can you please help here.

**Comment by harishdalm** [comment]
Please help on this. Thank you

**Comment by fmbenhassine** [comment]
@harishdalm This is the same issue as #3846, which is already planned  for the next minor release 5.2.0. Please follow the updates on #3846 .

**Comment by harishdalm** [comment]
Thanks for the response.
