### ISSUE TITLE
Spring batch Partitioner : How to make a spring boot app having spring batch functionality work as multinode

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [spring-projects/spring-batch#4542]
We have a spring boot application which is designed specifically to handle spring batch jobs. Here we are using spring batch partioner approach. This approach was chosen as we needed the resumability/restartability of a batch on failure in a single node. Reference : [Restarting a job after server crash is not processing the unprocessed data](https://stackoverflow.com/questions/77432989/restarting-a-job-after-server-crash-is-not-processing-the-unprocessed-data/77436608?noredirect=1#comment136622034_77436608).

Now we need to make our application multi node by pointing our multiple copies of this spring boot servers to same database. So is there a provision now in spring batch which will make jobs node aware. For scenarios like,

1) If the job is being processed by node1 and if node 1 goes down, node 2 needs to pick it from where node1 had left,
2) Through load balancer jobs should be distributed across nodes etc..

**Comment by fmbenhassine** [comment]
I answered this question on SO: https://stackoverflow.com/questions/77905776/spring-batch-partitioner-how-to-make-a-spring-boot-app-having-spring-batch-fun/77955135#77955135.

Please use the issue tracker only for bug reports or feature requests.  For support requests, please use Github Discussions or StackOverflow: https://github.com/spring-projects/spring-batch/blob/main/SUPPORT.md. Thank you.

**Comment by PSHREYASHOLLA** [comment]
Noted Thanks.
