### ISSUE TITLE
Not able to create JobRepository for spring-batch 5.x (MongoDB)

### ISSUE THREAD

**Issue by monalisha1994** [spring-projects/spring-batch#4549]
Hi,

- I am trying to move from spring batch 4.x to 5.x. where I am trying to create JobRepository .
- I am using @EnableBatchProcessing where its asking me to create a datasource while creating bean for JobRepository.
- I dont want datasource to add while creating JobRepository bean.
- I am excluding DataSourceAutoConfiguration.class , still its asking me to create a bean for datasource
- @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class, MongoAutoConfiguration.class,MongoDataAutoConfiguration.class})

Please suggest

**Comment by mdeinum** [comment]
The default `JobRepository` requires a `DataSource` there is no more in-memory implementation. You can use H2 to serve as an in-memory database to use this.

**Comment by monalisha1994** [comment]
Adding H2 databse , its giving me error:
[REASON:: PreparedStatementCallback; bad SQL grammar [SELECT JOB_INSTANCE_ID, JOB_NAME\nFROM BATCH_JOB_INSTANCE\nWHERE JOB_NAME = ?\n and JOB_KEY = ?]]

**Comment by fmbenhassine** [comment]
If you use `@EnableBatchProcessing` with Spring Boot 3, then the batch auto-configuration (datasource initialization, automatic execution of jobs at startup, etc) will back off. So you either need to remove `@EnableBatchProcessing` and let Spring Boot auto-configure that batch infrastructure, or provide a datasource that you initialize yourself with the batch tables. There is a note about this in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-batch-changes) of Spring Boot.

That said, you can also define a custom `JobRepository` (that is not based on a datasource) as a bean and Spring Batch will use it. Please try these options and share your feedback with us.

**Comment by fmbenhassine** [comment]
I am closing this issue for now. But if you need more support on this, please add a comment.
