### ISSUE TITLE
Spring Batch step write_count less than read_count and filter and skip counts are all zero

### ISSUE THREAD

**Issue by rezashirinnezhad** [spring-projects/spring-batch#4558]
We are facing a situation in Spring Batch that step write_count sometimes is less than read_count and filter_count and read_skip_count, process_skip_count and write_skip_count are all zero while the job has been completed successfully with no exception. We are still investigating but wished to know how can this happen and what can cause that?
Just to add we have 2 different writers for this step and we use classifier to switch between them under some conditions.
Here is the step configuration code:

>     public Step step() {
>     return stepBuilderFactory.get("jobName")
>         .<InputTransaction, OutputTransaction>chunk(500)
>         .reader(itemReader)
>         .processor(itemProcessor)
>         .writer(classifierCompositeItemWriter())
>         .faultTolerant()
>         .skipLimit(Integer.MAX_VALUE)
>         .skip(RuntimeException.class)
>         .listener(adjustTransactionItemWriter)
>         .listener(adjustTransactionItemLogFileWriter)
>         .build();
> }

**Comment by fmbenhassine** [comment]
In order to avoid duplicate efforts, I am closing this issue as it was asked on SO: https://stackoverflow.com/questions/78075520. I asked for more details and I will follow up there.
