### ISSUE TITLE
remote partitioning doesn't work if you're using graalvm 

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-batch#4564]
i have an example, [here](https://github.com/joshlong-attic/batch-partitioning-example) that fails if you don't add a few extra hints for a simple example compiled to graalvm and using remote partitioning. please add the following hints to the jar itself so users don't need to

i had to put this on the worker node and `@ImportRuntimeHints` it:

```
    static class Hints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            var mcs = MemberCategory.values();
            hints.reflection().registerType(StepExecutionRequestHandler.class, mcs);
            hints.serialization().registerType(StepExecutionRequest.class);
        }
    }
```

i had to put this on the leader node and `@ImportRuntimeHints` it:

```
    static class Hints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {

            var mcs = MemberCategory.values();
            hints.reflection().registerType(MessageChannelPartitionHandler.class, mcs);
            hints.serialization().registerType(StepExecutionRequest.class);
        }
    }
```

**Comment by RubenGamarrarodriguez-tomtom** [comment]
I was watching the tips video https://www.youtube.com/watch?v=dmdkJ3ZmT5E&list=PLgGXSWYM2FpPw8rV0tZoMiJYSCiLhPnOc&index=28 good to see that now the hint seem to be added.
