### ISSUE TITLE
MockStatic and MockConstruction not working in spring batch test cases

### ISSUE THREAD

**Issue by vatsla20** [spring-projects/spring-batch#4574]
**Bug description**
I am trying to mock static function and new instantiations in the spring tasklet step testing, but the mocks are not working and are going to the actual implementations.

**Environment**
spring.batch.version - 5.1.1
mockito-core - 5.11

This is my code - 

conn = ConnectionFactory.getConnection(tenantID);
This is the line I want to mock the implementation for, using spring batch 5 and mockito 5. My guess its because of the annotations as in my other files mock static is working fine, where the spring batch annotations are not present.

How can I mock these calls, as I do not want to execute the actual implementations of these classes?

@SpringBatchTest
@SpringBootTest
@SpringJUnitConfig(BatchConfig.class)
@EnableAutoConfiguration
@ContextConfiguration(classes = { BatchConfig.class, DataSourceConfiguration.class, DatabaseConfig.class})
@ActiveProfiles(profiles = "test")
@TestPropertySource(value = { "classpath:application-test.properties" })

public class TestingProcessor {

    @Autowired
    private JobLauncherTestUtils jobLauncherTestUtils;
    @Autowired
    private JobRepositoryTestUtils jobRepositoryTestUtils;
    @InjectMocks
    Processor processor;
    @InjectMocks
    Payload payload;

    @MockBean
    JobListner jobListner;
    @MockBean
    AlertNotification ans;
    @MockBean
    AlertConfig alertConfig;
    
    @Autowired
    @Qualifier("pipeline")
    Job job;

    @Autowired
    @Qualifier("JobLauncher")
    JobLauncher jobLauncher;

    @AfterEach
    public void cleanUp() {
        jobRepositoryTestUtils.removeJobExecutions();
    }

    @BeforeEach
    public void initMocks() {
        MockitoAnnotations.openMocks(this);
    }

    public StepExecution getExecutionContext() {
        StepExecution execution = MetaDataInstanceFactory.createStepExecution();
        execution.getExecutionContext().put(SchedulerConstants.CONTEXT, context);
        return execution;
    }
    @Test
    public void testingProcessorTasklet() throws Exception {
        this.jobLauncherTestUtils.setJobLauncher(jobLauncher);

        JobParameters jobParameters = new JobParametersBuilder()
                .addString(SchedulerConstants.TENANTID_CONTEXT, "TestTenantId")
                .addLong("time", System.currentTimeMillis())
                .toJobParameters();
        StepExecution executionContext = getExecutionContext();

        when(mockedClass1.getTenant(anyString())).thenReturn("mockedClass2");
        when(mockedClass2.getTenantId()).thenReturn("mockTenantId");
//these are working they return the mocked values

        try (MockedStatic<ConnectionFactory> mockedStatic = Mockito.mockStatic(ConnectionFactory.class)) {
            Connection connection = mock(Connection.class);
            mockedStatic.when(() -> ConnectionFactory.getConnection(any())).thenReturn(connection);
//these are not working even MockConstruction is not mocking

            JobExecution jobExecution = jobLauncherTestUtils.launchStep("PROCESS_IT", jobParameters, executionContext
                    .getExecutionContext());

            Assertions.assertEquals(BatchStatus.STARTING, jobExecution.getStatus());
            while (jobExecution.isRunning()) {
            }
            Assertions.assertEquals("COMPLETED", jobExecution.getExitStatus().getExitCode());
        }
    }
}

**Comment by fmbenhassine** [comment]
To avoid duplicate efforts, I am closing this issue as it was asked on SO: https://stackoverflow.com/questions/78290369/mockstatic-and-mockconstruction-not-working-in-spring-batch-test-cases. I asked for mote details , let's continue there.
