### ISSUE TITLE
Deprecate the usage of LobHandler

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4588]
Following the deprecation of `LobHandler` in Spring Framework [#32179](https://github.com/spring-projects/spring-framework/issues/32179), the usage of this API should be deprecated in Spring Batch as well.

**Comment by kanathan9** [comment]
Hi @fmbenhassine I would like to work on this issue. I have seen the fixes for [#32179](https://github.com/spring-projects/spring-framework/issues/32179) and [#32161](https://github.com/spring-projects/spring-framework/issues/32161).

**Comment by fmbenhassine** [comment]
@kanathan9 Thank you for your offer to help! Sure, give it a try and open a PR, I will review it for 5.2.0-M2 (which is planned for October 9th). Please note that this should include the deprecation of `LobHandler` in public APIs as well as in the XSD, and update its usage with the suggested replacement if any where appropriate. Let me know if you need help on this.

**Comment by kanathan9** [comment]
@fmbenhassine PR opened. I replaced LobHandler by standard setClob method.
