### ISSUE TITLE
Regression in Javadoc deployment path with 5.1.2

### ISSUE THREAD

**Issue by scordio** [spring-projects/spring-batch#4604]
A new `api` folder appeared in the URL, compared to the previous version:
* 5.1.1: https://docs.spring.io/spring-batch/docs/5.1.1/api/
* 5.1.2: https://docs.spring.io/spring-batch/docs/5.1.2/api/api/

**Comment by fmbenhassine** [comment]
Thank you for reporting this. 

Resolved with 0b2c741e79bf76f6155dea3b216b7cdd109aeb5d, which now deploys the javadocs to the right folder: https://docs.spring.io/spring-batch/docs/5.1.3-SNAPSHOT/api/

The javadocs for 5.1.2 were redeployed to the right path as well: https://docs.spring.io/spring-batch/docs/5.1.2/api/

**Comment by scordio** [comment]
Thanks a lot!
