### ISSUE TITLE
Link to batch reference documentation on project page is incorrect

### ISSUE THREAD

**Issue by fstorz** [spring-projects/spring-batch#4637]
**Bug description**
The link on the batch project page to the "reference documentation section on Batch Applications" links to https://docs.spring.io/spring-boot/docs/current/reference/html/howto-batch-applications.html which in the end leads to the main spring-boot documentation on https://docs.spring.io/spring-boot/index.html.
![image](https://github.com/user-attachments/assets/3db1fb02-ea5b-44c8-80e4-4699844a286c)

**Steps to reproduce**
Go to https://spring.io/projects/spring-batch and click on the link "reference documentation section on Batch Applications" at the bottom of the page.

**Expected behavior**
The user is linked to a batch related page at https://docs.spring.io/spring-batch/reference/index.html or https://docs.spring.io/spring-boot/how-to/batch.html.

**Comment by fmbenhassine** [comment]
Good catch! Thank you for raising this.

I fixed the link to the correct Spring Boot page.
