### ISSUE TITLE
typo in the chapter Spring Batch Integration of documentation

### ISSUE THREAD

**Issue by pxzxj** [spring-projects/spring-batch#4649]
chapter [Spring Batch Integration/Sub-elements/Asynchronous Processors](https://docs.spring.io/spring-batch/reference/spring-batch-integration/sub-elements.html#asynchronous-processors)
Asynchronous Processors help you scale the processing of items. In the asynchronous processor use case, an AsyncItemProcessor serves as a dispatcher, executing the logic of the ItemProcessor for an item on a new thread. Once the item completes, the Future is passed to the **AsynchItemWriter** to be written.

wrong: `AsynchItemWriter`
correct: `AsyncItemWriter`

**Comment by fmbenhassine** [comment]
That correct, good catch! You are welcome to contribute the fix if you want.

**Comment by pxzxj** [comment]
OK,I'll create a PR.By the way, this typo exists in multiple branchs
