### ISSUE TITLE
Batch table relationship description seems to be wrong.

### ISSUE THREAD

**Issue by chaenabi** [spring-projects/spring-batch#4653]
[StackOverflow](https://stackoverflow.com/questions/73990604/spring-official-batch-table-relationship-description-seems-wrong).

Hello, 
after writing the question above I couldn't pay attention for a while.
if the above issue is still valid, please concern to correct the description picture.

The photo and file below are a list of attached files for requesting correction. 
(The zip file is a Mysql Workbench model diagram (mwb extension) file.)

![batch_erd](https://github.com/user-attachments/assets/52d05069-b463-4cce-82c5-870045835195)
[batch_erd.zip](https://github.com/user-attachments/files/16722402/batch_erd.zip)

**Comment by chaenabi** [comment]
Thanks for the reponse. 
I wonder it looks like the updated picture still describes at #4358 
BATCHSTEP_EXCEUTION_CONTEXT / BATCH_STEP_EXECUTION tables as many to one relationship
(BATCH_JOB_EXECUTION / BATCH_JOB_EXECUTION_CONTEXT too)
aren't each table a one-to-one relationship anymore?

**Comment by fmbenhassine** [comment]
I see. This is actually the output of MySQL workbench for the given schema, which seems to be inaccurate (I don't see how to alter that). However, the [corresponding text](https://docs.spring.io/spring-batch/reference/schema-appendix.html#metaDataBatchJobExecutionContext) describing the tables is accurate:

```
There is exactly one Job ExecutionContext for each JobExecution, [...]
```

Is that what you are looking for?

**Comment by chaenabi** [comment]
yes I am. 
if this is acceptable to you, you may see the picture #4653 to update

**Comment by fmbenhassine** [comment]
OK I see the difference with your update (relations are now one-to-one), thank you for doing that! 👍 

I will re-open this issue and plan the fix for the next release.

**Comment by fmbenhassine** [comment]
I will plan this for v6 and rework all diagrams with something other than MySQL workbench (to avoid having to reverse engineer the diagram every time).
