### ISSUE TITLE
NPE inside getString method of JobParameters class

### ISSUE THREAD

**Issue by Demdelf** [spring-projects/spring-batch#4671]
Seems like if jobParameter will be null we will get NPE here
`if (!jobParameter.getType().equals(String.class)) {`

Whole method of JobParameters class:

```
@Nullable
	public String getString(String key) {
		if (!parameters.containsKey(key)) {
			return null;
		}
		JobParameter<?> jobParameter = parameters.get(key);
		if (!jobParameter.getType().equals(String.class)) {
			throw new IllegalArgumentException("Key " + key + " is not of type String");
		}
		return (String) jobParameter.getValue();
	}
```

https://github.com/spring-projects/spring-batch/blob/53e33c06e9cabdd8794b748b4cd58a3fbd65e321/spring-batch-core/src/main/java/org/springframework/batch/core/JobParameters.java#L117C1-L118C1

**Comment by mdeinum** [comment]
That should be prevented by the `if (!parameters.containsKey(key)) {` statement at the start of this method. This checks if the parameter is available, if not it will return `null` and not proceed. So if the `JobParameter` doesn't exists that code should be unreachable.

**Comment by Demdelf** [comment]
@mdeinum just imagine that parameters.containsKey(key) but it's value = null so jobParameter = null
and when we will run jobParameter.getType() - NPE will thrown

**Comment by mdeinum** [comment]
In theory yes, but all APIs surrounding this don't allow a `null` value, to be added. Now this might be better enforced by using a `ConcurrentHashMap` instead of a reguler `HashMap` inside the `JobParameters`. This will enforce it and throw an exception if this happens, this instead of doing additional `null` checks in all the methods.

**Comment by Demdelf** [comment]
Yes, you are right. Thanks for your replies!
