### ISSUE TITLE
Error in Migration guide

### ISSUE THREAD

**Issue by CharliePrm88** [spring-projects/spring-batch#4695]
Hi,
I will be short:

I was migrating to Spring Batch 5 following [your guide](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide) and Liquibase throw error when adding [this new column](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#column-change-in-batch_step_execution).

The error is that in the guide you wrote "1970-01-01 00:00:00" but that value is invalid in timestamp so I had to put "1970-01-01 00:00:01".

Best Regards

**Comment by fmbenhassine** [comment]
Thank you for reporting this! I don't remember having an issue with that value while testing the migration script (it probably depends on which db system you use and which version), but I updated the guide as you suggested as it should not really matter. Thank you!
