### ISSUE TITLE
Typo in Wiki "Spring Batch 5.0 Migration Guide"

### ISSUE THREAD

**Issue by Yg-Hong** [spring-projects/spring-batch#4698]
Chapter [Transaction manager bean exposure/configuration](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#transaction-manager-bean-exposureconfiguration)

Up until version 4.3, the @EnableBatchProcessing annotation exposed a **tranasaction** manager bean in the application context. While this was convenient in many cases, the unconditional exposure of a **tranasaction** manager could interfere with a user-defined transaction manager.

wrong : tranasaction
correct : transaction

**Comment by fmbenhassine** [comment]
Good catch, thank you for reporting these typos!

I fixed that. It should be correct now.
