### ISSUE TITLE
Unclear documentation about wildcard usage to select input files

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4707]
This section of the docs https://docs.spring.io/spring-batch/reference/readers-and-writers/multi-file-input.html is not clear regarding how input files are selected with a wildcard.

We need to update the text as well as the Java sample (the XML one is correct) to clarify how the wildcard is used to select input files.

cc @snicoll

**Comment by zedbeit** [comment]
Hi @fmbenhassine, When you have a moment, could you please take a look at this Spring Batch issue I'm facing? It works for 1k records but fails for 10k. Here's the link: https://stackoverflow.com/questions/79194924/spring-batch-chunk-processing-fails-for-10k-records-works-for-1k-connection-m

**Comment by fmbenhassine** [comment]
@zedbeit I added a comment on your SO question. Please do not request help like that on a completely different issue. You are always welcome to open a separate issue or discussion with the details of your support request. Thank you for your comprehension. I will hide/delete unrelated comments here.
