### ISSUE TITLE
String array command with SystemCommandTasklet

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#752]
**[dgray16](https://jira.spring.io/secure/ViewProfile.jspa?name=dgray16)** opened **[BATCH-2863](https://jira.spring.io/browse/BATCH-2863?redirect=false)** and commented

Hi. Using this chance I want to thank you for Spring Batch, it is amazing :)

Now, directly to the topic.

 

I want to use

```java
org.springframework.batch.core.step.tasklet.SystemCommandTasklet 
```

but there an issue.

 

There is method:

```java
org.springframework.batch.core.step.tasklet.SystemCommandTasklet#setCommand
```

which accepts

```java
java.lang.String
```

 

My task is simple: run network packet analyzer _Wireshark_ before processing is started.

Bash command looks like this:

 

```java
/bin/bash -c tshark -i enp1s0 -w ~/Documents/log.pcap -f "host 8.8.8.8"
```

 

The problem is that

```java
java.util.StringTokenizer#StringTokenizer(java.lang.String)
```

is about to split provided String with Bash command into array, after it command is not working.

 

In this case helps a lot another method

```java
java.lang.Runtime#exec(java.lang.String[], java.lang.String[], java.io.File)
```

So if I split manually command into this:

```java
new String[] { "/bin/bash", "-c", "tshark -i enp1s0 -w ~/Documents/log.pcap -f \"host 8.8.8.8\""}
```

Works perfectly.

 

If there is tricky way to hack

```java
java.util.StringTokenizer#StringTokenizer(java.lang.String)
```

to make it work with my example, I suggest to add JavaDoc above

```java
org.springframework.batch.core.step.tasklet.SystemCommandTasklet#setCommand
```

 

If not, I suggest to provide possibility to use both forms, String[] + String.

 

And one more thing, there may be opportunity to run sh script by single String method (did not test it), but I am not interested in it. I am interested only in hardcoded bash command.

 

As a workaround for it right now I have written this code:

```java
Tasklet tasklet = (contribution, chunkContext) -> {
    new ProcessBuilder("/bin/bash", "-c", "tshark -i enp1s0 -w ~/Documents/log.pcap -f \"host 8.8.8.8\"").start();
    return RepeatStatus.FINISHED;
};
```

 

In any case I am ready to create PR based on discussion here if that will be needed.

 

---

**Affects:** 4.2.1

**Comment by philippe-tr** [comment]
Passing command arguments as environment parameters seems counter-intuitive. Does this mean the intent of SystemCommandTasklet#setEnvironmentParams is both command arguments and environment parameters?

**Comment by hpoettker** [comment]
I wouldn't expect that passing command arguments to `setEnvironmentParams` actually works. The array of environment parameters is passed as is to `ProcessBuilder::environment`. The example arguments above should get silently (compatibility with Java 4 ...) ignored there since they don't contain a `=`.

**Comment by philippe-tr** [comment]
I have ideas for how to support this while maintaining backward compatibility. I also want to do it in a way that would work for the requirements in [BATCH-2318](https://github.com/spring-projects/spring-batch/issues/1283)
