### ISSUE TITLE
Multithreaded KafkaItemReader on lines of JdbcPagingItemReader [BATCH-2855]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#760]
**[Abhinav Nigam](https://jira.spring.io/secure/ViewProfile.jspa?name=abnig19)** opened **[BATCH-2855](https://jira.spring.io/browse/BATCH-2855?redirect=false)** and commented

Hello Mike

 

Checking if there is possibility to have a multithreaded item reader to read from a Kafka topic/partition similar to JdbcPagingItemReader

 

Regards

Abhinav

---
No further details from [BATCH-2855](https://jira.spring.io/browse/BATCH-2855?redirect=false)

**Comment by benas** [comment]
The `KafkaItemReader` is based on a `KafkaConsumer` which is **not** thread safe. Here is an excerpt from [its Javadoc](https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#multithreaded):

```
The Kafka consumer is NOT thread-safe.
All network I/O happens in the thread of the application making the call.
It is the responsibility of the user to ensure that multi-threaded access
is properly synchronized. 
```

Hence, the `KafkaItemReader` is in turn [not thread-safe](https://github.com/spring-projects/spring-batch/blob/a7092a21e428cf904f210aff2682b518dc3649c5/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/kafka/KafkaItemReader.java#L46). If you want to use it in a multi-threaded scenario, you can decorate it with a `SynchronizedItemStreamReader`. In a partitioned scenario (for example with a partitioner that creates a Spring batch partition for each partition in a given kafka topic), using a step-scoped reader should make it thread-safe as well.

That said, to answer the question about the "possibility to have a multithreaded item reader to read from a Kafka topic/partition ", I will base my answer on the following section from the aforementioned Javadoc of the Kafka consumer:

```
We have intentionally avoided implementing a particular threading model for processing.
This leaves several options for implementing multi-threaded processing of records.

1. One Consumer Per Thread
A simple option is to give each thread its own consumer instance
[...]
2. Decouple Consumption and Processing
Another alternative is to have one or more consumer threads that do all data consumption
and hands off ConsumerRecords instances to a blocking queue consumed by
a pool of processor threads that actually handle the record processing.
[...]
```

* To implement option 1: You can create multiple `KafkaItemReader`s (each one with its own kafka consumer), then make each thread use a different reader
* To implement option 2: Use a single `KafkaItemReader` and couple it with an `AsyncItemProcessor`/`AsyncItemWriter` (aka reading is single threaded and processing/writing is multi-threaded)

I'm closing this issue for now as I explained the reason why the `KafkaItemReader` cannot be made thread-safe and gave some alternative options.
