### ISSUE TITLE
Add getUniqueJobParametersBuilder() in JobLauncherTestUtils. [BATCH-2847]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#767]
**[jojoldu](https://jira.spring.io/secure/ViewProfile.jspa?name=jojoldu)** opened **[BATCH-2847](https://jira.spring.io/browse/BATCH-2847?redirect=false)** and commented

JobLauncherTestUtils often uses the getUniqueJobParameters method.
But it seems a bit cumbersome to use this method with other JobParameters.
In the same case, I use it like this:

```
new JobParametersBuilder(jobLauncherTestUtils.getUniqueJobParameters())
.addString()
.addDouble()
```

I want to make this convenient.

```
jobLauncherTestUtils.getUniqueJobParametersBuilder()
.addString()
.addDouble()
```

What do you think?

---

**Affects:** 4.2.0

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/734

**Comment by benas** [comment]
Resolved with #734 .
