### ISSUE TITLE
setScriptEvaluator method in ScriptItemProcessor removed in Spring Batch 4 [BATCH-2846]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#768]
**[David Geary](https://jira.spring.io/secure/ViewProfile.jspa?name=david_geary)** opened **[BATCH-2846](https://jira.spring.io/browse/BATCH-2846?redirect=false)** and commented

This method was added as a result of [BATCH-2270](https://jira.spring.io/browse/BATCH-2270).

We have recently upgraded to Spring Batch 4 and are getting compilation errors as this method has been removed.

---

**Affects:** 4.1.2

**Comment by benas** [comment]
Fixed by cherry-picking the original commit in the 4.x lines, see d6f90a1d214e17fc6a1f62251d1a90aa3e72b07b.
