### ISSUE TITLE
Class cast exception when autowiring flat file writer [BATCH-2822]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#792]
**[rovshenn](https://jira.spring.io/secure/ViewProfile.jspa?name=rovshenn)** opened **[BATCH-2822](https://jira.spring.io/browse/BATCH-2822?redirect=false)** and commented

When autowiring `@Bean` in the xml job config, I get class cast exc as shown in the comment.

---

**Affects:** 4.1.1

This issue is a sub-task of [BATCH-2023](https://jira.spring.io/browse/BATCH-2023)

**Comment by benas** [comment]
> as shown in the comment.

Which comment? I see this issue has been marked as a sub-task of [BATCH-2023](https://jira.spring.io/browse/BATCH-2023), so are you referring to this comment: https://github.com/spring-projects/spring-batch/issues/1569#issuecomment-566279715? If yes, then please note that I fixed the formatting and tried to import the snippet in my IDE but this was not enough to be able to run the sample and reproduce the issue. 

Please provide a minimal example that reproduces the issue and we will take a look.
