### ISSUE TITLE
"ISO-8859-1" charset usage is still forced in JdbcExecutionContextDao [BATCH-2804]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#795]
**[Matthias Fiebiger](https://jira.spring.io/secure/ViewProfile.jspa?name=mfiebiger)** opened **[BATCH-2804](https://jira.spring.io/browse/BATCH-2804?redirect=false)** and commented

This is a known issue. With Spring Batch 4 it has got worsened.

With Spring 4 The XStreamExecutionContextStringSerializer is deprecated. You should use the Jackson2ExecutionContextStringSerializer. But this Serializer can only be used with utf-encoding. JdbcExecutionContextDao only works with ISO-8859-1. Thus, by default all spring Batch 4 applications will destroy special characters. Some Databases do not except the broken characters.

---

**Affects:** 4.1.1

**Reference URL:** https://jira.spring.io/browse/BATCH-2057

**Attachments:**
- [stacktrace.txt](https://jira.spring.io/secure/attachment/26202/stacktrace.txt) (_11.15 kB_)

**Comment by benas** [comment]
The default encoding in `JdbcExecutionContextDao` has been changed to UTF-8 (see #3983), which should fix this issue. 

Moreover, the charset has been made configurable in `JdbcExecutionContextDao` (see 9315a3b438ae8c95f74f05ba369f21a5838e9b01).
