### ISSUE TITLE
 hibernate.default_batch_fetch_size option does not work in JpaPagingItemReader. [BATCH-2805]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#802]
**[jojoldu](https://jira.spring.io/secure/ViewProfile.jspa?name=jojoldu)** opened **[BATCH-2805](https://jira.spring.io/browse/BATCH-2805?redirect=false)** and commented

(In Spring Boot Batch 2.1.3)

jpa I used hibernate.default_batch_fetch_size to improve performance, but it has no effect.

For JpaRepository and HibernateCursorItemRepository, these options work normally.

An N + 1 issue occurs.

Below is my test.

 

https://github.com/jojoldu/blog-code/blob/master/spring-batch-n1/src/main/java/com/jojoldu/batch/job/StoreBackupBatchConfiguration.java

 

 

---

**Affects:** 4.1.1

**Comment by benas** [comment]
Thank you for opening this issue. However, it is not clear to me. What I understood is that you are trying to change `hibernate.default_batch_fetch_size` but it has no effect. How did you come to that conclusion?

> For JpaRepository and HibernateCursorItemRepository, these options work normally.

Do you mean this option works with `RepositoryItemReader` (based on a `JpaRepository`)  and `HibernateCursorItemReader`?

I tired to follow the link you shared but there is a lot of (commented) code and I was not able to run the sample (tried to import `spring-batch-n1` but got a compilation error at [this line](https://github.com/jojoldu/blog-code/blob/master/spring-batch-n1/src/main/java/com/jojoldu/batch/job/domain/StoreService.java#L8)). Please try to isolate things and provide a minimal example that we can run to reproduce the issue or a failing unit test and we can re-open this issue for investigation.
