### ISSUE TITLE
Add encoding parameter in StaxEventItemReader [BATCH-2795]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#807]
**[Mahmoud Ben Hassine](https://jira.spring.io/secure/ViewProfile.jspa?name=mbenhassine)** opened **[BATCH-2795](https://jira.spring.io/browse/BATCH-2795?redirect=false)** and commented

The `StaxEventItemReader` does not provide a parameter to use a particular encoding when reading the XML input. It should provide an "encoding" parameter just like the `FlatFileItemReader` [does](https://docs.spring.io/spring-batch/4.1.x/api/org/springframework/batch/item/file/FlatFileItemReader.html#setEncoding-java.lang.String-) for flat files.

---

**Affects:** 4.1.1

**Reference URL:** https://stackoverflow.com/questions/54868274/invalid-utf8-encoding-on-processing-xml-file

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/728

**Comment by benas** [comment]
@jdomigon Thank you for your comment. I see your point. Since this issue is closed, please open another one with your case and we will try to find the best way to allow auto-detecting the encoding from the input file. Thank you upfront.
