### ISSUE TITLE
Support sequence for Spring batch table [BATCH-2794]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#810]
**[NEONKID](https://jira.spring.io/secure/ViewProfile.jspa?name=neonkid)** opened **[BATCH-2794](https://jira.spring.io/browse/BATCH-2794?redirect=false)** and commented

Currently, tables in Spring batches in MSSQL use the IDENTITY attribute and use the table to increment the index number.

However, from the 2012 version of MSSQL, we want to use Sequence in Spring batch by officially providing Sequence. Is there any way to use Sequence in MSSQL?

---

**Affects:** 3.0.8

**Comment by benas** [comment]
This will be addressed in #1448 .
