### ISSUE TITLE
beanRowMapper builder method to JdbcPagingItemReaderBuilder [BATCH-2785]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#819]
**[Drummond Dawson](https://jira.spring.io/secure/ViewProfile.jspa?name=drumonii)** opened **[BATCH-2785](https://jira.spring.io/browse/BATCH-2785?redirect=false)** and commented

Creates a beanRowMapper method to JdbcPagingItemReaderBuilder that sets the rowMapper as a BeanPropertyRowMapper.

---

**Affects:** 4.1.1

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/679

**Comment by benas** [comment]
Resolved with #679 .
