### ISSUE TITLE
JobLauncherTestUtils doesn't always launch new job instance because generated job parameters aren't unique [BATCH-2783]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#821]
**[saikatbhadra](https://jira.spring.io/secure/ViewProfile.jspa?name=saikatbhadra)** opened **[BATCH-2783](https://jira.spring.io/browse/BATCH-2783?redirect=false)** and commented

We noticed that our integration tests for a batch job (with many tests) were failing intermittently.  After debugging, I found that JobLauncherTestUtils.launchJob was occasionally relaunching the same job instance. After looking at the code, I saw that a random number generator was being used which does not guarantee that the number generate would be unique. I believe a UUID would be more appropriate as strongly guarantees that an ID does not repeat (except in highly exceptional cases). 

Pull request here: #3701 

---
No further details from [BATCH-2783](https://jira.spring.io/browse/BATCH-2783?redirect=false)

**Comment by benas** [comment]
Resolved with #3701 .
