### ISSUE TITLE
Add Synchronized version of ItemWriter similar to SynchronizedItemStreamReader [BATCH-2762]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#842]
**[gd-estrepetov](https://jira.spring.io/secure/ViewProfile.jspa?name=gd-estrepetov)** opened **[BATCH-2762](https://jira.spring.io/browse/BATCH-2762?redirect=false)** and commented

This could be useful especially for writers like JsonFileItemWriter.

---

**Affects:** 4.1.0

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/665

**Comment by benas** [comment]
Resolved with #665 .
