### ISSUE TITLE
Thread interference in Partition [BATCH-2753]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#851]
**[ANUJ KHARE](https://jira.spring.io/secure/ViewProfile.jspa?name=anujkhare)** opened **[BATCH-2753](https://jira.spring.io/browse/BATCH-2753?redirect=false)** and commented

I have created a Master slave Partition pattern in Spring batch using various blogs and Spring manual. It works perfectly fine in partitioning using FlatFileItemReader, ItemProcessor and writing to various files created by FlatFileItemWriter. Correct number of output files as per partitions are created and most of the files have correct output data, EXCEPT SOME,... WHERE THE RECORDS FROM OTHER PARTITION HAVE BEEN WRITTEN IN OTHER PARTITION. SAY THE IDS IN EACH LINE REPRESENTS LINE NUMBER AND HAVE RANGE OF RECORDS TO BE WRITTEN IN EACH FILE IS 10, SO IN 4TH PARTITION THE RECORDS SHOULD BE 41 TO 50, BUT THERE IS A THREAD INTERFERENCE AND VALUES ARE LIKE 41,42,100,44,45...

SO ONE RECORD IS BEING PICKED BY THE SAME THREAD WHICH IS HOLDING THE PARTITION. NOT sure how?.

I have tried to make everything synchronized as well, the ItemReader, Writer, Processor, Input, Output, but still suppose a Thread T1 is working on Partition P1, then range of that partition has to be processed, rather this I see in some partitions one record is sneaking in from other partition, picked by same Thread T1. QUITE STRANGE.

---

**Attachments:**
- [Main Logic in Partitioner.PNG](https://jira.spring.io/secure/attachment/26014/Main+Logic+in+Partitioner.PNG) (_14.62 kB_)
- [Master and Slave Partitioner.PNG](https://jira.spring.io/secure/attachment/26015/Master+and+Slave+Partitioner.PNG) (_30.27 kB_)
- [Reader Writer.PNG](https://jira.spring.io/secure/attachment/26013/Reader+Writer.PNG) (_42.28 kB_)

1 votes, 3 watchers

**Comment by benas** [comment]
Please share a repo with a minimal example that we can run to reproduce the issue. Attaching screenshots does not help.
