### ISSUE TITLE
Multithreaded step with Skip limit and throttle limit [BATCH-2744]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#860]
**[Madhusudhanan](https://jira.spring.io/secure/ViewProfile.jspa?name=madhu1991)** opened **[BATCH-2744](https://jira.spring.io/browse/BATCH-2744?redirect=false)** and commented

 
I have Multi-threaded Step with a throttle limit as 10(assume) and the skip limit for the job is been configured as 5. My input file which has 20 records, have more than 10 invalid records in it. In this case whenever my job fails, it doesn't fail when it reaches 5 negative cases. It stops somewhere around 12 or 13th failure.

---
No further details from [BATCH-2744](https://jira.spring.io/browse/BATCH-2744?redirect=false)

**Comment by benas** [comment]
And what is the chunk size? This is an important parameter in the equation as well. I tired to create a similar job config [here](https://github.com/benas/spring-batch-sandbox/blob/master/gh860/src/main/java/com/example/demo/MyJob.java) and each time the step fails at the skip limit as expected (See [results](https://github.com/benas/spring-batch-sandbox/blob/master/gh860/result.md)).

Please provide a minimal example that reproduces the issue and we can dig further.
