### ISSUE TITLE
MongoItemReader (AbstractPaginatedDataItemReader) doesnt skip correctly on multi reading context [BATCH-2742]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#862]
**[fawzi1414](https://jira.spring.io/secure/ViewProfile.jspa?name=fawzi1414)** opened **[BATCH-2742](https://jira.spring.io/browse/BATCH-2742?redirect=false)** and commented

When using MongoItemReader (AbstractPaginatedDataItemReader) in a multi reading context  (multi partition or multi thread) 
  
The jumpToItem doesn't save the page number nor the offset in the same page, or we lose it after method call, so each thread or partition will read from the 0 position which is incorrect .
 
i think that the correction must be done on AbstractPaginatedDataItemReader and not on MongoItemReader.
 
 
 
Use case: multi threading or patition context
 
reading  a collection with 24 documents,
Two thread:
1st thread(currentItemCount=0, maxItemCount=12)
2nd thread(currentItemCount=12, maxItemCount=24)
page size 10, each thread will read 12 documents.
 
 
The first thread will read correctly.
 
The second thread will read the elements from 10 to 24, because even we call the  jumpToItem function  ( jump to the second page (since the page size is 10) and skip the first 2 documents), we dont save the state.
 
So the jump to count state must be saved (page ++ and save the iterator)

---

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/628

**Comment by benas** [comment]
`AbstractPaginatedDataItemReader` extends [AbstractItemCountingItemStreamItemReader](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/item/support/AbstractItemCountingItemStreamItemReader.html) which is documented to be **non thread-safe** as well as its sub-classes. Here is an excerpt from the Javadoc:

```
Subclasses are inherently not thread-safe
```

So using it as is in a multi-threaded environment does not conform to the docs. What you can do is to wrap it in a [SynchronizedItemStreamReader](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/item/support/SynchronizedItemStreamReader.html).
