### ISSUE TITLE
@Retryable does not work when component passed to Async Configuration [BATCH-2739]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#865]
**[Chris](https://jira.spring.io/secure/ViewProfile.jspa?name=springtings)** opened **[BATCH-2739](https://jira.spring.io/browse/BATCH-2739?redirect=false)** and commented

Firstly, I'm sorry if this is the wrong way to create an issue in Spring. 

The following doesn't seem like expected behavior.

 

When I pass a component that has a `@Retryable` annotated method to 

an async uncaught exception handler, the retryable doesn't work. When I debug

I can see that there is no proxy object setup for the passed component.

The component is injected in the constructor of the async uncaught exception handler.

If I use `@Lazy` for the parameter, then everything is okay. Or if I use a setter method instead

of constructor, then everything works.

I'm attaching a sample main directory of the project. 

 

Repro Steps.

1.)  put break point at line 22 in TestScheduledTasks.java

2.) put break point at line 15 in TestChrisComponent.java

3.) Debug run the app.

4.) when the debugger goes to break point 1), if you step forward, you should see no proxy

on the way to break point 2)

5.) Add `@Lazy` to TestChrisComponent on line 19 in AsyncConfigurer.java

 

Repeat Step 3, and now you should see a proxy called.

 

 

Thanks!

 

---

**Attachments:**
- [main.zip](https://jira.spring.io/secure/attachment/25764/main.zip) (_3.27 kB_)

**Comment by benas** [comment]
Thanks for opening this issue and for providing an example. The attached `main.zip` file does not contain any code related to Spring Batch. Spring Retry has been pulled out of Spring Batch and is now a separate project, so please open this issue against [spring-retry](https://github.com/spring-projects/spring-retry/issues).
