### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.MF in all components

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#867]
**[Serban Iordache](https://jira.spring.io/secure/ViewProfile.jspa?name=siordache)** opened **[BATCH-2729](https://jira.spring.io/browse/BATCH-2729?redirect=false)** and commented

To avoid module hell when using spring-batch in modular applications, a stable [automatic module name](http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html) should be provided for all components.

---

**Affects:** 4.1.0

**Comment by sukanth** [comment]
I can take this .. can you assign this to me ?

**Comment by sukanth** [comment]
> I can take this .. can you assign this to me ? @fmbenhassine

here is the PR https://github.com/spring-projects/spring-batch/pull/4372
