### ISSUE TITLE
AbstractCursorItemReader doClose() method is not reentrant [BATCH-2737]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#868]
**[Tommy](https://jira.spring.io/secure/ViewProfile.jspa?name=tommy)** opened **[BATCH-2737](https://jira.spring.io/browse/BATCH-2737?redirect=false)** and commented

The following warning coming up from the `DisposableBeanAdapter`, when it tries to destroy any reader extended from the `AbstractCursorItemReader` by the auto-discovered `close()` method.
`DisposableBeanAdapter : Invocation of destroy method 'close' failed on bean with name 'reader': org.springframework.batch.item.ItemStreamException: Error while closing item reader`

Since the invocation of the `close()` method is already part of the Spring-Batch life-cycle, the `doClose()` method of this class should be reentrant.
The problem lies in the incomplete check around resetting the `autoCommit` state of the underlying connection, which does not respect the already closed connection.

The check should look like something similar

```java
if(this.con != null && !this.conn.isClosed()) {
	this.con.setAutoCommit(this.initialConnectionAutoCommit);
}
```

---

**Affects:** 4.0.0

1 votes, 2 watchers

**Comment by benas** [comment]
I was not able to reproduce the case (See [this repo](https://github.com/benas/spring-batch-lab/tree/master/issues/gh868) where  the warning does not show up), but I see no harm in adding this extra check to make sure the connection is not closed at that point.

Extra check added in 999ef54.
