### ISSUE TITLE
Request to make the postgres db more secure by not using public schema [BATCH-2736]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#869]
**[Gary P Russo](https://jira.spring.io/secure/ViewProfile.jspa?name=garyrusso)** opened **[BATCH-2736](https://jira.spring.io/browse/BATCH-2736?redirect=false)** and commented

To make the database more secure, could you please modify the ddl to use an application specific owner of the database objects instead of using the public schema?

 

---

**Reference URL:** https://dba.stackexchange.com/questions/117109/how-to-manage-default-privileges-for-users-on-a-database-vs-schema

**Comment by benas** [comment]
Spring Batch cannot make this decision, it is up to you to choose in which schema the tables should be created. As mentioned in the [Meta-Data Schema appendix](https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/schema-appendix.html#exampleDDLScripts), the DDL scripts can be used as is or modified as needed.
