### ISSUE TITLE
Document Job/Step Context Serialization changes in Spring Batch 4 [BATCH-2717]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#890]
**[Ben Madore](https://jira.spring.io/secure/ViewProfile.jspa?name=madorb2)** opened **[BATCH-2717](https://jira.spring.io/browse/BATCH-2717?redirect=false)** and commented

Spring Batch 4 is now using Jackson to serialize job/step context, this causes an incompatibility with previously serialized values, but it does not appear to be documented outside of a stackoverflow item. This would hopefully be a part of the what's new in Sping Batch 4  or a "migrating to sb4" section of the documentation

 

 

reference: https://stackoverflow.com/questions/49625231/migration-to-spring-boot-2-and-using-spring-batch-4

---

**Affects:** 4.0.0, 4.0.1

**Comment by benas** [comment]
Resolved with d1d9f0d83f1a815e5947e6c4e48ef61ad1603e01.
