### ISSUE TITLE
JpaCursorItemReader [BATCH-2707]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#901]
**[Michael Minella](https://jira.spring.io/secure/ViewProfile.jspa?name=mminella)** opened **[BATCH-2707](https://jira.spring.io/browse/BATCH-2707?redirect=false)** and commented

JPA 2.2 added the ability to stream results as a cursor instead of just paging. This story is to explore the practicality of using that API to provide something similar to the functionality provided via the `HibernateCursorItemReader` but using the JPA APIs.

---

**Affects:** 4.0.1

**Comment by benas** [comment]
Resolved with #3775 .
