### ISSUE TITLE
Defining step scope in a base class [BATCH-2685]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#923]
**[Tyler K Van Gorder](https://jira.spring.io/secure/ViewProfile.jspa?name=tkvangorder)** opened **[BATCH-2685](https://jira.spring.io/browse/BATCH-2685?redirect=false)** and commented

This issue was originally mentioned on gitter and I was asked to create an issue to investigate this pattern with using bean scanning and `@Component`.

I am running into an interesting issue. I have built a base item reader that will allow parameters (passed into the job) to be mapped in a Mybatis database query used by the descendant class. This requires the step to be StepScope and I was hoping I could put the `@StepScope` on the base class which would then force all subclasses to be in StepScope.

```java
@StepScope
public class ParameterizedMybatisItemReader<T> extends AbstractItemCountingItemStreamItemReader<T> {

    @Value("#{jobParameters}")
    private Map<String, JobParameter> jobParameters;
.
.
.
    @Override
    protected void doOpen() throws Exception {
        JobParameters jobParameters = new JobParameters(this.jobParameters);
        Map<String, Object> parameters = doMapParameters(jobParameters);
        sqlSession = sqlSessionFactory.openSession(ExecutorType.SIMPLE);
        cursor = sqlSession.selectCursor(queryId, parameters);
        cursorIterator = cursor.iterator();
    }

    /**
     * This method is called prior to executing the query on the database and allows for query parameters to be
     * populated/defaulted. This allows the job parameters to be mapped into parameters used by Mybatis. The default
     * behavior is to map each Job parameter into a query parameter. A sub-class can simply override this method if
     * there is not a one-to-one mapping.
     * 
     * @return Parameters that will be passed to the Mybatis query.
     */
    protected Map<String, Object> doMapParameters(JobParameters jobParameters) {
        Map<String, Object> queryParameters = new HashMap<>();
        for (Map.Entry<String,JobParameter> entry : jobParameters.getParameters().entrySet()) {
            if (entry.getKey() == null) {
                continue;
            }
            queryParameters.put(entry.getKey(), entry.getValue()==null?null:entry.getValue().getValue()); 
        }
        return queryParameters;
    }
```

And in the configuration class:

```java
@Bean
       public ParameterizedMybatisItemReader<String> greetingsReader() {    
           return new ParameterizedMybatisItemReader<String>(sqlSessionFactory, TestMapper.class, "findGreeting");
       }
```

It does not appear to work, however if I add the `@StepScope` to the Java Configuration, things work as I expect.

```java
@Bean
        @StepScope
        public ParameterizedMybatisItemReader<String> greetingsReader() {    
            return new ParameterizedMybatisItemReader<String>(sqlSessionFactory, TestMapper.class, "findGreeting");
        }
```

Thanks!

---
No further details from [BATCH-2685](https://jira.spring.io/browse/BATCH-2685?redirect=false)

**Comment by fmbenhassine** [comment]
> This requires the step to be StepScope and I was hoping I could put the `@StepScope` on the base class which would then force all subclasses to be in StepScope.

This is not recommended and does not make sense. There is a note about it in this section of the docs: https://docs.spring.io/spring-batch/reference/step/late-binding.html

```
A Step bean should not be step-scoped. If late binding is needed in a step definition, the components of that step (tasklet, item reader or writer, and so on) are the ones that should be scoped instead.
```

> Defining step scope in a base class

The step scope was moved in a base class `ScopeConfiguration` since this issue was created. Therefore, I am closing it.
