### ISSUE TITLE
Open ChunkMessageChannelItemWriter for extension

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#952]
**[Wim Veldhuis](https://jira.spring.io/secure/ViewProfile.jspa?name=ystava)** opened **[BATCH-2651](https://jira.spring.io/browse/BATCH-2651?redirect=false)** and commented

The current implementation of `ChunkMessageChannelItemWriter.waitForResults` will not read more than maxWaitTimeouts replies from the reply queue, even when there are more due to a larger throttle-limit.

This causes the job to get status failed, and the remaining replies are left ontouched on the reply queue. The next job will then read these replies, and complain about being them for the wrong job, forcing that job to fail as well.

---

**Affects:** 4.0.0.M4

**Reference URL:** https://stackoverflow.com/questions/47227650/remote-batch-job-does-not-read-all-responses-in-afterstep-method

**Comment by fmbenhassine** [comment]
I agree with Michael. Resetting the timeout each time can lead to a batch window being exceeded, which is not and should not be the case in the first place. The timeout should really be related to a time window, and not the number of attempts.

> Also because the method is private, it cannot be overruled.

The class will be opened for extension to be able to override the default behaviour if needed.
