### ISSUE TITLE
Improve Map*Dao memory allocations [BATCH-2650]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#953]
**[Benoit](https://jira.spring.io/secure/ViewProfile.jspa?name=benbenw)** opened **[BATCH-2650](https://jira.spring.io/browse/BATCH-2650?redirect=false)** and commented

When using a MapJobRepository the daos :
* MapJobExecutionDao
* MapStepExecutionDao
* MapExecutionContextDao

are allocating unneeded memory when performing the object deep copy (see static copy methods)

First when re-allocating the internal buffer of the ByteArrayOutputStream
Then when copying it through ByteArrayOutputStream#toByteArray()

Those allocations show up when profiling our batch executions

I'd like to provide an efficient deep copy method based on classes available since spring 4.2
I'm ready to do the PR but where should I create this new method (to be shared between the Map*Dao) ?

---

**Affects:** 3.0.8, 4.0.0.RC1

**Comment by benas** [comment]
Map-based DAOs have been deprecated for removal (#3836), so I see no added value in putting effort on them for the rest of their short lifetime.
