### ISSUE TITLE
Stateful Retry section of the retry.adoc needs example [BATCH-2645]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#958]
**[Glenn Renfro](https://jira.spring.io/secure/ViewProfile.jspa?name=grenfro)** opened **[BATCH-2645](https://jira.spring.io/browse/BATCH-2645?redirect=false)** and commented

This section has no example. It could use one (or more) to show how to inject
// `RetryContextCache` into `RetryTemplate` and passing the `RecoveryCallback` to
// `RetryOperations`

---

**Affects:** 4.0.0.M3

**Comment by benas** [comment]
Spring Batch docs have been [updated](https://github.com/spring-projects/spring-batch/commit/9d2e6c6d2a810074eba9b324fa40b4f795c58aa4) to not include an outdated copy of Spring Retry docs. This issue has been transferred to Spring Retry: https://github.com/spring-projects/spring-retry/issues/223.
